### ISSUE TITLE
[Question] How to implement a recursive function in wren?

### ISSUE THREAD

**Issue by imsomedev** [wren-lang/wren#1025]
Hello, everyone! and sorry if this is a stupid question but I'm new to wren and I couldn't find a way to implement recursive factorial function below is what I tried.
```
var factorial = Fn.new { |n|
  if (n == 0) return 1
  return n * factorial .call(n - 1)
}
```
But I get the following error.
```
[./test line 5] Error at '}': Variable 'factorial' referenced before this definition (first use at line 4).
```

And yes i've read https://wren.io/functions.html, but I wasn't find anything related to recursive. could someone help me to write a recursive function. Thanks.

**Comment by ChayimFriedman2** [comment]
Either make it captial or declare the variable before referencing it. Another option is to create it as a method in a class.

```
// Option 1:
var Factorial = Fn.new {|n|
  if (n == 0) return 1
  return n * Factorial.call(n - 1)
}

// Option 2:
var factorial
factorial = Fn.new {|n|
  if (n == 0) return 1
  return n * factorial.call(n - 1)
}

// Option 2:
class Factorial {
  calculate(n) {
    if (n == 0) return 1
    return n * Factorial.calculate(n - 1)
  }
}
```

**Comment by imsomedev** [comment]
@ChayimFriedman2 Thanks a bunch for the help, Just wondering what's the different between title case variable and regular? 
(note that new for wren)

**Comment by ruby0x1** [comment]
The scope rules are discussed here, https://wren.io/classes.html#implicit-this , basically because you're working inside the top level module there's a rule involved.
