### ISSUE TITLE
bitwise negation gives incorrect results

### ISSUE THREAD

**Issue by jossephus** [wren-lang/wren#1031]
i tried to run 
```
System.print(~1)
```
in wren and it is giving me "4294966895" which is different from what i am used to in c....
is this an error??

**Comment by mhermier** [comment]
It should return ~(uint32t)1.

**Comment by PureFox48** [comment]
The answer you're getting appears to be `~400` rather than `~1`.

The latter gives `4294967294` on my machine (or in hex `0xfffffffe`) which is what I'd expect.

In Wren the operands are converted internally to unsigned 32 bit integers before bit-wise operations are performed.

**Comment by jossephus** [comment]
Thanks for the replys...

**Comment by mhermier** [comment]
Did you find the error? Because how you presented it can be various things?
