### ISSUE TITLE
bug in 'each' iterator

### ISSUE THREAD

**Issue by wwwRongLaw** [wren-lang/wren#1040]
var permute
permute = Fn.new {|source_list|
    if (!(source_list is List)) return [[]]
    if (source_list.count < 2) return [source_list[0..-1]]
    var all_permute = []
    if (source_list.count == 2) {
        all_permute.add(source_list[0..-1])    
        if (source_list[0] != source_list[1]) {
          all_permute.add([source_list[1], source_list[0]])
        }
        return all_permute 
    } 
    var set = {}
    for (i in 0...source_list.count) {
      if (!set[source_list[i]]) {
          set[source_list[i]] = true 
          var plist = permute.call(source_list[0...i] + source_list[(i+1)..-1])
          /////////////////////////////////////////////////////////////////////////////
          // plist.each {|j| all_permute.add([source_list[i]] + j)}
          /////////////////////////////////////////////////////////////////////////////
          for(j in plist) all_permute.add([source_list[i]] + j) 
      }
    } 
    return all_permute 
}

var a = permute.call([1, 2, 2, 4])
a.each {|x| System.print(x)}

1. use plist.each{|j| ...} 
   [1, 2, 2, 4]
   [1, 2, 2, 4] ---> incorrect
   [1, 4, 2, 2]
   .....
2. System.print( something ) before plist.each{|j| ...}
   <print something>

   [1, 2, 2, 4]
   [1, 2, 4, 2] ---> correct
   [1, 4, 2, 2]
   ...
3. use for(j in plist) ...
   [1, 2, 2, 4]
   [1, 2, 4, 2] ---> correct
   [1, 4, 2, 2]
   ...
wren 0.3.0
termux
android

**Comment by joshgoebel** [comment]
Could you reformat your example using actual code blocks and perhaps explain exactly what you think you are seeing here - perhaps with a sentence or two of text? Are you saying each only works if you print some random something first?

**Comment by wwwRongLaw** [comment]
var permute
permute = Fn.new {|source_list|
    if (!(source_list is List)) return [[]]
    if (source_list.count < 2) return [source_list[0..-1]]
    var all_permute = []
    if (source_list.count == 2) {
        all_permute.add(source_list[0..-1])    
        if (source_list[0] != source_list[1]) {
          all_permute.add([source_list[1], source_list[0]])
        }
        return all_permute 
    } 
    var set = {}
    for (i in 0...source_list.count) {
      if (!set[source_list[i]]) {
          set[source_list[i]] = true 
          var plist = permute.call(source_list[0...i] + source_list[(i+1)..-1])
          
          //for(j in plist) all_permute.add([source_list[i]] + j) 
          System.print("")
          plist.each{|j| all_permute.add([source_list[i]] + j)} 
          
      }
    } 
    return all_permute 
}

var a = permute.call([1, 2, 2, 4])
a.each {|x| System.print(x)}

**Comment by joshgoebel** [comment]
I'm not sure what you're seeing but perhaps it's a long fixed bug.  On wren-console with Wren 0.4 I see the "correct" output with case 1, the one you say is supposed to be a failing case.

```
% wrenc permute.wren
[1, 2, 2, 4]
[1, 2, 4, 2]
[1, 4, 2, 2]
[2, 1, 2, 4]
[2, 1, 4, 2]
[2, 2, 1, 4]
[2, 2, 4, 1]
[2, 4, 1, 2]
[2, 4, 2, 1]
[4, 1, 2, 2]
[4, 2, 1, 2]
[4, 2, 2, 1]
```

**Comment by ruby0x1** [comment]
This does sound like the issues similar to #801, #770 and #761, which was fixed in 0.4 by #807. which version of wren are you running?

**Comment by joshgoebel** [comment]
The first post says 0.3 so I'd say this could be closed if it can't be reproduced on 04

**Comment by wwwRongLaw** [comment]
Sorry for wasting my time, I tried with 0.4 and it works, thanks.

**Comment by ruby0x1** [comment]
not a problem @wwwRongLaw! glad it was resolved.
