### ISSUE TITLE
How i import a module?

### ISSUE THREAD

**Issue by kefd** [wren-lang/wren#1042]
How i import a module 

im trying to import a module like this 

file 1  (module) 
```
var a = 1

```

file 2 (main)
```
import "hello_world" for a

System.print(a)

```

i want to do this but i get an error:

[kefd@fedora hello_world]$ wren_cli hello_world_test.wren 
Could not load module 'hello_world'.
[./hello_world_test line 1] in (script)

and how i can get a class from a module?

**Comment by ruby0x1** [comment]
There are [rules about capitalization](https://wren.io/classes.html#implicit-this) to be aware of. 
So you'll probably want to do this instead:

```js
var A = 1
```

```
import "hello_world" for A
```

Secondly, it's hard to tell where your error lies. You need to implement the `loadModuleFn` on the vm configuration. In that function, you return the source code for the module (or null if not found). 

https://wren.io/embedding/configuring-the-vm.html#loadmodulefn

**Comment by ChayimFriedman2** [comment]
You can import lowercase names IIRC.

However if in the CLI, then you should `import "./hello_world"`.

**Comment by ruby0x1** [comment]
> You can import lowercase names IIRC.|

Even if so, in the interest of not confusing people when mixing, and to make sure it's not a surprise, I prefer to simplify and not suggest this.

**Comment by ChayimFriedman2** [comment]
I just wanted to say that this is not the problem, I fully agree.

**Comment by kefd** [comment]
> Você pode importar nomes em letras minúsculas IIRC.
> 
> No entanto, se estiver na CLI, você deve `import "./hello_world"`.

omg this save me a lot, thanks bro :rocket: 

and thanks for you guys
