### ISSUE TITLE
Using userdata and finalizers together might imply Global State - even if unwanted

### ISSUE THREAD

**Issue by Pallavering** [wren-lang/wren#1043]
Say that we'd like to set our associated `WrenVM*` userdata to be a map of types to different pool allocators of that size via `wrenSetUserData(WrenVM*)`. Wren keeps its state completely encapsulated in `WrenVM*`.

When allocating an instance of a foreign class, Wren calls the function in `WrenForeignClassMethods.allocate` of function type `void (WrenVM*)`, giving me access to a pool allocator of my choice through `wrenGetUserData(WrenVM*)`, which I am able to call inside the `allocate` function since I am given a `WrenVM*` to access my - *non-global* - allocator.

As the time comes to clean up my messes, Wren calls `WrenForeignClassMethods.finalize` of function type `void (void*)`, but my allocator - which needs to be notified of deallocation *somehow* - is not at all reachable, since it is nicely encapsulated in `WrenVM*`, forcing me to provide a global allocator while Wren can keep its glorious encapsulation.

Either that, or every Wren foreign object that I want to create, needs to carry an extra `WrenVM*` pointer as baggage just so I can get to my allocators.

Do we gain any advantages from not letting `WrenFinalizerFn` (also known as `void (*)(void*)`) take a `WrenVM*` parameter? I see a major disadvantage in this sort of purity, and it forces me to provide global state.

A big no-no.

**Comment by mhermier** [comment]
The idea is not worth it. If you need to pass any data for destruction, you
can alter the passed type so it holds the required data.

**Comment by Pallavering** [comment]
@mhermier That is exactly the crux. Do I really need to carry an extra `WrenVM*` pointer in *every object of every foreign type* just to get to the userdata that I require to deallocate these objects? I plan to allocate a lot of small, separate foreign objects (that‘s why I use a pool allocator in the first place), and that redundancy in data is just heartbreaking.

**Comment by mhermier** [comment]
Passing the WrenVM* would solve a range of problems for sure for cheap.

But in you specific case and looking at the situation in C++ with
allocators, I think it safer to let the allocators next to its allocated
pointers. Even if it waste memory.

**Comment by ChayimFriedman2** [comment]
Passing the VM is misleading, since finalizers should not invoke any functionality of the VM. However, we could pass the VM's user data directly. You can fork the repo and do so if you want.

However I agree with @mhermier that for allocators, it's better to store them side-by-side. And I don't see many cases where providing access to the user data will be beneficial.

**Comment by Pallavering** [comment]
You might be right; providing the userdata to the finalizer is only a matter of changing a handful of lines at most, I suppose. Oh well. I might apply that change in my own projects but it doesn't really seem like such a big deal anymore. Thanks!
