### ISSUE TITLE
[RFC] Make the use of call method to invoke functions optional.

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#1045]
One thing I find a bit of a nuisance in Wren (and I don't think I'm alone in this) is having to use the ```call``` method to invoke a function.

Looking back at old issues and #158 in particular, @munificent  gave the following example as to why removing the need for ```call``` would be problematic:

```javascript
class Foo {
  a { _a }
  a(arg) { IO.print("method) }

  new {
    _a = new Fn {|arg| IO.print("fn") }
    a("arg") // <--
  }
}
```

and he commented:

> How do we interpret a("arg"). Is it:

 >1.   Invoke the a getter, get the result (a function) and then call that.
 >2.   Invoke the a method, passing in the argument.

>The obvious answer is 2.

I accept, of course, that there would be an ambiguity here. However, what I would question is whether that ambiguity is serious enough and occurs sufficiently often to prevent us from removing the need for ```call```?

Rather than removing it altogether, suppose instead we simply make the need for ```call``` optional as it was in some old BASICs and specify that, in an ambiguous situation such as the above,  option 2. would always win. The advantages of this would be that:

1. It would be backwards compatible - code written with ```call``` would work as it did before.

2. The working of functions and the _```Fn```_ class would otherwise be unaffected as would callable classes.

3. Ambiguities could still be resolved by using ```call``` rather than parenthesization.

4. There is a precedent for dealing with functions in a special way, namely the shorter `block argument` syntax.

The disadvantages would be:

1. It would make the compiler more complicated - when seeing something like `func()` the compiler would need to interpret it as `func.call()`.

2. You'd need to remember that there could be ambiguities if ```call``` were not used.

I look forward to comments.

**Comment by joshgoebel** [comment]
Call is the only thing I dislike about Wren, and that's saying a lot. Feels like extra complexity/clutter in the language grammar just to (I think) allow for a simpler compiler. 

In no other area of the language do I feel like trade offs had to be made - making this one exception all the more annoying. 

So I'd be in favor of such a proposal for sure.

**Comment by mhermier** [comment]
The trivial solution to this ambiguity is parentheses. A less obvious is an
operator that force evaluation of the what follow as a name or nameless
argument.
I don't think direct usage is spread enough to justify something else than
parentheses. I may be wrong, but I suspect most usage would be function
factory passed to utility methods (lazyness/composition operators/...), and
not direct call.

**Comment by PureFox48** [comment]
Well, parentheses would be one way to resolve an ambiguity but, if the use of ```call``` were to become optional, I personally would prefer to stick with that to resolve ambiguous situations.

Not that there would be many - I've written a lot of Wren code in the last 16 months and I'm struggling to think of a single instance where not using ```call``` would have created an ambiguity.

**Comment by mhermier** [comment]
I don't advocate to change current solution. call is simple stupid and
works well.

**Comment by PureFox48** [comment]
Yes, it works OK but, IMO, it does the language no favors.

It makes it look like an old-fashioned BASIC where you had to use call to invoke a user-defined function.

**Comment by ChayimFriedman2** [comment]
> It makes it look like an old-fashioned BASIC where you had to use call to invoke a user-defined function.

Actually, I like how it makes Wren look very object-oriented, but I understand there are other opinions.

However, while parentheses are a working (though obviously less elegant) solution, how is the compiler supposed to know what to call? Consider the following situation:
```wren
class Foo {
  construct new() {}
  
  a { _a }
  f() {
    _a = Fn.new {|arg| System.print("fn") }
    a("arg") // <--
  }
}
class Bar is Foo {
  construct new() {}
  a(arg) { System.print("method") }
}
Foo.new().f() // Should print "fn"
Bar.new().f() // Should print "method"
```

(BTW, it's really frustrating that we cannot share links to code in the playground.)

**Comment by PureFox48** [comment]
Well, at the present time, that code doesn't compile unless I change line 7 to : ```a.call("arg")``` when it displays ```fn``` twice. It's not printing ```method``` because Bar's ```a``` takes a single parameter, it's not a getter. 

Ideally, if ```call``` were made optional, I'd want it to work just the same without ```call``` as it did before. That might be easier said than done - particularly with tortuous code such as this - but I'm not wanting to change the behavior of the code just its appearance.

**Comment by ChayimFriedman2** [comment]
This is what I mean: You need to keep `Bar.new().f()` printing "method", but you want to make `Foo.new().f()` printing "fn". How is the compiler supposed to do that?

**Comment by PureFox48** [comment]
But it's not printing ```method``` to start with -  it's not printing anything -  unless you're thinking of making some other change than the one I made to line 7 to get it to run.

**Comment by ChayimFriedman2** [comment]
I commented the call to `Foo.new().f()` because right now it is, indeed, invalid. But you want to make it valid and print "fn" - how, then, will you differentiate these calls?

**Comment by PureFox48** [comment]
Well,  if you comment out ```Foo.new().f()``` then it does indeed run and print ```method``` because ```a(arg)``` is now interpreted as a call to Bar's ```a(arg)```.

If you want to make it print both ```fn``` and ```method``` just now, then I think you'd have to rewrite it like this so that Foo's ```a``` now takes a parameter and is no longer a getter:

```javascript
class Foo {
  construct new() {}
  
  a(arg) { _a.call(arg) }  //  <-- changed here
  f() {
    _a = Fn.new {|arg| System.print("fn") }
    a("arg") // <--
  }
}
class Bar is Foo {
  construct new() {}
  a(arg) { System.print("method") }
}
Foo.new().f() // Should print "fn"
Bar.new().f() // Should print "method"
```
But I'm struggling to see how making ```call``` optional would make the situation any worse than it currently is. It would just be a case where you'd still need  to use ```call``` to maintain the existing behavior because the compiler wouldn't know that ```_a``` was a function.

**Comment by ChayimFriedman2** [comment]
That's exactly the point: it would be a case where you need to put parentheses explicitly, but _every case will be so_!

For example, take the following:
```
class A {
  foo(callback) {
    callback(1)
  }
}
```
Clearly the compiler can see this is equivalent to `callback.call(1)`, isn't it?

Nope. Consider (in a different module, even):
```
class B is A {
  callback(i) {}
}
```
Now, when this class is used, we need to call the method `callback(_)`. So we need to disambiguate even this "obvious" case with `.call()`.

Generally, _it's impossible for the compiler to reason about the existence of some method_. It may be possible with static methods (I'm not sure), but I'm not sure we want to give so much partial solution.

**Comment by PureFox48** [comment]
Well in that case I'm puzzled why @Munificent said in #158:

> I think if we really wanted to, we could get rid of .call but I think it keeps things simpler to require it.

It was this sentence that inspired me to resurrect this matter in the first place.

If it's impossible for the compiler to resolve these situations in a dynamically typed language, I wonder if he had in mind making the runtime a bit smarter?

**Comment by ChayimFriedman2** [comment]
It can be, or perhaps he talked about a syntactic difference (like requiring parentheses). I don't know.

**Comment by PureFox48** [comment]
One syntactic proposal I definitely didn't like was just using a dot (```.```) on its own and, if it came down to a choice between requiring parentheses and ```call```, I'd take the latter every time.

Anyway, you've persuaded me that making ```call``` optional is not really viable, so I'm going to close this now and live with things as they are.

Thanks everyone for a useful discussion.
