### ISSUE TITLE
allow the caller to specify a preallocated array for the heap

### ISSUE THREAD

**Issue by jockm** [wren-lang/wren#1047]
In embedded, and non memory protected environments it is often desirable to preallocate all of memory as arrays and not use `malloc()` and `free()`.  So it would be nice to have an option in the config to pass in the heap.  Alternatively you could allow the caller to pass in the functions for `malloc()` and `free()` (DukTape does this)

**Comment by ruby0x1** [comment]
You can already configure a custom allocation function which will allocate from your fixed heap. 

https://wren.io/embedding/configuring-the-vm.html
