### ISSUE TITLE
Bug: List does not implement 'remove(_)'

### ISSUE THREAD

**Issue by mestrey** [wren-lang/wren#1049]
When you want to use the remove(String) method on list.

You can reproduce it even from the documentation example :
```js
var letters = ["a", "b", "c", "d"]
letters.removeAt(1)
System.print(letters) //> [a, c, d]
letters.remove("a")
System.print(letters) //> [c, d]
```

```js
[a, c, d]
List does not implement 'remove(_)'.
[./test line 4] in (script)
```

Version: wren 0.3.0

**Comment by joshgoebel** [comment]
Wren is at 0.4 now. ￼CLI is not. Likely this is what you are seeing.

**Comment by mestrey** [comment]
Oh you're write,
Closing it
Thanks for the response
