### ISSUE TITLE
Potentially dangerous behavior when functions are passed too many arguments

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#1050]
In the documentation about [functions](https://wren.io/functions.html) it says in the Function parameters section:

> If you pass too many arguments, the extras are ignored.

However, I noticed today that this isn't true. Instead of getting ignored, they are taken off the stack and assigned to local variables within the function whose own assignment values get passed further down the food-chain!

For example, consider the following simple script and the output it produces:

```javascript
var f = Fn.new { |a|
    var i = 1
    System.print("i = %(i)")
    var j = 2
    System.print("j = %(j)")
    return a + i + j
}

System.print("a + i + j = %(f.call(3))\n")
System.print("a + i + j = %(f.call(3, 4))\n")
System.print("a + i + j = %(f.call(3, 4, 5))")

/*
i = 1
j = 2
a + i + j = 6

i = 4
j = 1
a + i + j = 8

i = 4
j = 5
a + i + j = 12
*/
```
The first call passes the correct number of arguments and so works as expected.

The second call passes an extra  argument '4' which gets assigned to ```i``` and then ```j``` is assigned what ```i``` would otherwise have been assigned ('1').

The third call passes two extra arguments '4' and '5' which are assigned in turn to ```i``` and  ```j``` whose own assigned values are apparently discarded.

Needless to say this is potentially very dangerous behavior and probably not that rare. The reason I noticed it today is that I'd written a function which originally required 2 parameters, then decided I didn't need the second one but forgot to change the function call. Luckily, the extra parameter (a ```Bool```) was a different type to the local variable (```Num```) and so all that happened was that I received a puzzling runtime error when I tried to manipulate the latter. However, if they had been the same type, there would have been no error and the results would have been completely wrong.

I don't know how easy or expensive it is to prevent this behavior but, if nothing easy can be done, then I think we should at least warn about it in the documentation.

**Comment by joshgoebel** [comment]
Confirmed on Wren 0.4.  This seems quite dangerous and something that should be fixed, not just a docpatch. IMHO.

**Comment by PureFox48** [comment]
Also was just the same in Wren 0.2.
 
I agree that it needs fixing - preferably by outlawing excess arguments altogether.

Surprised it was done like this in the first place when class methods need to be passed the exact number of arguments. Possibly done for performance reasons.

**Comment by datatypevoid** [comment]
What is an example of this being dangerous, out of curiousity?

NodeJS/Javascript also has this behavior and has got by just fine over the years:
```
> function fn (a, b, c) { console.log(arguments); return [a, b, c] }
undefined
> fn(1, 2, 3)
[Arguments] { '0': 1, '1': 2, '2': 3 }
[ 1, 2, 3 ]
> fn(1, 2, 3, 4)
[Arguments] { '0': 1, '1': 2, '2': 3, '3': 4 }
[ 1, 2, 3 ]
```

**Comment by PureFox48** [comment]
The example I've given (although simplified) is dangerous.

Although the correct answer is 6,  you get different answers if you pass extra arguments.

If some complex calculation were being carried out, you might not even realize the answer was  wrong or, if you did, spend some time debugging it.

**Comment by minirop** [comment]
@datatypevoid the last argument overrides the local variable. in JS it would be like this:
```js
> function fn(a, b, c) { var d = 42; return d; }
undefined
> fn(1,2,3,4);
4 // instead of 42
```

**Comment by datatypevoid** [comment]
Yes, it was first thing in the morning and I wasn't thinking straight yet, I immediately realized what was the dangerous part after I posted, and promptly deleted.

**Comment by PureFox48** [comment]
I noticed when I was searching for something else that this issue has already been raised before in #731 which is still open.
 
So I'm going to close this one now to avoid duplication.
