### ISSUE TITLE
Crash on returning new foreign class in foreign class function

### ISSUE THREAD

**Issue by TwistedTwigleg** [wren-lang/wren#1062]
Hi everyone! I've been trying to integrate Wren into a Godot module for the purposes of allowing the user to write and execute code during runtime all from within the Godot editor. I've gotten Wren integrated and working for the most part, but I've hit a bit of a snag with exposing foreign functions that return foreign classes. I seem to be able to return a foreign class using `wrenSetSlotNewForeign`, but whenever I try to access or do anything with the newly returned foreign class, it crashes.

Here's the Wren code:

~~~
foreign class Vector2 {
	construct create(x, y) {}
	
	foreign x
	foreign x()
	foreign x=(val)
	foreign y
	foreign y()
	foreign y=(val)
	
	foreign abs()
	
	foreign set(x, y)
	foreign normalize()
	foreign get_as_string()
	foreign print_to_console()
}

// ===============================
var vec = Vector2.create(10, 10)

var vec_x = vec.x()
var vec_y = vec.y()
System.print("Vector X indirect:%(vec_x)")
System.print("Vector Y indirect:%(vec_y)")
//vec.print_to_console()

vec.set(10, 20)
System.print("Vector X:%(vec.x)")
System.print("Vector Y:%(vec.y)")
//vec.print_to_console()

vec.normalize()
System.print("Vector as string: %(vec.get_as_string())")
//vec.print_to_console()

vec.set(-20, -40)
// This does not cause a crash and according to a System.print, it is assigned to an instance of a Vector2
var vec_abs = vec.abs()
// However, this causes it to crash
System.print("Vector X:%(vec_abs.x)")
System.print("Vector Y:%(vec_abs.y)")
// ===============================
~~~

All of the code above printing the X and Y variables in `vec_abs` works fine, but whenever I try to access anything in `vec_abs` it crashes.

Here's how I have the class allocated, finalized, and bound in C++
(I removed some necessary bits, like the other foreign functions)

~~~
void Foreign_Vector2::allocate(WrenVM* vm)
{
    Vector2* vec2 = (Vector2*)wrenSetSlotNewForeign(vm, 0, 0, sizeof(Vector2));
    double val_x = wrenGetSlotDouble(vm, 1);
    double val_y = wrenGetSlotDouble(vm, 2);
    vec2->x = val_x;
    vec2->y = val_y;
}
void Foreign_Vector2::finalize(void* data)
{
    // Not really anything to do here, I don't think...
}
WrenForeignMethodFn Foreign_Vector2::bind_methods(WrenVM* vm, const char* module, const char* className, bool isStatic, const char* signature)
{
    if (!isStatic)
    {
        // Properties:
        // ========================
        if (strcmp(signature, "x()") == 0) { return Foreign_Vector2::get_vector2_x; }
        else if (strcmp(signature, "x") == 0) { return Foreign_Vector2::get_vector2_x; }
        else if (strcmp(signature, "x=(_)") == 0) { return Foreign_Vector2::set_vector2_x; }

        else if (strcmp(signature, "y()") == 0) { return Foreign_Vector2::get_vector2_y; }
        else if (strcmp(signature, "y") == 0) { return Foreign_Vector2::get_vector2_y; }
        else if (strcmp(signature, "y=(_)") == 0) { return Foreign_Vector2::set_vector2_y; }
        // ========================

        // Methods:
        // ========================
        else if (strcmp(signature, "abs()") == 0) { return Foreign_Vector2::method_vector2_abs; }
        // ========================

        // Misc
        // ========================
        else if (strcmp(signature, "set(_,_)") == 0)
        {
            return Foreign_Vector2::custom_vector2_set;
        }
        else if (strcmp(signature, "normalize()") == 0)
        {
            return Foreign_Vector2::custom_vector2_normalize;
        }
        else if (strcmp(signature, "get_as_string()") == 0)
        {
            return Foreign_Vector2::custom_vector2_get_as_string;
        }
        else if (strcmp(signature, "print_to_console()") == 0)
        {
            return Foreign_Vector2::print_to_console;
        }
        // ========================
    }
    return NULL;
}
bool Foreign_Vector2::bind_classes(WrenVM* vm, const char* module, const char* className, WrenForeignClassMethods *methods)
{
    if (strcmp(className, "Vector2") == 0)
    {
        methods->allocate = Foreign_Vector2::allocate;
        methods->finalize = Foreign_Vector2::finalize;
        return true;
    }
    return false;
}

void Foreign_Vector2::method_vector2_abs(WrenVM* vm)
{
    Vector2* vec = (Vector2*)wrenGetSlotForeign(vm, 0);


    // Didn't work
    /*
    Vector2* new_vec2 = (Vector2*)wrenSetSlotNewForeign(vm, 0, 0, sizeof(Vector2));
    new_vec2 = new Vector2(vec->abs());
    */

    // Didn't work
    /*
    void* bytes = wrenSetSlotNewForeign(vm, 0, 0, sizeof(Vector2));
    new (bytes) Vector2(vec->abs());
    */
    
    // Doesn't work
    auto* memory = wrenSetSlotNewForeign(vm, 0, 1, sizeof(Vector2));
    new (memory) Vector2();
    auto* wrapper = reinterpret_cast<Vector2*>(memory);
    Vector2 vec_abs = vec->abs();
    wrapper->x = vec_abs.x;
    wrapper->y = vec_abs.y;
}
~~~

All of the functions in the C++ file are static, public, and defined in the header with the same syntax and formatting as the file above.

Is it possible to return a foreign class as a return value from a foreign function? I feel like I am probably missing something and that's why it's not working, but so far all of the adjustments and tests I've done have all resulted in crashes.

**Comment by mhermier** [comment]
There is an error in your invocation of wrenSetSlotNewForeign. Second slot
argument should be the class of the foreign. Your first try, attempt to use
an instance, and your second try to access nothing. You have to grow the
stack put the class at slot 1 (possibly from slot 0, I don't remember if we
have an API for that, or if you have to use a WrenHandle), and with that
you'll be able to create your instance.

**Comment by TwistedTwigleg** [comment]
Something like this?

~~~
WrenHandle* test_handle = wrenGetSlotHandle(vm, 0);

Vector2* new_vec2 = (Vector2*)wrenSetSlotNewForeign(vm, 0, 1, sizeof(Vector2));

Vector2 vec_abs = vec->abs();
new_vec2->x = vec_abs.x;
new_vec2->y = vec_abs.y;

test_handle = (WrenHandle*)new_vec2;
wrenSetSlotHandle(vm, 0, test_handle);
~~~

The code above, when in the function to return the foreign object, gives me this:

~~~
Vector Type: 34359746768
[Runtime Error] Num does not implement 'x'.
[main line 88] in (script)
Runtime Error!
~~~

Which is closer, but it still isn't returning the right type. I tried using slot `1` with `wrenGetSlotHandle`, but it was crashing like before, while using slot `0` seems to have it return a number rather than the foreign Vector2 class.

I'm sure I'm missing something obvious.

**Comment by mhermier** [comment]
Unless I'm is taken, there is nothing in slot 1. So you have to grow the
stack and push the class from slot 0 to slot 1 before calling
wrenSetSlotNewHandle(vm, 0, 1, size of(Vectors)).

**Comment by TwistedTwigleg** [comment]
When you say grow the stack and push the class, I'm not quite following how to do that. I've tried using `wrenGetSlotHandle(vm, 0)` and `wrenGetSlotHandle(vm, 1)` and then setting it to the class using `test_handle = (WrenHandle*)new_vec2` but I'm guessing that is not the way to do it or I am still missing something.

**Comment by TwistedTwigleg** [comment]
Okay, I think I figured it out! I think you need to use `wrenGetVariable` and point it to the Foreign class you define in Wren code and store that in the slot that matches the `class_slot` in `wrenSetSlotNewForeign`.

I found how to get and store the class into the slot from [this code snippet in this issue](https://github.com/wren-lang/wren/issues/498#issuecomment-376275611). Now it seems to be working.

For anyone looking in the future, here's the code that I found that works:

~~~
wrenGetVariable(vm, "main", "Vector2", 1);
Vector2* new_vec2 = (Vector2*)wrenSetSlotNewForeign(vm, 0, 1, sizeof(Vector2));
Vector2 vec_abs = vec->abs();
new_vec2->x = vec_abs.x;
new_vec2->y = vec_abs.y;
~~~

And I'm loading the code into the `main` module with my Wren foreign class defined as below:

~~~
foreign class Vector2 {
	construct create(x, y) {}
	
	foreign x
	foreign x()
	foreign x=(val)
	foreign y
	foreign y()
	foreign y=(val)
	
	foreign abs()
	
	foreign set(x, y)
	foreign normalize()
	foreign get_as_string()
	foreign print_to_console()
}
~~~

Thanks @mhermier for the help!

Is this solution correct? And if so, should I close this issue?

**Comment by mhermier** [comment]
The solution is correct (with possible some subtle technical issues, like ensuring the stack size, and accessing the class via module) but slow because of `wrenGetVariable`.
Maybe a function should be added that would put the type of a slot to a destination slot. It would ease coding and avoid some awkward questions like were to store the reference/handle to the class in many cases.

**Comment by TwistedTwigleg** [comment]
Great!
I plan to change how the code I’m using a bit so I can use a handle to store the class, rather than using `wrenGetVariable`, now that I understand more on how it all works.

I think having a function for this sort of thing would be helpful, especially for those getting started, or perhaps having an example in the documentation/embedding section of the website that shows a quick example. I knew I was missing something, but until I got your help, I wasn’t able to figure it out even after looking around on both GitHub and via Google.

Thanks so much for the help, I really appreciate it!
I’ll close the issue since a solution was found.
