### ISSUE TITLE
Optional brackets around expressions in statements

### ISSUE THREAD

**Issue by RazrFalcon** [wren-lang/wren#1070]
Hi! I'm interested in how easy is to allow optional brackets around expressions in statements. Basically:

```c
if n < 0 {
for i in 0...5 {
while n > 0 {
```

I've actually tried modifying the [`ifStatement` parsing code](https://github.com/wren-lang/wren/blob/3c43de7485dd49b1c2a79904ea3d7c79ffc81cdf/src/vm/wren_compiler.c#L3123), but it seems you cannot simply ignore brackets. They are used somewhere down the line.

I think optional brackets should work just fine, as long as we have `{` on the same line. So this can be done in a backward-compatible way. It would make the code a bit cleaner.
I'm not saying it should be added to the language itself, it's not an RFC. But I would be interested in adding this to my own fork.

**Comment by munificent** [comment]
Doing this would interact poorly with block arguments. Consider:

```
if foo { code... }
```

Is that an `if` statement whose condition is `foo` and whose body is the block, or is it an `if` statement whose condition expression is `foo { code... }`? The parser can't tell until it has completely finished parsing that block and can see if there's another block afterwards. That kind of arbitrary lookahead doesn't play nice with a single-pass compiler like Wren uses.

I understand the desire to eliminate unnecessary punctuation, but I think the grammar is a lot simpler and more regular if we just require parentheses for `if` and `for` expressions.

**Comment by RazrFalcon** [comment]
Thanks! I have not considered block arguments.
