### ISSUE TITLE
Accessing Wren `map` objects from the host application

### ISSUE THREAD

**Issue by gkjpettet** [wren-lang/wren#1074]
I'm currently attempting to embed Wren into an app.

I see it's possible to retrieve simple values from the VM with methods such as `getSlotBool()` and `getSlotDouble()` but how do I get or set values from a Wren `map` from C?

The only non-simple values I see being able to set from C are list values with `wrenInsertInList()` and `wrenSetSlotNewList()` but there doesn't seem to be a `map` equivalent.

**Comment by ruby0x1** [comment]
The following API. At the moment you can't iterate from in C, unless you pass the keys in as a list and iterate on that to get values from the map. 
```c
wrenSetSlotNewMap
wrenGetMapCount
wrenGetMapContainsKey
wrenGetMapValue
wrenSetMapValue
wrenRemoveMapValue
```

**Comment by gkjpettet** [comment]
Fabulous thank you. I didn’t see it documented over at wren.io which is why I think I missed it.
