### ISSUE TITLE
(Feature Request) Support for RegEx

### ISSUE THREAD

**Issue by whmsft** [wren-lang/wren#1081]
I think RegEx is really important..
If Regex is there JSON and YAML decoding and encoding too could be possible

I myself tried to make a handwritten "port" of "re" module of python.. (regex module)
But it got complex, It needed more modules, which would need to be ported, and one of them required python's compiled files (pyc) and so i quit.

Wouldn't it be great if you (the dev team) do the thing? after all, you're more experienced than me...

I expect there must be another feature request regarding the same due to RegEx's importance...

**Comment by datatypevoid** [comment]
I don't support the idea of regex in core wren, but there are json and toml encoders/decoders written in wren already.

See: https://github.com/wren-lang/wren/wiki/Modules#parsing

**Comment by joshgoebel** [comment]
FYI, JSON support comes per-bundled with [wren-console](https://github.com/joshgoebel/wren-console) and we're open to adding a regex library as well. We just need to agree on an implementation and find someone to put in the time. 

I do agree for those of us wanting to do more utility kind of scripting that the lack of regex is a loss.

**Comment by ruby0x1** [comment]
the plan was an optional module (similar to random and meta) that adds regex as a starting point. i've got an implementation and an api i'm using that I was going to extract soon (I recently brought the json one out and working toward regex too).
