### ISSUE TITLE
Num arithmetic appears to be losing precision

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#1109]
I've noticed recently that 'Num' arithmetic in Wren can lose precision compared to 64 bit floating point arithmetic in other languages.  Take a look, for instance, at [this (rather extreme) example](https://rosettacode.org/wiki/Meissel%E2%80%93Mertens_constant#%7B%7Bheader%7CWren%7D%7D) .

One thing that's always worried me is that _System.print_ never displays a number with more than 14 significant digits even though, on the face of it, 15 should be safe for doubles. 

This makes me wonder whether calculations are being carried out internally to a lower precision than would normally be the case for double arithmetic in C. Does anyone know whether this is in fact so and, if it is, what the reason for it is?

I'm using nowadays an x64 Linux box though I doubt whether this is a platform specific issue or, for that matter, a display issue because (as the example shows) inaccuracies can creep in well below the 15/16 digit threshold.

**Comment by mhermier** [comment]
Considering how it rapidly converge there is obviously a bug somewhere...

**Comment by mhermier** [comment]
Found the chosen algorithm has a *bug* where the precision is dependent of the order of operation. Tweaking the algorithm a little to:
```javascript
import "./math" for Int
import "./fmt" for Fmt

var euler = 0.57721566490153286
var primes = Int.primeSieve(2.pow(31))
var pc = primes.count
var sum = 0
var c = 0
System.print("Primes added         M")
System.print("------------  --------------")
for (p in primes) {
    var rp = 1/p
    sum = (1-rp).log + rp + sum
    c = c + 1
    if ((c % 1e7) == 0 || c == pc) Fmt.print("$,11d   $0.12f", c, sum + euler)
}
```
produce the expected output (identical to the Go reference implementation):
```
Primes added         M
------------  --------------
 10,000,000   0.261497212987
 20,000,000   0.261497212912
 30,000,000   0.261497212889
 40,000,000   0.261497212878
 50,000,000   0.261497212871
 60,000,000   0.261497212867
 70,000,000   0.261497212864
 80,000,000   0.261497212862
 90,000,000   0.261497212861
100,000,000   0.261497212859
105,097,565   0.261497212858
```

**Comment by PureFox48** [comment]
Wow, thank you - that's a relief :)

I actually tried changing the order of the operations in that line but I didn't think to put 'sum' at the end.

I guess the next question is why does changing the order make a difference.  Could be due to the fact that Go is using a compound operator (+=) which we don't (yet) have but that's a question for another day.

Closing the issue now.

**Comment by PureFox48** [comment]
Yeah,  the defence against this (which frankly I should have remembered) is to sum the 'smallest'  numbers first and then add the result to the 'biggest' number.

In this example, after a lot of iterations, ```log(1 - 1/p)``` was very close to ```1/p``` apart from the sign, so adding those two first maximized precision.

Go etc. were using  ```+=``` and so would have done this automatically.

Anyway, the important thing is that this was just an issue with my code and not a bug or restriction in Wren itself.

So thanks again for figuring it out :)

**Comment by mhermier** [comment]
No problem, it was quite trivial. It took e more time to setup the test
case, than find the issue.
