### ISSUE TITLE
[RFC] Keyword List Data Structure

### ISSUE THREAD

**Issue by clsource** [wren-lang/wren#1113]
Reading #1112 I though that Maybe a new Data Structure can be created for Wren.
From [Elixir's Keyword list](https://www.djm.org.uk/posts/elixir-keyword-lists-function-parameters/).

Keyword lists in Elixir are simply a special case of a list, their contents being made up entirely of 2-item "pair" tuples with the first item of each being an Elixir :atom. Unlike maps, they are ordered and may contain multiple values for the same key. Due to their prevalence in the language, a lot of syntactic sugar has been created to make working with them easier and more idiomatic. For example, during creation:

```
iex(1)> [{:cats, 2}, {:dogs, 1}] == [cats: 2, dogs: 1]
true
```

In [Wren this maybe created](https://wren.io/try/?code=MYGwhgzhAEDSCmBPA7gewE4BNoG8BQ0hA1krgPomIC+BhAbmCAK7zkPPw2HTCoB2EAC7omwQdD7xkACkoAaaOxYBKXLW7QKpALzRK67mSWtdx9V0KDUAZWEBLPgHNcAIhwBSaYIAWdiADpKZTlPHz9-Y2UqFxoaPDxrRCF4AFt-AAd0B0FpAG0EFAxMf0kZF2AwQQgXBQAmYLgkNCwSqWkXTFRHaoUARmUAXWUgA) as

```js
class Keyword {
   key {_key}
   value {_value}
   construct new(key, value) {
      _key = key
      _value = value
   }
   toString {"{%(this.key),%(this.value)}"}
}


System.print([Keyword.new("cats", 2), Keyword.new("dogs", 1)])
```
> [{cats,2}, {dogs,1}]

So if some sugar is added maybe

```elixir
[cats: 2, dogs: 1]
```

becomes
```js
[Keyword.new("cats", 2), Keyword.new("dogs", 1)]
```

This can be handy in #1112

```
method([cats: cats, dogs: dogs]) {
   // cats and dogs
}
```

**Comment by mhermier** [comment]
There is already an equivalent of `Keyword` in code with `MapEntry` so if `identifier : value` needs to be transformed to something it has to be that to be coherent with map entries.
Even with that, I don't see what we gain from being able to create a `List` of `MapEntry`? Unless I'm mistaken, it would requires some kind of pattern matching at runtime when performing a call which would be an absolute NO for performance reasons.

**Comment by clsource** [comment]
> There is already an equivalent of Keyword in code with MapEntry

I think then it should be marked as unable to redefine, because is part of the core classes like String

>  it would requires some kind of pattern matching at runtime when performing a call 

Why so?. I think it would be the same as using a normal list of maps.

**Comment by aosenkidu** [comment]
Would it not make more sense to allow "unquoted single word strings" on the left side of key/value pairs? Just like Groovy does it?

**Comment by mhermier** [comment]
This is syntaxic sugar. And it would require LL(2) parser...
