### ISSUE TITLE
Does Wren has any forums?

### ISSUE THREAD

**Issue by shuiweng** [wren-lang/wren#1121]
I can't find a community for Wren that I could discuss problems and asking for help. If it doesn't have any forums yet, what about open Github discussion on this repo? Github discussion is a good forum. People will have a place to discuss things instead of having to post on the issues page. Please consider about this. Thank you.

**Comment by ruby0x1** [comment]
Hi! Many people are in the [discord server](https://wren.io/contributing.html), which is where a lot of discussion happens. 

I had been testing Discussions when they were in beta but forgot to revisit when it went live. I've enabled them now on the wren repo: https://github.com/wren-lang/wren/discussions

Thanks for the reminder!
