### ISSUE TITLE
Some issues appear to be missing

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#1135]
I don't know whether any one else has noticed this but the issue/PR numbering system for this repo seems to have gone awry.

I can't find issue numbers 1114 and 1118 to 1121 inclusive.

Not sure what if anything we can do about this, but it would be a pity if folks are posting stuff which then disappears into the ether :(

**Comment by PureFox48** [comment]
Went back a bit further and 1085 is missing too.

But you're right about the API as I subsequently found [this](https://stackoverflow.com/questions/66569047/github-what-causes-gaps-in-issue-number-404-this-is-not) on Stackoverflow.

They just show up as  '404 Not Found' so it looks like someone (@ruby0x1 perhaps) has deleted them because they were spam or otherwise off-topic.

**Comment by PureFox48** [comment]
Closing now as I don't think there's any more to be said.

**Comment by ruby0x1** [comment]
I doubt I would have deleted issues with actual discussion 🤔. I did move some issues over using transfer to the wren cli repo though, but iirc those would redirect? And those would have been related to the cli project, so I'm not sure now.

**Comment by PureFox48** [comment]
Bit of a mystery then but never mind. If they were important issues, the OPs would probably have reposted them.
