### ISSUE TITLE
Proposal: Private methods

### ISSUE THREAD

**Issue by munificent** [wren-lang/wren#117]
Trying to dump some stuff out of my brain and into the issue tracker so other people can see it.

Right now, Wren has no concept of private methods. Something like `_method(arg)` is actually a syntax error since it's field followed by a `(`.

We could loosen this to allow that syntax to represent a method call on `this` to a method whose name starts with an underscore. This would add a nice capability without adding too much complexity to the language and would fill in a hole in the grammar.

It's a bit tricky because we'd have to ensure a private method in one class doesn't collide with the same named method in the base class. Fields do this implicitly by how they're compiled. If we compile private methods to regular `CALL` instructions, that means the method name goes in the global table, so we'd have to swizzle their names somehow. We could generate different instructions for private methods, but that starts to add more complexity to the interpreter loop.

Another downside is that you could _only_ do this for methods with arguments. Private getters and setters already have built-in semantics for reading and writing to fields. There's no way to change that.

This is because we want to compile a use of a field to efficient bytecode and not preemptively go through a synthesized getter or setter call. The compiler may hit a `_foo = 2` expression in the middle of a class and it needs to know how to compile it even though it has never seen `_foo` before. The designed behavior today is that that _always_ just stores a value in a field and the compiler directly writes the bytecode to do that.

We can't have the compiler do "if `_foo` is a field then output the bytecode to store a field, otherwise call a getter `_foo`" because at compile time, it doesn't know what `_foo`. Even if we did require fields to be explicitly declared at the top of the class, we still don't know what _inherited_ fields are available.

**Comment by lluchs** [comment]
What about adding some nicer syntax for function calls instead? A field or local variable followed by parentheses could desugar to a `.call` method call:
```dart
var foo
foo(1, 2)
// would be equivalent to
foo.call(1, 2)
```
An empty pair of parentheses would probably be fine for a function call without arguments.

Private methods would then just be function objects stored in fields.

**Comment by munificent** [comment]
I would definitely love to have function-call-like syntax. Unfortunately, I believe it's ambiguous. Given:

```dart
foo.bar(arg)
```

Is it:

1. Calling the `bar` getter on `foo`, which returns a function, and invoking the function with `arg`.
2. Calling the `bar` method on `foo` with `arg` as an argument.

Wren leans heavily towards being method-oriented, which is why it can do things like support overloading by arity. I like this in general, but the sacrifice I had to make is that bare functions aren't quite as nice to work with. :-/

**Comment by lluchs** [comment]
Looking at your example, I think the only interpretation that "makes sense" (i.e. what you expect to happen) would be the second one, so I think not supporting the first one isn't actually an issue. Function object will usually only exist inside of local variables and parameters anyways.

**Comment by zeckalpha** [comment]
What about making parentheses an operator/method like indexing? The Function class could then have it alias `.call`. Would that be ambiguous? Perhaps, if a getter returns a function... Hmm.

**Comment by edsrzf** [comment]
I don't think there's any reasonable way to get rid of the `.call` on function calls without giving up the ability to omit parentheses from method calls with no arguments. If there were, Ruby probably would've done it already. (They might've even done it if there were an unreasonable way.)

Private methods fall firmly into the "nice to have, but not strictly necessary" category of features for me. It is appealing that an optimizing compiler could statically dispatch private methods and even inline calls. (I know that's not appropriate for this implementation, though.)

To implement private methods without adding much complication, the compiler could generate a unique symbol every time it runs into a new private method name in a class. Then keep a map from private method names to symbol names within the context of a class. Only the compiler would need to know about private methods, not the VM itself.

**Comment by munificent** [comment]
> I think not supporting the first one isn't actually an issue. Function object will usually only exist inside of local variables and parameters anyways.

I think that's true often, but not always. In my code in other languages, I pretty often store callbacks in fields. I think it would feel inconsistent if those worked differently than functions stored in locals.

Like @edsrzf says, my feeling is that if it could be done in a harmonious way, Ruby would have done it already.

**Comment by lluchs** [comment]
Ruby supports function calls with `[]` though, so maybe they just didn't have enough incentive to find a way ;)

**Comment by emeseles** [comment]
> Calling the bar getter on foo, which returns a function, and invoking the function with arg.
> Calling the bar method on foo with arg as an argument.

It'd be solvable if foo.bar was illegal. The scenario would then be foo.bar() to get whatever the getter was going to give, then foo.bar()() to call on it. As you say, Wren is about methods and there is no direct access to variables, so you could tighten the syntax, thus also simplifying it, by making foo.bar meaningless.

The only exception to this is '.' itself, which is an implied send of (), ie: the 'foo' in foo.bar() is really foo().bar() ...this is a slightly specious argument because I'm not at all sure how noisy Wren code would become if ()'s were required everywhere that getters are currently called.

**Comment by munificent** [comment]
> The scenario would then be foo.bar() to get whatever the getter was going to give, then foo.bar()() to call on it.

Ouch, that's pretty unpleasant on the eyes.

**Comment by soveran** [comment]
> We could loosen this to allow that syntax to represent a method call on this to a method whose name starts with an underscore. This would add a nice capability without adding too much complexity to the language and would fill in a hole in the grammar.

I like how it's done in `io.wren`, where you append an underscore to indicate the method is not part of the API without the need to enforce it.

**Comment by robotii** [comment]
The ambiguity between fields and private methods could be resolved by using another prefix for private methods, such as '@'.

I appreciate that this may not be a path that you want to go down though.

**Comment by munificent** [comment]
> The ambiguity between fields and private methods could be resolved by using another prefix for private methods, such as '@'.

I did consider that a long time ago. In fact, you can look at `_` today as equivalent to `@` in Ruby. Having two sigils does make this unambiguous, but then it would still raise question of if an argument list should be allowed after `@` too. :)

I'm personally not a fan of `@` because I think it's a bit too visually jarring for something I want to encourage users to do (have private state).

**Comment by ianmackenzie** [comment]
Another possibility would be to have methods private by default, and have to explicitly make them public using a 'fn' keyword in front of them. This would have the nice side effect that the same keyword might be able to be used to define global/standalone functions without having to go through the 'new Fn...' dance. For example:

```
class MyClass {
    privateMethod() {
        IO.print("Private")
    }
    fn publicMethod() {
        IO.print("Public")
    }
}

fn globalFunction() {
    IO.print("Global")
}

var alternateGlobalFunction = new Fn {
    IO.print("Alternate")
}
```

(I also think fun/Fun or function/Function might be better, but that's a separate discussion...)

This doesn't adress the issues of resolving name clashes between classes in the same hierarchy, but I think it's a reasonably clean syntax that makes it easy to define private functionality while gently forcing the user to think about what they want to explicitly expose to others.

**Comment by munificent** [comment]
> Another possibility would be to have methods private by default, and have to explicitly make them public using a 'fn' keyword in front of them.

That is possible, but Wren doesn't use keywords for visibility anywhere else, so it seems strange to me to use one here.

> used to define global/standalone functions without having to go through the 'new Fn...' dance. 

The `new Fn {}` dance isn't the real hard part with global functions, it's *invoking* them that's tedious. Wren is highly class-based, so bare functions are never going to feel very natural for reasons outlined [here](https://github.com/munificent/wren/issues/158#issuecomment-72594167).

It's kind of a drag (I do like bare functions in general), but I think it's a reasonable compromise to keep Wren's syntax simple and make working with objects more terse.

> This doesn't adress the issues of resolving name clashes between classes in the same hierarchy

Name-mangling would address this.

However, the original problem I was looking at was that syntax like `_foo(arg)` seems natural, but isn't allowed in Wren and doesn't mean anything. The question for me is, should we make that work? If we add a different unrelated syntax for private methods, that still leaves this syntax as a weird hole in the grammar.

**Comment by ppvk** [comment]
Private methods, regardless of syntax, would be awesome.

In my project `wren.js`, I have a low level wren api that evals JavaScript strings, and I have a high level class that wraps JavaScript objects. The high level code needs the low level stuff to work, but I don't want my users to be able to access the low level stuff. Making them private would solve my problem.

**Comment by munificent** [comment]
> Private methods, regardless of syntax, would be awesome.

Yeah, I think they're really useful too. I like the idea of using `_foo()` syntax, and I think it's reasonable to just say there are no private getters or setters to avoid the syntactic ambiguity with fields.

The main challenge I see right now is that the natural way to implement this (as just regular named methods that don't allow an explicit receiver) would make them *protected*, not *private*. You could access your superclass's private methods to.

To disallow that, we'd have to mangle the names somehow. That's doable, but it starts to feel a little hairy. So far, I've been doing private by convention by naming them with a *trailing* underscore, and it works OK.

**Comment by ppvk** [comment]
I've been using the same convention after seeing some of your work, and I agree that it works well. 

So I guess the question is whether we want private methods bad enough to complicate the VM with name mangling, or can we trust our users to follow a convention and not use methods we specify as private? Or maybe some middle ground where we just have protected methods that might be good enough for some use cases?

**Comment by munificent** [comment]
> Or maybe some middle ground where we just have protected methods that might be good enough for some use cases?

That's what I was leaning towards. Protected is pretty useful in its own right. Since the coupling between a class and its subclass is pretty deep anyway, the lack of private there might not be much of a loss.

However, *fields* are private. So making leading underscore methods protected feels really inconsistent.

**Comment by ppvk** [comment]
> However, fields are private. So making leading underscore methods protected feels really inconsistent.

Leading to perhaps a trailing underscore representing something protected?

Thinking about it more, I'd probably be fine without private methods, and really, _privacy_ is usually what I use protected methods for anyway.

**Comment by Noctisdark** [comment]
I think that we really need an abstract syntax tree, doing systax directed translation imposes some limitation (unpleasant experiences T_T). I think having this structure will allow the VM to know more about what's going and managing the symbol table more intellectuelly, private method will be trivial using this approach, the same is for prohibiting redefinition of functions, I don't know how will this affect performance or memory but I think It's worth trying.

**Comment by munificent** [comment]
> I think that we really need an abstract syntax tree, doing syntax directed translation imposes some limitations (unpleasant experiences T_T).

Yes, it is a hard constraint to work within, definitely. But my feeling is that a creative work stands out in large part by the constraints it chooses to follow. I decided really early on to make Wren a single-pass bytecode compiled language because it helps keep the VM small, simple, and efficient.

We definitely sacrifice things with that choice, especially around name resolution. But, ultimately, every project has to pick which things it's going to do and which things it isn't. If we take single-pass compilation as a given, can we still make a useful, productive language? I think so.
