### ISSUE TITLE
String pattern matching

### ISSUE THREAD

**Issue by edsrzf** [wren-lang/wren#120]
This is a tracking issue for some kind of string pattern matching, such as regular expressions or Lua patterns.

Regular expressions are probably out, since they'd either require a dependency or a complicated implementation.

Lua patterns are pretty nice because they're relatively easy to implement. They don't support Unicode, though. I don't think it would be _too_ difficult to bring Unicode support to Lua patterns, but something would have to be done about the built-in character classes, like "letters". They can't be extended to the full Unicode range without bringing in a bunch of Unicode data. One option would be to say that they're only valid for the ASCII range.

Are there any other string pattern matching options? Or anyone who thinks we don't need it?

**Comment by zeckalpha** [comment]
I've been working off an on on a readable and relatively efficient pure
Python implementation of regexes and FSAs, which could be ported to wren
without too much trouble. Not sure we need or want regex literals, though.
This might be a library thing.

**Comment by edsrzf** [comment]
Yes, to be clear I don't think this is a language change, but an addition of one or more string methods. I could also be convinced that it doesn't belong in core and would be better as a module.

**Comment by zeckalpha** [comment]
Here's roughly what I'm thinking: https://github.com/andrewclarkson/luther/pull/2/files

**Comment by munificent** [comment]
My thoughts:

1. Regexes are definitely useful. I find them ugly and hard to maintain but, alas, indispensable.
2. Doing something close-to-regex-but-not-really like Lua patterns may just cause more trouble than it's worth. While there's variation between languages, the core syntax is pretty stable and users expect it to just work.
3. The set of regex that people expect to just work, I think, is pretty large. I do worry it would add a lot of code to Wren, but maybe it won't be too bad.
4. Regex *literals* don't do much for me. I get the argument that it simplifies escaping, but I haven't found them useful enough to want to add dedicated syntax.
5. I have always wanted an excuse to implement [Russ Cox's paper on bytecode regex](http://swtch.com/~rsc/regexp/regexp2.html).

**Comment by zeckalpha** [comment]
That's the paper we were working from for Luther!

**Comment by lluchs** [comment]
>Regex literals don't do much for me. I get the argument that it simplifies escaping, but I haven't found them useful enough to want to add dedicated syntax.

Some kind of raw string literal which doesn't do any escape sequences could help here, and is also useful in other cases.

**Comment by munificent** [comment]
Yeah, I agree raw strings can be handy. I'll put them in the "let's try to live without them to keep things minimal bucket" but I can see wanting them at some point. Multiline strings are handy too and could be combined with those.

**Comment by soveran** [comment]
> I'll put them in the "let's try to live without them to keep things minimal bucket"

I'd like that to happen to regex too :-)

**Comment by zeckalpha** [comment]
https://github.com/zeckalpha/wren-io/blob/master/src/regex.c.wren

**Comment by munificent** [comment]
Neat!
