### ISSUE TITLE
Set syntax sugar for maps

### ISSUE THREAD

**Issue by munificent** [wren-lang/wren#137]
The typical way to emulate sets in a language with only maps is by making a map with dummy values. The keys become the set. We can add a little bit of syntax sugar to Wren to make that more natural. In a map literal, you can leave off the `: <value>` and it will implicitly be `true`. This lets you create a "set" like so:

``` dart
var set = {1, 2, 3}
```

By making the dummy value `true` (and since `null` is falsey), it lets you use the subscript operator as a membership test. You can do `containsKey()` too, of course, but this is a bit more terse:

``` dart
if (set[2]) ...
```

**Comment by zeckalpha** [comment]
Is there a syntax ambiguity here? Let's say a set containing one element that isn't a literal:

~~~ dart
var x = { a.b(c) }
~~~

Is this is a block or a set?

**Comment by munificent** [comment]
It's a set. Blocks can only appear in statement position and sets can only appear in expression position. (This is an example of where having a statement/expression distinction and not having implicit returns is helpful.)

If we didn't have this distinction, we'd have problems even without the set sugar. You'd run into issues with an empty map, `{}`.

**Comment by lluchs** [comment]
There's also the ES6-way of interpreting map literals (which obviously conflicts with this proposal):

```dart
var a, b, c
var map = {a, b, c}
// equivalent to
var map = {"a": a, "b": b, "c": c}
```

I feel like having a separate class for sets which would then implement common set operations like union and difference would be more useful. Typing `new Set(1, 2, 3)` doesn't seem to be too much work and feels a lot more clear (although this might need methods/constructors taking a variable number of arguments). Additionally, I think in a lot of cases, sets are built dynamically anyways (?).

**Comment by munificent** [comment]
Yeah, the ES6 sugar makes sense in their context where bare identifiers get treated as strings sometimes, but is definitely not how Wren rolls. Wren also doesn't allow `foo.bar` to mean the same as `foo["bar"]` or treat `{a: 1}` as equivalent to `{"a": 1}`.

We can certainly have a separate class for sets if we find it wants a lot more methods than feed natural to add to maps. But there is, I think, real value in having containers in the core module. They are passed very frequently between third-party modules (or, at least, will be when Wren has third-party modules :smile:). That imposes an interoperability tax on external modules.

If I want to pass a set from `my_module` to `your_module`, we have to agree on which third-party set class to use. Reaching that agreement is super hard which is why, I think, you see lots of competing JS libraries for data structures, none of which has wide adoption. Meanwhile, the collections in the Java standard library are all very widely used.

The art is balancing this with wanting to keep Wren minimal. :)

**Comment by ppvk** [comment]
I support this proposal. Sets are handy and this syntax makes them stand out from lists and maps.

**Comment by munificent** [comment]
:)

**Comment by Qard** [comment]
I think having "official" components as part of the standard distribution can be a good balance between unifying use of standard data types and not polluting the languages with things lots of people don't need. If you want to set type, add the set component to your build and you'll now have that type. :smile_cat:
