### ISSUE TITLE
Automated testing for all configurations

### ISSUE THREAD

**Issue by munificent** [wren-lang/wren#167]
Wren has an increasingly large number of supported configurations. Ignoring platform (which is its own little ball of complexity) we have every permutation of:
- Compile as C or C++.
- 32-bit or 64-bit.
- Debug or release.
- NaN tagging or not.
- This isn't really a configuration a user would use, but also whether or not GC stress testing is enabled, which helps flush out GC bugs.

Right now, `make test` just runs a released build compiled as 32-bit C with NaN tagging. This means bugs in other configurations can and do happen.

It would be swell if the test runner could handle being told what Wren executable to run. Then we could add a `testall` target to the Makefile that builds every configuration and tests all of them. Then we'd make Travis use that.

**Comment by zeckalpha** [comment]
I looked into doing both C and C++ builds with Travis and the documentation was opaque.
http://docs.travis-ci.com/user/languages/c/
http://docs.travis-ci.com/user/languages/cpp/
