### ISSUE TITLE
More robust module loading heuristics

### ISSUE THREAD

**Issue by gsmaverick** [wren-lang/wren#210]
The current module loading setup doesn't work very well when you try and pull in modules from other repositories and include them as you'd be accustomed to in other languages. As a quick example, say I have the following directory structure:

```
/wren-path
    /deps
        /wren-test (pulled in as a git submodule fwiw)
main.wren
```

When I try and include a file from `wren-path/deps/wren-test` in `main.wren` it doesn't load because Wren will only look for modules in the the outer `wren-path` directory. This makes it effectively impossible to reuse Wren modules elsewhere.

One possible solution is to allow module relative imports by having every `ObjModule` know from what file path it was loaded and then add its parent as a place to look in `loadModule` defined in `main.c`.

**Comment by munificent** [comment]
Yeah, the current behavior is super crude. It should definitely be a bit smarter with the usual caveat that the stock Wren interpreter isn't considered the main deliverable for Wren. It's just a little mini-app you can use to play with the language while it's "real" use is for embedding.

Even so, it seems like people *do* want to use Wren as a general purpose language too, so I'll probably need to start taking the interpreter more seriously too.

**Comment by gsmaverick** [comment]
I'll take a stab at making module loading a little bit smarter, hopefully in a way that can be completely contained within `main.c`.

**Comment by munificent** [comment]
> hopefully in a way that can be completely contained within main.c.

+1!
