### ISSUE TITLE
Make Range implement count

### ISSUE THREAD

**Issue by munificent** [wren-lang/wren#211]
Right now, it inherits `count` from Sequence, which is really slow—`O(n)`. It should be able to calculate and implement it directly in C.

**Comment by MarcoLizza** [comment]
I'l dig on this, if you agree...

**Comment by munificent** [comment]
Works for me!

**Comment by MarcoLizza** [comment]
:+1:

**Comment by MarcoLizza** [comment]
Done! Sorry for being late... :wink:

**Comment by munificent** [comment]
Ha, there's definitely no rush. I only have so much time to keep up with pull requests.
