### ISSUE TITLE
Improved VM performance for Windows/VC++

### ISSUE THREAD

**Issue by BarabasGitHub** [wren-lang/wren#269]
I read your article about Pratt Parsers and somehow stumbled upon Wren, which looks really nice! I briefly went through the implementation and saw the mention of computed gotos. I also read this article http://eli.thegreenplace.net/2012/07/12/computed-goto-for-efficient-dispatch-tables/ last week. And it got me thinking if it wasn't somehow possible to achieve the same on windows with VC++. 
After thinking about it on and off for a week I made some pseudo computed goto implementation for the Wren VM. Some quick tests showed 10-12% improvement on the benchmarks. It works by implementing the goto table as a switch case (in a macro), which contains the correct jumps back to the instructions.

However I had to include the 'wren_opcodes.h' in the switch case which is in a macro. And that's not possible. So my solution was to wrap the whole 'wren_opcodes.h' into a macro. It's not very pretty and I can understand if you're not happy about that. (I'm not =D) But I don't know of a better solution. I've never programmed in C before, only C++, so also macros are a bit new to me.

I'm not sure how the generated code compares to the actual computed goto implementation, since I haven't got Linux/GCC at hand here.

You can check out the code on my fork. Let me know if you're interested.

**Comment by lluchs** [comment]
I tested on Linux/Clang and it seems to work pretty well (baseline is computed goto):
```
binary_trees - wren            .......... 0.38s 0.2054  92.28% relative to baseline
delta_blue - wren              .......... 0.17s 0.0851  91.47% relative to baseline
fib - wren                     .......... 0.46s 0.2803  90.74% relative to baseline
for - wren                     .......... 0.15s 0.0962 104.88% relative to baseline
method_call - wren             .......... 0.23s 0.0055  94.14% relative to baseline
map_numeric - wren             .......... 0.60s 0.0018 101.43% relative to baseline
map_string - wren              .......... 0.14s 0.0011 107.44% relative to baseline
string_equals - wren           .......... 0.46s 0.0029 106.16% relative to baseline
```

As comparison, here's how the old fallback performed:
```
binary_trees - wren            .......... 0.42s 0.2361  82.88% relative to baseline
delta_blue - wren              .......... 0.19s 0.0943  79.13% relative to baseline
fib - wren                     .......... 0.54s 0.2093  76.87% relative to baseline
for - wren                     .......... 0.25s 0.0987  65.64% relative to baseline
method_call - wren             .......... 0.31s 0.0816  69.85% relative to baseline
map_numeric - wren             .......... 0.80s 0.0008  75.55% relative to baseline
map_string - wren              .......... 0.17s 0.0715  88.50% relative to baseline
string_equals - wren           .......... 0.62s 0.3502  78.90% relative to baseline
```

**Comment by munificent** [comment]
Wow, those numbers are pretty compelling. I'd love to merge this in.

@BarabasGitHub, I'll add a comment on the other bug you filed to try to help get your Git repo set up to send some pull requests. :)
