### ISSUE TITLE
Using Meta.eval inside an object

### ISSUE THREAD

**Issue by cacciatc** [wren-lang/wren#278]
I see that there is a Meta.eval method, but I am having trouble invoking it inside the context of an object. For example:

```
class Test {
  new(methodName) {
    _methodName = methodName
  }

  run() {
    Meta.eval(_methodName + "()")
  }
}
```

In other languages I might use "self" of "this" which is what I am assuming I need for Meta.eval to find the right context. Or perhaps there is a better way to do what I am attempting in wren?

**Comment by cacciatc** [comment]
After reviewing my example I noticed it is incomplete:

    class Test {
      new(methodName) {
        _methodName = methodName
      }

      belch() {
        IO.print("burp")
      }

      run() {
        Meta.eval(_methodName + "()")
      }
    }

    var t = new Test("belch")
    t.run()
    // -> hoping for "burp" to be printed to the screen

I also snooped around in wren_meta.c and it doesn't appear what I want to do is possible since the code is eval'd inside the calling function's module. I guess I am looking for a class_eval...

**Comment by munificent** [comment]
Yeah, eval-like support is very very limited in Wren right now, and might be generally difficult given some of its implementation choices. (For example, after a class is compiled, we no longer know the names of its fields.)
