### ISSUE TITLE
Fiber::try not working as expected

### ISSUE THREAD

**Issue by brandly** [wren-lang/wren#294]
[In the docs](https://munificent.github.io/wren/error-handling.html#handling-runtime-errors), it says

`[Y]ou can run a fiber using the try method. If a runtime error occurs in the called fiber, the error is captured and the try method returns the error message as a string.`

However, if I do something like

``` dart
var fiber = Fiber.new {
    return "Hello"
}

IO.print(fiber.try())
```

shouldn't I see `null`, since no error occurred? Currently, I see `"Hello"` instead.

I can check for `fiber.error`, which is great, but seeing that return value from the `try` seemed odd. Let me know if I'm out of line :smile:

**Comment by munificent** [comment]
Yeah, the way the error is reported is kind of hacky here since the return value is used for *both* the error and the normal return value. I can think of a few options:

1. Keep it as is and just document it better.
2. Just return `null` on an error and require the user to check `fiber.error`.
3. Pass a function to `try` that gets invoked if an error occurs. Like:

```dart
var fiber = Fiber.new {
    "string".doesNotHaveThisMethod()
}

fiber.try {|error|
  IO.print("caught ", error)
}
```

If we do that, it may make more sense to call it `catch` than `try`. What do you think?

**Comment by brandly** [comment]
I probably don't have much insight since I've only written Wren for like the past 48 hours, and I haven't done much with `Fiber`. I ran into this confusion while updating [Please](https://github.com/EvanHahn/wren-please).

That being said, I think it makes sense to only return an explicit return value. If the fiber aborts, just return a `null`.

I don't really understand the differences between `Fiber::try` and `Fiber::call`, as they currently exist. However, having something like

```dart
fiber.catch {|error|
  IO.print("caught ", error)
}
// null if fiber aborts
var returnValue = fiber.call()
```

makes sense to me. Are there any Wren programs making ample use of `Fiber`?

**Comment by minirop** [comment]
`Fiber.try` catch the error if there is one (same as `try/catch` in C++ or `try/except` in python), while `Fiber.call` just abort itself the let the error propagates to the calling fiber.

**Comment by munificent** [comment]
> Are there any Wren programs making ample use of Fiber?

I don't think there are many Wren programs *in general* yet, so probably no. I've written a few toy programs to play with fibers, but it's definitely unexplored territory.

**Comment by gsmaverick** [comment]
FWIW, I used fibers quite a bit for the [testing framework](https://github.com/gsmaverick/wren-test) I've been hacking on in Wren. I haven't found the current API to be too much of an issue; as long as the return type from a Fiber either through `try` or `call` is just a simple object we'll have this issue one way or another. There's no "state" for a Fiber as it is right now.

**Comment by munificent** [comment]
> I used fibers quite a bit for the testing framework I've been hacking on in Wren. I haven't found the current API to be too much of an issue

That's a good sign. Real-world user feedback is always the best signal.

> There's no "state" for a Fiber as it is right now.

It does have a bit, actually. You can call `.isDone` on a fiber to see if it has returned from its initial function yet. Also `.error` returns the runtime error if the fiber aborted. (This means the return value of `try` is redundant, but I put it there mostly for convenience.)

**Comment by Qard** [comment]
I like how Rust does this, with a Result<Type, Error> valued enum that can be pattern-matched to decompose to the appropriate value like this:

```
match thing_that_fails() {
  Error(error) {
    // Do something with error
  }
  Result(result) { result }
}
```

I think it'd make sense for `try()` to produce a similar Result type, which can be checked for an error or value. Could be a complicated pattern-matching feature, or it could be as simple as:

```
var result = fiber.try()
if (result.error) {
  // do error stuff
}
if (result.value) {
  // do value stuff
}
```

I feel like having `try()` maybe return a value or maybe return an error is just a bad idea and will likely only make it harder to support things like try/finally.

**Comment by munificent** [comment]
> I feel like having try() maybe return a value or maybe return an error is just a bad idea and will likely only make it harder to support things like try/finally.

Yeah, I think you're probably right. Having a result type feels like overkill to me in a dynamically typed language, but it's not a bad idea. Another one is to pass a block that gets invoked only when a runtime error occurs, like:

```
var result = fiber.catch {|error|
  System.print("%(error) occurred!")
}
```

This would let you tell when an error occurred or not without having to guess from the type of the result. What do you think?

**Comment by Qard** [comment]
That handles the catch half, but what about finally?

Also, what would the behaviour be after running the catch handler? Return null? You'd basically have to handle the error branch twice...

**Comment by munificent** [comment]
> Also, what would the behaviour be after running the catch handler? Return null?

I haven't put much thought into it, but I'm thinking `.catch(_)` would return the result of calling the fiber on success or the result of the error block on failure. But, yeah, without nonlocal returns, it would be a little tedious to propagate the error outwards from the block.
