### ISSUE TITLE
A way to express "finally" in Wren

### ISSUE THREAD

**Issue by munificent** [wren-lang/wren#323]
Fibers and the `try()` method give you a way to approximate exception handling. You can run some questionable code and use `try()` to stop a runtime error from propagating up the stack.

What you can't currently do is catch that runtime error, run some clean up code, and then "rethrow" that error to continue propagating _while preserving the original callstack_.

For example, here's some code from File:

```
var fiber = Fiber.new { fn.call(file) }

// Poor man's finally. Can we make this more elegant?
var result = fiber.try()
file.close()

// TODO: Want something like rethrow since now the callstack ends here. :(
if (fiber.error != null) Fiber.abort(fiber.error)
return result
```

One option might be to pass in the first failed fiber to `Fiber.abort()` and then make sure that handles that gracefully?

**Comment by Qard** [comment]
Rather than trying to resume an outer fiber in a possibly unsafe state, it might be better to use fiber finalizers. 

```
var fiber = Fiber.new { fn.call(file) }

// Regardless of success or error completion state,
// run the finalizer immediately before completion occurs.
var result = fiber.callThen { file.close() }
```

The block given to `callThen` would run immediately *before* the inner fiber actually produces an error, allowing the file to be safely closed before the stack unwinds and potentially creates a state where objects are no longer valid.

**Comment by munificent** [comment]
Executing code right before the runtime error will be difficult. At the point that we know a runtime error is going to occur, it's pretty much too late.

It would be pretty easy to implement what you have here, though, I think. It's just:

```
class Fiber {
  callThen(fn) {
    var result = try()
    fn.call()
    if (error != null) Fiber.abort(error) // <--
    return result
  }
```

This has the same problem, though, in that the callstack that gets dumped isn't helpful anymore because it starts at the marked line, and isn't the callstack for the original fiber that failed.

The bug description isn't really clear, but I think the issue here is more about having a useful callstack than it is being able to get the runtime behavior you want.

**Comment by Qard** [comment]
Could you not express the finally handler as another fiber that could be transferred to before propagating the error?

**Comment by munificent** [comment]
> Could you not express the finally handler as another fiber that could be transferred to before propagating the error?

Yes, that would work, I think, though we'll have to think about how to wire them up so that *that* fiber transfers control back to the right thing when it's done.
