### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [wren-lang/wren#335]
Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html) ⇒ [readFile](https://github.com/munificent/wren/blob/d431c2eaa86bb49a7bb5395abafb80d707ec9321/src/cli/vm.c#L25)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) ⇒ [main](https://github.com/munificent/wren/blob/71e2458a6c4adb477b0ab7db773a8e0116637367/src/cli/main.c#L8)

**Comment by munificent** [comment]
> * fseek ⇒ readFile

I wouldn't mind handling errors better here. There's still a good bit of work to do in the CLI around handling imports. The current support is pretty rudimentary. (See #325.) When that happens, this code may end up getting rewritten. But, until then, better error handling is always good.

> printf ⇒ main

Eh, if Wren can't successfully print the usage info, there's probably not much it could do to recover from that error either. Do you think error handling would be useful here?

**Comment by elfring** [comment]
* I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
* How do you think about to indicate a file output failure by a corresponding exit status for your program?

**Comment by munificent** [comment]
> How do you think about to indicate a file output failure by a corresponding exit status for your program?

Sure, that seems reasonable for code in the CLI.
