### ISSUE TITLE
Enable ability to add user-data to WrenVM object

### ISSUE THREAD

**Issue by ChrisAJS** [wren-lang/wren#350]
To allow context to be associated with a `WrenVM` handle, it would be useful to be able to add a user-data object. 

This would allow for domain specific objects to be retrieved during resolution and use of foreign methods, without forcing clients to introduce global state to their applications.

It doesn't appear to be possible to do this currently. 
### Sample Use Case

Wren script:

``` scala
class Gfx {
    foreign static drawLine(x, y, x2, y2)
}
// some time later...

Gfx.drawLine(10, 10, 40, 40)
```

C impl:

``` c
void gfx_drawLine(WrenVM *vm) {
   GfxHandle *gfx = (GfxHandle*)wrenGetUserData(vm);
   // get values
   gfx_drawLine(gfx, x, y, x2, y2);
}
```

Where gfx_drawLine has been returned from the function provided as `configuration.bindForeignMethodFn`.

**Comment by munificent** [comment]
Ah, interesting. Foreign classes—man, I really need to get around to writing docs for them—let you associate state with an individual Wren object. There's no way to associate it with the entire VM, but you could probably pretty simply accomplish that by defining a foreign class and storing a singleton instance in the global scope, like:

```scala
foreign class GfxState {
  construct new() {}
}

// This calls the foreign class's constructor where the host app captures the state.
var state = GfxState.new()

class Gfx {
  static drawLine(x, y, x2, y2) {
    // Forward to the foreign one, passing the captured state back.
    drawLine(state, x, y, x2, y2)
  }

  foreign static drawLine(state, x, y, x2, y2)
}
```

Then in C, you'd have something like:

```c
// Registered as the allocate function for GfxState using the config's bindForeignClassFn.
static void allocateGfxState(WrenVM* vm)
{
  GfxHandle *gfx = (GfxHandle*)wrenSetSlotNewForeign(vm, 0, 0, sizeof(GfxHandle));
  *gfx = ...
}

void gfx_drawLine(WrenVM *vm) {
   GfxHandle *gfx = (GfxHandle*)wrenGetSlotForeign(vm, 0);
   double x = wrenGetSlotDouble(vm, 1);
   double y = wrenGetSlotDouble(vm, 2);
   double x2 = wrenGetSlotDouble(vm, 3);
   double y2 = wrenGetSlotDouble(vm, 4);
   gfx_drawLine(gfx, x, y, x2, y2);
}
```

Given that, I don't think it's worth adding specific support for VM-scoped foreign data since it adds complexity and can already be expressed. How does that sound?

**Comment by boardwalk** [comment]
I was just looking for exactly this the other day --

The issue I have (and I'll use the example here to illustrate) is if you need some object to allocate GfxHandle in the first place (i.e. `*gfx = ` here requires some context from the surrounding program that constructed the interpreter), how do you get that into Wren? A sort of chicken & the egg problem.

What you could theoretically do is define a class in Wren, then instantiate it in C with wrenSlotNewPrivate, set your userdata inside it, then wrenCall something to squirrel that instance away.

```
class C {
  static instance=(i) { __i = i }
  static instance { __i }
  foreign doSomething()
}
```

```
wrenGetVariable(vm, "main", "C", 0);
void** userdata = (void**)wrenSetSlotNewForeign(vm, 1, 0, sizeof(void*));
*userdata = myuserdata;
WrenValue* method = wrenMakeCallHandle(vm, "instance=(_)");
wrenCall(vm, method);
```

```
C.instance.doSomething()
```

Which I suppose would work but isn't the most satisfying thing in the world.

Yesterday I added userData to WrenConfiguration and wrenGetUserData to my local copy in lieu of realizing you could do this (7 lines of code total). Unsure if I'll swap that out for this.

**Comment by munificent** [comment]
Yeah, that is a chore. Maybe we should do something better. Can you give me some more details about your use case? Do you have multiple Wren VMs floating around and therefore need to associate data with each one? Or are you trying to avoid creating a global variable in C to store the state it?

**Comment by ChrisAJS** [comment]
> Or are you trying to avoid creating a global variable in C to store the state it?
That's exactly what I'm trying to avoid doing. 

I'm actually using C++ and end up struggling trying to maintain access to an object instance in a _nice_ way. Having a coupling between a `WrenVM` instance and my vm wrapper class seems acceptable, however I'm currently having to store a global that all my foreign method binds have to access.

In my use case, I won't be having more than one `WrenVM` instance at a time, but it doesn't feel *right* having global state.

The alternative, albeit still undesirable, would be to store a pointer in the VM as a global... but I couldn't figure out how to do this, and my lack of desire to do this probably limited my investigations some what 😉 .

**Comment by minirop** [comment]
I guess, one way is to make your classes "foreign" and you "capture" the global variable in the constructor.

**Comment by boardwalk** [comment]
> Do you have multiple Wren VMs floating around and therefore need to associate data with each one? 

Not yet, but I'm considering the need for it, particularly to have a VM per thread or a VM per geographic area on the server side. I'm just working on the client right now.

> Or are you trying to avoid creating a global variable in C to store the state it?

Yes, that's exactly what I'm trying to avoid. I have global variables, but they're for communicating between subsystems, and I'd like to avoid using globals within a system (like here) in case I want to reuse that subsystem. Certainly I could use a thread local global and be sure to set it every time I call into Wren code, or capture the value of the global like @minirop suggested -- both of which use the global as a temporary which doesn't feel clean.

**Comment by paulsapps** [comment]
I'm unsure about the FFI stuff - I guess there are no docs/examples yet?

**Comment by munificent** [comment]
>  I guess there are no docs/examples yet?

There are tests, and doc comments in `wren.h`, but no good standalone documentation yet. Definitely on my TODO list!

**Comment by Banane9** [comment]
For my .net integration project's AutoMapper, I added a Map/Dictionary of the allocated foreign objects to the WrenVM wrapper and the public API of the wrapper only deals with setting an object to a slot and getting it from a slot.

I do this by storing an id in the wren foreign object and retrieving that to get the associated object from the map/dictionary.
