### ISSUE TITLE
Support opening files for append

### ISSUE THREAD

**Issue by cacciatc** [wren-lang/wren#383]
I am curious why does File.open only support reading files inside the supplied function? Is this a design decision or hasn't been implemented?

**Comment by cacciatc** [comment]
Ahh, hand't noticed the symmetry with File.create...., but there is still no way to append to an existing file without copying it all over correct?

**Comment by munificent** [comment]
>  there is still no way to append to an existing file without copying it all over correct?

Not, yet, no. The file API is still a baby and has a lot of growing to do. :)

**Comment by xordspar0** [comment]
Just checking in on this: from a quick look at the code it doesn't look like this has been implemented yet.

Anyone interested will probably want to look at https://github.com/wren-lang/wren/blob/master/src/module/io.wren and https://github.com/wren-lang/wren/blob/master/src/module/io.c. The commit https://github.com/wren-lang/wren/commit/8e90e3577b0f2924b4c5220a8a222254b9040b42 may also be a helpful guide.
