### ISSUE TITLE
Ability to export and import objects to/from binary blobs and JSON

### ISSUE THREAD

**Issue by bytemaster** [wren-lang/wren#395]
Moving data between applications and/or languages is much easier when objects can be serialized in a platform independent manner. 

It would be even more amazing if the serialization format worked like captain proto so that objects do not need to be parsed when loaded.

**Comment by minirop** [comment]
I gave a little thought about a binary format (like java's class, python's pyc). Is it what you have in mind or something more specific (like C++ modules)?

**Comment by CodogoFreddie** [comment]
Possibly include [this module](https://github.com/brandly/wren-json) into wren's default modules?

It's quite a small library, and I'd consider JSON parsing a pretty vital feature for any language

Otherwise I'd be happy to try to write a native c parser?
