### ISSUE TITLE
Namespace Classes with Cleaner Syntax

### ISSUE THREAD

**Issue by bytemaster** [wren-lang/wren#416]
I have been attempting to utilize the module system for importing classes, but run into a problem if I have two modules that define the same class and want to import them into the same code.  

In other languages I would do something like this:
```
namespace X {
   class Y {
      construct new() {}
   }
}
namespace Z {
   class Y {
      construct new() {}
   }
}

X.Y.new()
Z.Y.new()
```

In Wren the closest I have come to achieving this is:

```
class Scope {
   static Nest {
      class Nest {
         construct new() {}
      }
      return Nest
   }
}
class Scope2 {
   static Nest {
      class Nest {
         construct new() {}
      }
      return Nest
   }
}

Scope.Nest.new()
Scope2.Nest.new()
```

It would be nice if this "pattern" could be simplified as 
```
class Scope {
      class Nest {
         construct new() {}
      }
}
class Scope2 {
      class Nest {
         construct new() {}
      }
}
```

**Comment by bytemaster** [comment]
The problem with the nested approach is that it creates and defines a new class every time and that new class has its own static variables.

I had to extend the code even more to get the true desired behavior:

```
class Scope {
   static Nest {
      class Nest {
         construct new() {
            System.print( "Scope.Nest" )
         }
         static inc() {
            if( !__var ) __var = 0
            __var = __var + 1
            System.print(__var)
         }
      }
      return Nest
   }
}
class Scope2 {
   static Nest {
      if( !__nest ) {
         class Nest {
            construct new() {
               System.print( "Scope2.Nest" )
            }
            static inc() {
               if( !__var ) __var = 0
               __var = __var + 1
               System.print(__var)
            }
         }
         __nest = Nest
      }
      return __nest
   }
}


Scope.Nest.new()
Scope.Nest.inc()
Scope.Nest.inc()
Scope2.Nest.new()
Scope2.Nest.inc()
Scope2.Nest.inc()

```

Outputs:
```
Scope.Nest
1
1
Scope2.Nest
1
2
```

**Comment by bytemaster** [comment]
To avoid the extra if() check in every call to Scope2.Nest() it is possible to define a separate Scope.init() method that defines all the static classes and then Scope2.Nest can simply return the result.

```
class Scope {
   static init() {
      if( !__Nest ) {
         class Nest {
         }
         __Nest = Nest
      }
   }
   static Nest { __Nest }
}

**Comment by bytemaster** [comment]
One additional side effect of these approaches is that a class has no concept of its own "scope" so we get the situation that:

Scope2.Nest.toString == Scope.Nest.toString  ==> true
Scope2.Nest == Scope.Nest ==> false

This is a minor issue if you rely on the built in toString, but it this can be worked around with the following:

```
class Scope {
   static init() {
      if( !__Nest ) {
         class Nest {
             static toString { "Scope.Nest" }
         }
         __Nest = Nest
      }
   }
   static Nest { __Nest }
}

Scope.init()
Scope.Nest.toString == "Scope.Nest"
```

My conclusion is that it is possible to mimmic the desired behavior by making the code more verbose, but that this likely has performance, readability, and maintainability impacts.

**Comment by bytemaster** [comment]
One last problem with this approach is that inheritance is completely broken:

```
class SubNest is Scope.Nest {

}
```

The above code fails to compile because Scope.Nest is not a class name, but a method call that returns a Class object.

**Comment by SuperWangKai** [comment]
Namespace seems neccessary. **Why not?**

**Comment by crabmusket** [comment]
> I have been attempting to utilize the module system for importing classes, but run into a problem if I have two modules that define the same class and want to import them into the same code.

This seems like a slightly separate issue to namespaces, but just as important (at least, to me). Without being able to import variables under a different name than the one they're defined as, you essentially have a single global namespace for all names that need to be shared between modules.

If we could do this, for example, that would be avoided:

```
import "beverages" for Java
import "languages" for Java as JavaLanguage

Java.drink()
JavaLanguage.code()
```
