### ISSUE TITLE
Any plan to integrate a HTTP module

### ISSUE THREAD

**Issue by hwclass** [wren-lang/wren#417]

**Comment by aggsol** [comment]
That might be a bit specific. Most people won't need it and implementing in portable or platform independent is a difficult task in itself.

**Comment by egordorichev** [comment]
Maybe this should go as a stand-alone library.

**Comment by munificent** [comment]
Yes, I would like to have this as part of the Wren CLI on top of libuv, but not part of the core VM itself.
