### ISSUE TITLE
Document how to call a function (not method) from C

### ISSUE THREAD

**Issue by ChrisAJS** [wren-lang/wren#444]
[Looking at the call.c test](https://github.com/munificent/wren/blob/e7cabbb5e436b07f7c77b9ef83e3bd0408836672/test/api/call.c) I am struggling to understand how I would execute a `Fn` instance created from my script, from my C application.

I am doing something similar to the following:

```
ForeignClass.addCommand("invokeTest", Fn.new {
    ForeignClass.print("Invoked in script!")
})
```

In my foreign method bind function:

```c++
if(signature == "addCommand(_,_)") {
    return [](WrenVM *wrenVm) {
        std::string commandName = std::string(wrenGetSlotString(wrenVm, 1));
        WrenHandle *method = wrenGetSlotHandle(wrenVm, 2);
        std::cout << "Binding method " << commandName << std::endl;

        commands[commandName] = [&](std::vector<std::string> args) {
            std::cout << "HIT HIT HIT HIT" << std::endl;
            wrenCall(wrenVm, method);
        };
    };
}
```

When I later invoke `commands["invokeTest"]({});` I see `HIT HIT HIT HIT` but then the application segfaults.

I can only see a way to invoke methods in a class or methods that have a name. Is what I'm trying to achieve possible? 

**I would love to see the API documentation updated with examples! <3**

**Comment by minirop** [comment]
Your error comes that you don't get an handle to the method to invode in slot 2 but the function object.

```
if(signature == "addCommand(_,_)") {
    return [](WrenVM *wrenVm) {
        std::string commandName = std::string(wrenGetSlotString(wrenVm, 1));
       WrenHandle * fnObject = wrenGetSlotHandle(wrenVm, 2); // you get the object
        std::cout << "Binding method " << commandName << std::endl;

        commands[commandName] = [&](std::vector<std::string> args) {
            std::cout << "HIT HIT HIT HIT" << std::endl;
            WrenHandle * methodHandle = wrenMakeCallHandle(vm, "call()"); // get handle to the method "call"
            wrenEnsureSlots(wrenVm, 1);
            wrenSetSlotHandle(wrenVm, 0, fnObject); // the receiver of the method to be the function object you get as an argument
            wrenCall(wrenVm, methodHandle); // call the "call" method.
        };
    };
}
```

And you can simplify the `addCommand` call:
```
ForeignClass.addCommand("invokeTest") {
    ForeignClass.print("Invoked in script!")
}
```
does exactly the same thing. It's disturbing at first, but it removes some uglyness (IMO).

**Comment by ElFeesho** [comment]
@minirop, @munificent, thanks for the help! Got it working correctly thanks to your explanations.
