### ISSUE TITLE
System Call [Proposal & PR]

### ISSUE THREAD

**Issue by FreddieRidell** [wren-lang/wren#448]
Add support for creating new processes with shell commands.

I propose to add this as a `call` method to the `Process` object in `os` with the following signature:

+ `call(command)`: run the command, and return the exit code
+ `call(command, async)`: run the command, and return the `stdout` of the command
  + if `async` is false, blocks until the command is done and returns its output as one string
  + if `async` is true, does some cool fibrous stuff, I'd like to discuss exactly what, as I'm not sure what the best course of action is.

My initial thought for the async method would be to mirror the API for `Stdin.readline`, though I'd like a little guidance on how best to achieve this.

I've already got a PR of the first method ready to go, tested on linux, I'm afraid I have no access to a windows PC.

**Comment by CodogoFreddie** [comment]
On reflection, it seems that it would make most sense to superclass `Stdin` from `io` into a `Stream` class, that is inherited by `Stdin`, `Subprocess.Stdin`, and possibly `File`.  I'm really happy to re-write my code and try to do this properly over the next few months, but would really appreciate some outside input before I start coding :)
