### ISSUE TITLE
forward references only work for module variables that start with a capital letter

### ISSUE THREAD

**Issue by skybrian** [wren-lang/wren#467]
This works:

```
var run = Fn.new {
    System.print(A)
}

var A = 123

run.call()
```

This does not:

```
var run = Fn.new {
    System.print(a)
}

var a = 123

run.call()
```

The error is:

```
[main line 2] Error at 'a': Undefined variable.
```

(Not a big deal, but thought I'd mention it.)

**Comment by lluchs** [comment]
This is by design: https://github.com/munificent/wren/issues/106

**Comment by skybrian** [comment]
Hmm, perhaps this is a documentation bug then?In the docs, there is [method scope rule](http://wren.io/classes.html#method-scope) for identifiers with capital letters. But in my example, there is no method scope involved; this reference is in a block argument to a top-level method call.

**Comment by minirop** [comment]
It is a function scope. The block argument that you pass to Fn.new IS a function. If it was a "normal" scope, you would have "Undefined variable" even with A.

A block argument is the only time (AFAIK) where you can have a function (and not a method) because it gets wrapped in a Fn object just after.

**Comment by skybrian** [comment]
Yes that's true, but it's documented as method scope, so it seems like the docs should talk about function scope instead (or as well).

Also, this isn't a big deal, but arguably the capital letter rule makes less sense in function scope. The point of it is to avoid conflicting with getters (etc) on the same object, but that's not an issue for code that's not within a method.

**Comment by munificent** [comment]
Ah, this is an interesting case. Wren allows forward references to top level variables, but only capitalized ones. The function block is a distraction for the core issue. This program also has the same error:

```wren
if (false) {
  System.print(a)
}

var a = 123
```

The code that reports the "undefined variable" error is [here](https://github.com/munificent/wren/blob/master/src/vm/wren_compiler.c#L2237-L2241). As you can see, it literally does restrict it to lowercase variable names. Comment out that block and forward references to lowercase variables work.

I agree the docs are not at all clear on this. I'm not entirely certain this is the *behavior* we want. This touches on an area of Wren where the users's intuition kind of breaks down. In some ways, Wren looks and acts like a statically-typed OOP language like Java:

* Names inside methods are implicitly called on `this` if they don't refer to locals.
* Class declarations are mutually recursive. A method in one class can refer to a class declared later in the file.

But in other ways, it acts like a dynamically-typed scripting language:

* The top level of a program is a series of imperative statements executed from top to bottom.
* *Lowercase* variables declared at the top level behave like typical block-scoped variables and don't exist until after their declaration.

I think the fact that Wren is pretty intuitive in both of these styles is one of its major features, but the intuition breaks down in the corners sometimes. This is one of them. I've toyed with a *lot* of different changes to how the top level of a script works to try to settle on something that feels better, but nothing has worked out yet.

Sometimes, I wonder if the top level should be pure, simultaneous declarations as in Java or Dart, but then it requires creating a `main()`, which feels like a hassle...

At the very least, the docs around this should be clearer. I'm still working my way through the embedding API docs (finally!), but I'll try to improve these too.

**Comment by skybrian** [comment]
Yeah, this is tricky. But regardless of the semantics you decide on, it it seems like the error message could be improved? Currently it's:

```
[main line 2] Error at 'a': Undefined variable.
```

How about:

```
[main line 2] Variable 'a' is referenced before its definition (at line 5).
```

**Comment by skybrian** [comment]
@bjorn Looking at wrenDeclareVariable(), it assumes the variable exists (giving it a number) and sets its value to the line where it's first used. If the definition isn't found later then it prints an error.

It seems like for lowercase variables it could do the same thing, except that when the definition is found, it could report an error if a forward reference isn't allowed.

**Comment by bjorn** [comment]
@skybrian Makes sense. Also to look at the code before making assumptions. :-)

**Comment by underscorediscovery** [comment]
@bjorn @munificent @skybrian take a look at #699 which implements a better error message.
Feedback welcome, but I think it's better short term, even if we decide to allow forward references for some reason.

**Comment by skybrian** [comment]
It seems quite reasonable. Maybe add a test?

**Comment by underscorediscovery** [comment]
Oh yea, I had one to push along with this PR later.
