### ISSUE TITLE
Do not support XP/2003?

### ISSUE THREAD

**Issue by shawnye** [wren-lang/wren#489]
I build wren and libuv both with 'msbuild_toolset': 'v140_xp',  /MT , VS2015,
both successfully.

And then I put `wren.exe` on window 2003 server, and run the scirpt:
<pre>
import "io" for File

var rp = File.realPath(".")
System.print(rp) 
</pre>

the output:
<pre>
function not implemented
[scheduler line 18] in runNextScheduled_()
[io line 99] in realPath(_)
[main line 3] in (script)
</pre>

wren.exe self is OK, just can not use function in libuv.

Any suggestion, thank you!

**Comment by shawnye** [comment]
[scheduler line 18] in runNextScheduled_()
`Fiber.suspend()` not not implemented on XP ?

<pre>
  static runNextScheduled_() {
    if (__scheduled == null || __scheduled.isEmpty) {
      return Fiber.suspend()                                         //line 18
    } else {
      return __scheduled.removeAt(0).transfer()
    }
  }
</pre>

**Comment by KyleCharters** [comment]
This appears to be an issue with libuv, see the note under uv_sf_realpath:
http://docs.libuv.org/en/v1.x/fs.html#c.uv_fs_realpath

I don't believe there is an easy alternative, maybe we should just put a warning in the docs? Or better yet, a more friendly error message when trying to use the function on an unsupported system.

**Comment by munificent** [comment]
Oof, yes. Wren should be detecting this error from libuv and reporting it more gracefully.
