### ISSUE TITLE
Find the module associated with a class?

### ISSUE THREAD

**Issue by samw3** [wren-lang/wren#492]
Is there a way to know the module associated with a class?  this.type.name only returns the short name of the class.

**Comment by minirop** [comment]
No. Do you have any use-case?
Unlike languages like Python where a module is a file/directory with a specific name, in wren it can be any string (even non-printable characters). It's the embedder that dictate which name load each file.
So you can't really do anyting with that (except logging).

**Comment by samw3** [comment]
My use case is serialization. I have a game engine that uses wren. I modularize the game by Scene, i.e. Town1Inn, Town2Shop. The engine needs to keep track of the currently active Scene object in order to save it in a game save file.

I reload the save by building a string in C that does the import and hands it to my SceneManager. 

I have been using obj.type.name with everything in one huge “game” module which use for the import but things are getting unruly now. 

I understand that the module string can be arbitrarily anything, but I still need it to call the import again. 

Does that make sense?

**Comment by mhermier** [comment]
It make sense in the principle of data is code and code is data, unfortunately for now it is not possible to do so in the engine current state.
You have 2 options here I think:
1. Either manually define `static moduleName` in each of the class you want to serialize.
2. Hack the code so that classes knows the module they belongs to, and expose modules to the language.

The second option is a little harder, but should make it more effective in the long run, if you go that way.

**Comment by munificent** [comment]
Yeah, like @mhermier says, there is no way to do this now. Classes don't store a reference to the module name where they are defined. We could do that, but I'm not sure how generally useful that is, and I always hesitate to spend memory on state that may not be widely useful.

Another option would be to add a built-in variable like `__WREN_MODULE__` or something that evaluates to the name of the current module whenever you use it. Then when you define your class(es), you'd access that at some appropriate time and store the result somewhere in the class.

Would that work?

**Comment by mhermier** [comment]
What about a `thisModule` ? I think there is a precedent in a language I
forgot, and using `this` as a prefix should be pretty always safe.

**Comment by samw3** [comment]
@munificent I'm not sure what you mean by "current module" and how this differs from being stored as state.  Would it still be accessible whenever a function in that module is called?
