### ISSUE TITLE
Allocating foreign objects yourself

### ISSUE THREAD

**Issue by jclc** [wren-lang/wren#499]
wrenSetSlotNewForeign does the allocation for you, but I would like to do the allocation myself. My use case is that certain foreign objects go into an object pool where the data is all in-place. Is this possible?

**Comment by minirop** [comment]
When you create a VM, you con configure the allocator via the WrenConfigure struct, the field `reallocateFn`.

**Comment by jclc** [comment]
But I don't want everything to be in one object pool. Doesn't Wren use the allocator function for all memory allocation? Furthermore, I have no way of finding where or for what purpose the allocator is being called.

**Comment by munificent** [comment]
Interesting use case! How would you expect to handle deallocation of these objects when Wren's GC decides one is no longer needed? Call your finalizer and let it take care of it?

**Comment by jclc** [comment]
It's been a while since I encountered this problem so I'm not sure if I remember correctly; but I believe my idea was to be able to give foreign classes specialised allocate/deallocate functions that would otherwise work transparently just like the default allocator/deallocator.

**Comment by underscorediscovery** [comment]
See [this discussion](https://github.com/wren-lang/wren/issues/684#issuecomment-532972236) in #684 for some ideas on allocating independently of the GC. For now I'm closing this and tagging that issue with `future` to keep the ideas in mind.
