### ISSUE TITLE
System.clock should not use clock(3)

### ISSUE THREAD

**Issue by jube** [wren-lang/wren#508]
The documentation for `System.clock` says "Returns the number of seconds (including fractional seconds) since the program was started." But `clock(3)` returns que CPU time, not the wall time. In C99, there is no solution (except make non portable code). In C11, there is [`timespec_get`](http://en.cppreference.com/w/c/chrono/timespec_get) that could be used to get the right time.

**Comment by munificent** [comment]
Hmm, that function is mainly useful for benchmarking where CPU time is usually what you want. A function for getting elapsed wall time might be good too, though at that point, it might be better to just give seconds since epoch.

At the very least, the docs for this should be better.

**Comment by wasamasa** [comment]
I've checked what other interpreters commonly use and found that they go for POSIX `gettimeofday`, some adding `QueryPerformanceCounter` for Windows support.
