### ISSUE TITLE
Support libuv compilation on macOS systems without Xcode

### ISSUE THREAD

**Issue by netmute** [wren-lang/wren#514]
I don't have Xcode installed, but I have the Xcode command line developer tools. I changed the build step in `util/build_libuv.py` to the following

```
def build_libuv_mac():
  args = [python2_binary(), "gyp_uv.py", "-f", "make", "-Dtarget_arch=x86_64"]
  run(args, cwd=LIB_UV_DIR)
  run(["make", "-C", "out", "BUILDTYPE=Release", "libuv"], cwd=LIB_UV_DIR)
```

That seems to work just fine.

I didn't create a PR for this, because I don't want to break the setup for others. I'm sure there is a reason why this is done in Xcode by default.

Just wanted to put this on the radar.

**Comment by munificent** [comment]
I don't have an *explicit* reason for preferring XCode. That just seemed to be what the libuv docs lean towards. If we can build on Mac without it, that works for me too.

I'm super busy these days (though I have been trying to make some progress on Wren lately), but I'll try to take a look at this at some point.
