### ISSUE TITLE
Exposing field symbols at runtime

### ISSUE THREAD

**Issue by sponge** [wren-lang/wren#532]
I've been trying to modify the compiler to retain field symbol information after compilation is over, to view objects at runtime. I've got it working, and can dump a pretty complete representation of an object into Dear ImGui pretty well (https://i.imgur.com/UBX0dWw.png) but I'm wondering if there is a better way to implement the compiler change, one that could perhaps be included for real as a VM option.

My solution was to just save off the ClassInfo struct, which contained SymbolTable fields to the VM (although going back now I don't think saving anything else in ClassInfo besides the SymbolTable benefits me), instead of deleting them:

https://github.com/sponge/sdlgame/commit/942cb76d0fcf2a31a910753d05e0e2e2062684d1#diff-1016adda07353687f6ee5c19a7422af2
https://github.com/sponge/sdlgame/commit/942cb76d0fcf2a31a910753d05e0e2e2062684d1#diff-b4c23f2d20c9145e356f8c99b855a9c3

There are two drawbacks that I had with this approach, "just get it working" hackiness aside:

- When I have an ObjClass, I have to loop through my array on the VM object to find the symbols. It would probably be best if I could attach the symbols to the class, but I'm not sure if there's any place to do this at compile time. I see wrenNewClass, but that would be every time a class is instantiated. Maybe not a big deal if you opt into saving symbol info at VM creation and knew you were taking the memory/speed hit.

- When iterating through fields on an instance, I have to hop through superclasses in order to find which superclass this field actually came from. This was somewhat tricky with multiple superclasses. Maybe instead of saving off the SymbolTable I should save off a new one that includes superclass field symbols too, but I'm not sure if that's possible at compile time.

Would be interested in any feedback, especially if this could be useful to anyone else!

If anyone else is interested, my ImGui code is available at https://github.com/sponge/sdlgame/blob/master/game/wreninspector.cpp and shouldn't have any external dependencies beyond that compiler modification.

**Comment by underscorediscovery** [comment]
The debugger stuff we are trying to wrap up dealt with this, there's some that can be snuck into the FnDebug struct, some was stored elsewhere, I'll have to check but just wanted to note that we also had to grapple with that for the working runtime debugger.

**Comment by munificent** [comment]
Yeah, I didn't mention that, but I know you're way ahead of me on the debugger front. :)

**Comment by sponge** [comment]
Yea, I figured with luxe on the horizon (can't wait to check it out!) I wasn't even going to attempt to tackle debugger commands. :) I think there's value for my personal workflow with having an on-screen object dumper in addition to a debugger. If the luxe debugger stuff makes it back to wren trunk, I'd definitely move my imgui stuff over to those structures instead. It would then be just a matter of dropping my inspector file into a project already using imgui, and setting up the foreign function for anyone else to be able to use it.

I feel like a runtime option would be better than compile flags if the resource use when disabled can be minimized. There's cases like luxe, or my personal toy engine, where you'd want the user to be able to opt in/out of the debugging perf hit, but the VM host would always be built in a release configuration. It'd be weird to ship a separate binary with debugging support, at least coming from the world of stuff like Love2D and fantasy consoles.

**Comment by underscorediscovery** [comment]
Worth noting the debugger stuff we've done is 100% wren and 0% luxe (it's just implemented in luxe because it's easier for us and we have a body of work to test in/on). It's definitely aimed at wren master.
