### ISSUE TITLE
Self-assignment operators

### ISSUE THREAD

**Issue by nickwanninger** [wren-lang/wren#539]
From what I can tell, wren is missing any kind of compound assignments like
```js
var a = 3
a += 3 // a is now 6
```

I'm still poking around in the source, trying to get my head around it, but I feel that something like this could possibly be strapped on top and transformed at compile time into this:
```js
var a = 3
a = a + 3 // a is now 6
```

But again, I'm not sure. I'm also not sure how this could be implemented with the ability to overload operators on class fields. Thoughts?

**Comment by lasagnaphil** [comment]
[Link](https://stackoverflow.com/questions/20091779/lua-operators-why-isnt-and-so-on-defined)
In the link above, munificent gave out some good reasons why compound assignments aren’t implemented in lua (which can also be equally applied to wren). To summarize, the additional syntax is hard to implement in a single-pass compiler, along with some ambiguity issues in grammar.

**Comment by munificent** [comment]
Yeah, self-assignment is tricky in a single-pass compiler. It might be a little easier in Wren because we don't have multiple assignment. My hunch is that this will end up not happening, but it could be nice. I'll leave it open and maybe at some point try to do some investigation.
