### ISSUE TITLE
Notify iterable if iterator ends abruptly (to do possible cleanup)

### ISSUE THREAD

**Issue by pedromsilvapt** [wren-lang/wren#548]
I'd like to propose a small enhancement to the Iterator Protocol for your consideration.

When iterating with a `for` loop, there is no way for the Iterable to know if one of it's Iterators was "broken". For example, the following code:

```
for ( line in lineReader.open( 'some-file.txt' ) ) {
    if ( line == "end-header" ) {
        break
    }

    // Do some code with the lines before "end-header"
}
```

Line reader has no way of knowing that the Iterator is no longer in use, and thus cannot free any resources it may have.

Sure, if the Iterator object (not the Iterable) was a foreign class, it could be notified when Wren (later) garbage collected it, but that would require that all Iterators that needed this functionality be implemented as foreign objects.

A more elegant solution, in my opinion, would be to have an optional `iteratorEnd ( iterator )` method that would be called when any `break` or `return` statements are executed inside the cycle. Such wouldn't be too hard to implement, since it's only syntactic sugar and no internal components of the VM would need to change, I think.

The example provided int Wren's website
```
for (i in 1..100) { 
  System.print(i) 
  if (i > 50) {
    break
  }
}
```

Would then become
```
var iter_ = null 
var seq_ = 1..100 
while (iter_ = seq_.iterate(iter_)) { 
  var i = seq_.iteratorValue(iter_) 
  System.print(i) 
  if (i > 50) {
    seq_.iteratorEnd(iter__)
    break
  }
}
```

**Comment by mhermier** [comment]
I think that 'iteratorEnd' is confusing, since it might be confused with a function returning an iterator returning the end of the 'Iterable'. I think 'iteratorFini' would be a more suitable name.

**Comment by pedromsilvapt** [comment]
Yes, I had not given much thought to the name, iteratorEnd was just an example. Other options would be `iteratorBreak`, or possibly `iteratorReturn`, resembling the optional `return` method is JS iterators as well.

**Comment by bjorn** [comment]
I think regardless of the name this is a bad idea, because there is no guarantee that the iterator will no longer be used after this "iteratorBreak" method is called. It could have been stored in a variable, and its methods could be called manually rather than as part of a for-loop.

If `lineReader.open` allocates any resources that should be freed up after the iterator is no longer in use, then the way to implement this is to reference those resources (only) in the iterator object, such that they can be cleaned up when that object is garbage collected.

Maybe you need to have a way to hook into the garbage collection from Wren code instead of C code? I think that's pretty rare, but I guess it could be useful with some APIs. Lua provides this through the [`__gc` metamethod](https://www.lua.org/manual/5.3/manual.html#2.5.1), but I think it is not possible in Wren currently.

**Comment by pedromsilvapt** [comment]
I think it is fair to say that if you were to use an iterator outside of a
`for loop`, it would be your responsibility to call the method closing the
iterator, just like it is a programmer's responsibility to close files,
sockets, etc...

When using a `for loop` however, this would be completely transparent for
the end user. And there is no way for the use to manually get hold of the
variable used internally to iterate, so it wouldn't leak.

A qui, 24/05/2018, 09:33, Thorbjørn Lindeijer <notifications@github.com>
escreveu:

**Comment by mhermier** [comment]
In fact there is a issue in the roles implied in the logic there. What is meant here is that the iterator state could be somehow stored in the container. Therefore the iterator has to tell the container that it is done. Which defeats the role of the container.

If the container has more data that what could be represented in memory, we have to come back to the traditional way to do iterator, with an Iterator class like:
```
class Container {
  iterate(iter) {
     ... // Initialisation here
     return iter.next
  }
  iteratorValue(iter) { iter.value }

  next(key) { ... }
  value(key) { ... }
}

class Iterator {
  construct new(container, key) {
    _container = container
    _key = key
  }
  next { Iterator.new(_container, _container.next(_key)) }
  value { _container.value(_key) }
}
```
That way the Container become a data factory. I deliberately made the code simple here, but it can easily made to cache the next iterator and value, controlling both their life time. So it means when the iterator dies, the resource (which can be a foreign) dies.

The only drawback I see is that it make quite a boiler plate to implements, but if  native data is implied, I think the loss implied here are negligible.
