### ISSUE TITLE
Remove special bultins modules from library.

### ISSUE THREAD

**Issue by mhermier** [wren-lang/wren#551]
Rationale: libwren embeds `meta` and `random` modules which should not be part of the vm.
They are optional, meaning we can produce inconsistent/various libwren with different support under the same name.
While they can touch (technically only `meta`) internal structures there is no real need to have them inside the VM code/blob.
This would also optionally reduce bloat in module loading inside the VM and remove extra hooks/path in the VM code, by making them reuse the normal loading path.

While technically this should also be done for `core` this is not desirable for the purpose of this request since it would require extra changes, like code generation to a file and more intrusive changes.

**Comment by ruby0x1** [comment]
I thought about this while working on 0.3.0, and for now since there is no other mechanism to access them easily, they'll remain in the VM repo. I agree that having them separate is a reasonable goal, just not one with a clear solution right now.
