### ISSUE TITLE
Suggestion: the representative image of wren 

### ISSUE THREAD

**Issue by sheee7** [wren-lang/wren#563]
Hi! Many popular programming languages have their own representative image. It makes people feel more friendly with that language. So, I made an Representative image for wren, because I want wren become more familiar to people. It has concept of wren as bird which is fast and small. The white dot on image means small and fast. Also it used color of wren website.

Why don't you use it?

![wren](https://user-images.githubusercontent.com/33317140/41359954-98a683fa-6f66-11e8-90cb-982049ebd1c4.jpg)

If you need PSD file, I can e-mail it.

**Comment by RudenkoArts** [comment]
Nice idea, I was thinking about it too, and also can participate in logo creation. : )

**Comment by sheee7** [comment]
Great! That was just a draft, so I'd like to make more detailed and cooperative image with you-all!
