### ISSUE TITLE
Binding class methods and other primitives at runtime

### ISSUE THREAD

**Issue by hugoam** [wren-lang/wren#593]
I'm studying how to implement binding Wren to my classes at runtime based on my own reflection metadata, in a similar fashion as I bound lua. (https://github.com/hugoam/mud/blob/master/src/lang/Lua.cpp)
I'm almost in a dead end, or all designs I can think of will end up way too complex. So I want to know if you can help me or give me some pointers :)

The crux of the problem is that, unlike in lua where there is a function call mechanism with upvalues (for closures) at the core of the library, in Wren everything is the other way around: everything is an object, so you only ever call methods, and the C API method binding mechanism doesn't allow you to store any closure data with it : you only give a bare function pointer, which is biased towards implementing all your foreign methods manually (or generating C++ code).

I can't bind C/C++ primitives at runtime without being able to store some "closed-over" values somehow (like a wren handle) together with the bound method in `bindForeignMethod`. Which, if I'm starting to understand Wren design, seems likely to be impossible.

So I've been trying to think of ways to store a Wren handle (to a foreign class that I defined to store my callable), but since I have no way to attach it to the bound method in the `bindForeignMethod` handler, I need an alternative.

Since in Wren closures seem to be a higher level construct based on the former mechanisms (objects, methods, etc...), I can think of some very contrived workarounds where I would define my closure classes, create instances of these closures for each of my primitives, and write boilerplate "proxy" methods that would call these closures in the body of the foreign class, and then compile all this Wren boilerplate. But there are two things about such a design : 
1. I'm still not sure it's entirely possible
2. that's more an argument towards not using Wren so far, and I really wanted to provide this otherwise very neat language :)

Did I miss something crucial that would help me implement this with Wren ? If I haven't been clear or making sense let me know too :)

**Comment by hugoam** [comment]
I think I found a pattern to maybe get this working : 
I need to create these foreign classes, so I only have to bind a handful of foreign functions :
```dart

foreign class Function {
    construct create(name) {}
    
    foreign call(func)
    foreign call(func, _)
    foreign call(func, _, _)
    // etc..
}

foreign class Member {
    construct create(class, name) {}
    
    foreign set(object, value)
    foreign get(object)
}

foreign class Static {
    construct create(class, name) {}
    
    foreign set(value)
    foreign get()
}

foreign class Method {
    construct create(class, name) {}
    
    foreign call(object)
    foreign call(object, _)
    foreign call(object, _, _)
    // etc..
}
```

And then for each class I need to bind, I just need to redirect to a bunch of these primitives, stored as static members, initialized at startup 👎 
```
foreign class vec3 {
    
    static init() {
        __x = Member.create("vec3", "x")
        __y = Member.create("vec3", "y")
        __z = Member.create("vec3", "z")
    }
    
    add(v) { return __add.call(this, { v }) }
    
    x { return __x.get(this) }
    x=(value) { __x.set(this, value) }
    
    y { return __y.get(this) }
    y=(value) { __y.set(this, value) }
    
    z { return __z.get(this) }
    z=(value) { __z.set(this, value) }
    
    static up { return __up.get() }
    static up=(value) { return __up.set(value) }
}
```

This will probably add a significant overhead as opposed to a lua-like system of directly binding closures, but if I can get this working, I would probably be okay with that.

I'll try to implement this tomorrow and let you know if I manage :)

**Comment by hugoam** [comment]
I have one blocker.
If I write : 

```dart
foreign class Constructor{
    construct create(class) {}
    
    foreign call()
}

foreign class vec3 {
    construct create() { __constructor.call() }
    static init() {
        __constructor = Constructor.create("vec3")
    }
}
```

Can I call `wrenSetSlotNewForeign` in the implementation of `Constructor.call` and have that behave as if I called it inside of the `initialize` function ? Or will this break everything ?

**Comment by mhermier** [comment]
I don't understand what you are trying to achieve. It looks like reflexion API but not sure.

**Comment by hugoam** [comment]
I'll try to make the problem clear: 
I have N C++ classes with members, methods, constructors which I'm binding to Wren.
However, I don't write N*x C function to bind each of these foreign primitives: I have a generic reflection mechanism to do that, so I instead want to bind all of these foreign object members, methods and constructors to one single C function which itselfs calls my runtime reflection. However, this function needs context about the class, but Wren doesn't have any mechanism to either bind closures to foreign methods, and it doesn't have a mechanism to get the class in the handlers either IIUC.

The approach described above would have worked, except for one blocker on which I'm stuck on: the foreign class constructor apparently needs `wrenSetSlotNewForeign` to be called **inside** the `initialize` handler, so my idea of allocating the actual foreign object inside a `Constructor.create()` method called by the foreign constructor body doesn't work: the constructor body is only called if the foreign object was already allocated (and not doing so yields an error apparently).

**Comment by mhermier** [comment]
Earlier today I started to think that since we have wren_modules in place it was time to import wrenalyzer in the source code, so we can start some automated tooling. With that in place it should be possible to do binding generation. Do you think this could help you ? I mean wrenalyzer has to be updated and and stuff, but it has in its code the tools to produce AST of wren source, so it should be relatively ease to produce a binding generator for your needs.

**Comment by mhermier** [comment]
Otherwise re reading your constructor problem, I don't see any reason why you should not be able to call `wrenSetSlotNewForeign` anyware in C code. Just avoid to call `wrenEnsureSlots` since it is still broken frown within a foreign. But it should just work.

**Comment by hugoam** [comment]
I'm trying to avoid generating more code here, so a generator wouldn't really help.

I don't really understand the design of `wrenSetSlotNewForeign`, it only satisfies a very very narrow use case.
- It's meant to be called from C directly but doesn't call the constructor body in this case (so why do foreign classes have constructors in the first place ?)
- When called from Wren (which is the only way to create a C/C++ construct from Wren code), it's actually allocating the whole object itself, not just the foreign part. Which means that I can't call it anywhere, I **have** to call it in `initializer`, because if I don't there is simply no object. (and the actual constructor then fails to call)

It fits two different uses at the same time but doesn't fit either use well. It also allows to call `wrenSetSlotNewForeign` outside of the `initializer` with the same class but a different size than inside the `initializer` (which doesn't make sense).
It would really need to be split up in `wrenSetSlotNewForeign` to create an object and `wrenAllocateForeign` to allocate the data itself. The latter would be called inside of the initializer (or in a handler called by the constructor, which is what I'm trying to do).

**Comment by mhermier** [comment]
Foreign constructors are for the case, where calling the WrenReallocateFn is enought to initialise the object, so you can then do the extra initialisation in wren.

wrenSetSlotNewForeign is basically a memory allocator from the C point of view. So it returns a void* to the memory allocated for the foreign data. You can use that to do a C function call to initialise your data, like you would after a malloc. Or in C++ initialise your object wirth a placement new call, and finialise with a distructor method call to ~Foo() (do not call delete since the memory is owned by wren).

**Comment by mhermier** [comment]
I think you missed one point, wren doesn't require you to have a constructor method to allocate a foreign object. You can have a static foreign method (of any name) that create the foreign object for you. So you can do something like:
```
foreign class Foo {
  foreign static new() // This is an allocator with the usual name
  foreign static new(a, b, c) // This is an allocator with the usual name, and 3 parameter
  foreign static singleton()  // This is an allocator with an unusual name that returns a singleton instance
  foreign construct new() // Not sure it works, but it should technically call a WrenReallocateFn and then 
                                       // a foreign method with "init new()" signature.
}
```

**Comment by hugoam** [comment]
Thanks for the clarifications, I deleted my comment before you answered because I was guessing I misunderstood something. I'll look into all these options and update this issue soon :)

**Comment by hugoam** [comment]
I found a way to make this work.
But I have a full additional level of indirection on each constructor, function, setter, getter and method call, that wouldn't need to be there if Wren made foreign functions to be plain closures, instead of just a simple C function pointer. I don't know Wren internals enough to estimate how complex of a change that would be, but I would gladly study it if you think it's doable and would be open to a pull request regarding this.

**Comment by hugoam** [comment]
If you mean that the type `WrenForeignMethodFn` returned by `bindForeignMethod` is then an object to which I can attach some values, then yes

**Comment by hugoam** [comment]
Actually, I said I managed to make this work, but I still had to add a missing function to Wren.
It's a bit off-topic to this issue, but unless I'm mistaken there is no way in the public interface to assign a value to a variable from C. Which, to do two-ways C/Wren interactions, is kind of a fundamental feature. 

So I added this function:
```
void wrenAssignVariable(WrenVM* vm, const char* module, const char* name, int value_slot);
```

Should I open a pull request with this patch ?

**Comment by mhermier** [comment]
Try to make pull request, though I should see the code to be sure you don't
create a new variable, else it should be fine.

**Comment by hugoam** [comment]
Can you have a quick look ? I really started looking into Wren 2 days ago, so it's very likely I'm not doing it exactly the way it should be done ^^
https://gist.github.com/hugoam/2483e240573cc9aa90cf7f778c2bc223

**Comment by hugoam** [comment]
I don't want to open new issues for things that might just be due to my misunderstanding of how Wren works, but I have another problem.

I'm trying to use `wrenCall()`, I have my method handle for `init(_,_)`, and I'm pushing three values of type class A, class B, and class C in slots 0, 1 and 2. (class A is the class that has the `init(_,_)` method). The call doesn't succeed, with the error being `Null does not implement 'init(_,_)'`

When I inspect the `vm->apiStack`, it indeed has three objects of type `A`,  `B`, and  `C` in slots 0, 1 and 2. However when I inspect the values in `fiber->stack`, it has three objects of type `Null`, `B metaclass`, and `C metaclass`.

Again, I don't want to open an issue for something that might not be a bug, but if you can help me understand what's going on here, I'd be thankful :)

**Comment by hugoam** [comment]
And a last question: is it expected that `int currentSize = (int)(vm->fiber->stackTop - vm->apiStack);` inside of `wrenEnsureSlots` (https://github.com/munificent/wren/blob/master/src/vm/wren_vm.c#L1580) sometimes has a **negative** value ?

Also the documentation of `wrenEnsureSlots` specifies it's meant to be used inside of foreign methods, but I'm following the documentation about `Calling Wren from C` and it's using that function, outside of a foreign method, which is what I am doing here.

**Comment by hugoam** [comment]
After investigating, I think I now understand the root of all these issues : 
Wren is not at all designed to be called from C outside of foreign functions. So everything related to vm->apiStack will only behave correctly when called inside a foreign functions. You cannot use these straight up from C code.

This is not even about **re**-entrancy (I saw there is work on this going on), but it's just about simple entrancy. I didn't know that it's not supported. This should probably be specified somewhere ?

**Comment by hugoam** [comment]
I'm investigating, and something is deeply wrong with the plain C -> Wren calling mechanism...
I'm wondering if anyone is actually using this, because it seems to be simply broken. If you are calling Wren repeatedly directly from C, `wrenEnsureSlots` behavior is broken (the negative value I reported earlier) because `vm->apiStack` and `fiber->stackTop` simply don't point to the **same chunk of memory**.

**Comment by mhermier** [comment]
This issue is known. In some situations wrenEnsureSlot is the source of
stack corruption. But resolving it requires partial reentrancy support, and
Bob takes its time...

**Comment by hugoam** [comment]
Well, with all due respect, there should be a big red disclaimer at the top of the `Calling Wren from C` section from the docs saying that it **doesn't work** and you shouldn't use it...

I don't think it requires reentrancy support. This is simply a matter of entrancy. Entrancy doesn't work, in the current state.
I just added a two-liner that solves the problem for me : 
`
void wrenBegin(WrenVM* vm)
{
	vm->fiber = wrenNewFiber(vm, NULL);
	vm->apiStack = vm->fiber->stack;
}
`

Also solving the stack corruption should be high priority : a simple way to keep track of it would be to check which fiber `apiStack` refers too. `wrenEnsureSlots` should have a big ASSERT checking that that fiber is the same as  `vm->fiber`.

**Comment by mhermier** [comment]
The source of the corruption is that some internal function backup the
apiStack on the host stack. Meaning there is reentrancy happening.

**Comment by hugoam** [comment]
The behavior of `wrenEnsureSlots()` is very dangerous and error-prone in any case... It should have a safeguard or an assert to prevent it doing that terribly wrong thing that it is currently doing.

**Comment by hugoam** [comment]
Actually I think this can already be enforced : 
just add the following before checking the `currentSize` inside of `wrenEnsureSlots()`
```
  ASSERT(vm->apiStack >= vm->fiber->stack && vm->apiStack < vm->fiber->stackTop,
	     "apiStack must be contained in the current fiber stack");
```


Unless I overlooked something, this should always be the cases in the situations where `wrenEnsureSlots()` is safe to execute.

**Comment by mhermier** [comment]
This is it, any resize that results in resize of the stack will trigger the
issue (which defeats the purpose of that function).

**Comment by hugoam** [comment]
That's not really what's happening in the issue I'm triggering here.
Resizing the fiber stack works perfectly fine, the issue I have is triggered by `wrenEnsureSlots()` measuring it using two pointers that aren't relative to the same stack/memory chunk, hence it tries to resize it with a completely absurd/corrupt value like `34053940`.
Adding this check ensure that the `apiStack` is a pointer relative to the fiber `stack` and not something completely unrelated relative to another fiber stack.
