### ISSUE TITLE
Is there a better way of using default values for constructors?

### ISSUE THREAD

**Issue by novemberisms** [wren-lang/wren#596]
If I want to have a class constructor be overloaded by arity, and the missing arguments will have some default values, I can't think of another way to do it except having a private init_ function that's called by each constructor. Something like this:

```wren
class Timer {
	// this is the actual method that sets all the fields
	init_(period, one_shot, callback) {
		_period = period
		_timeLeft = period
		_stopped = false
		_oneShot = one_shot
		_callback = callback
	}
	// if all arguments are provided, just give them all to init_
	construct new(period, one_shot, callback) {
		this.init_(period, one_shot, callback)
	}
	// the default value for callback is null
	construct new(period, one_shot) {
		this.init_(period, one_shot, null)
	}
	// the default value for one_shot is true
	construct new(period) {
		this.init_(period, true, null)
	}
}
```

and I'm wondering if there's a more idiomatic or better way to do this? I'm testing out wren for a mini 4x game and I would love to learn more about it. Thank you for any help!

**Comment by avivbeeri** [comment]
I usually do something similar. If the class is just a Plain Old Data object, I put defaults into the field getters instead:

```
class Data {
  value { _value || 0 }
}
```

**Comment by mhermier** [comment]
Nice catch.

About the original question, I don't remember if 'this(a, b, c...)' syntax
is supported. I know it is supported with 'super' so if it's not with
'this' then it is an error.
That way you could call somehow other constructors.

**Comment by avivbeeri** [comment]
No, I don't believe you can call constructors within constructors. I use a separate private method like `setValues(a, b, c, d)` and call that from the constructors with the appropriate options. It's tedious though.

**Comment by mhermier** [comment]
I just checked, you can't use 'this(a, b, c)'. And for me this is an error.
If it is allowed for 'super', it has to also be allowed for 'this'.

Le mar. 18 sept. 2018 à 15:11, Aviv Beeri <notifications@github.com> a
écrit :

**Comment by mhermier** [comment]
I toyed with the compiler a little, and it is not possible to add the
'this(a, b, c...)' because it introduce an ambiguity in the language.

Because of the getter function syntax 'this' it adds the meaning: calling a
function with the same name as a getter.

Unless we introduce a new keyword ('self'?) or use an operator, I don't
think we can introduce such feature unfortunately...

**Comment by avivbeeri** [comment]
Yeah, I figured this would be the case. Why not something like `this.init`
if `init` was your constructor name?

**Comment by mhermier** [comment]
If I remember well: because of convoluted black magic Bob wants to have.
The 'construct' keyword make the method not usable by normal means since it
has a *broken* signature.
