### ISSUE TITLE
arg missmatch in tutorial 

### ISSUE THREAD

**Issue by ghost** [wren-lang/wren#599]
http://wren.io/embedding/#executing-wren-code

```c
WrenInterpretResult result = wrenInterpret(vm, 
    "System.print(\"I am running in a VM!\")");
```

...but https://github.com/munificent/wren/blob/master/src/include/wren.h#L293 has three args.

**Comment by minirop** [comment]
the `module` parameter was added 6 months ago in commit 8a71735e0f18b2f8f6022f5c8c8fe1044bbc741d you can do a PR to fix it. it's in `doc/site/embedding/index.markdown`

**Comment by monouser7dig** [comment]
I'll pass on that for now, but want to thank for the very good documentation ! 👍
