### ISSUE TITLE
Interactive mode crashes when a `\` is typed after a `"`.

### ISSUE THREAD

**Issue by MageJohn** [wren-lang/wren#603]
When I run wren in interactive mode and start to type out a string literal with a backslash escape sequence, the program immediately crashes. The crash is not very graceful, printing the error without a newline in front, and leaving the terminal text in the colour of the syntax highlighted `"`. 

The error is:
```
Range end out of bounds.
[repl line 555] in text
[repl line 344] in refreshLine(_)
[repl line 28] in run()
[repl line 929] in (script)
[<repl> line 1] in (script)
```
 
My system is GalliumOS, which is based on Xubuntu. I compiled wren per the instructions on the Getting Started page.

EDIT: I get the same problem on Arch Linux, with wren installed from community repo. The line numbers have changed, but this is probably just because they're different versions.

**Comment by dread-uo** [comment]
I can confirm this issue on Fedora 28 as well, with latest `wren` compiled with `gcc` 8.1.1
