### ISSUE TITLE
Tuple: immutable list type

### ISSUE THREAD

**Issue by MageJohn** [wren-lang/wren#607]
Tuples, or immutable lists, are very useful. Because they are immutable
they can be used as keys in maps, and they can be optimised for access speed and size. 

## Syntax

In Python (which is where I know tuples from), a set of expressions separated by commas is a tuple. Parentheses can be put around the expressions to separate them from the ones around it. Therefore that's the syntax I will suggest:

```
tuple = 1, "banana", true
// which is equivalent too
tuple2 = (1, "banana", true)

// tuples can be nested
tuple3 = 1, "banana", ("foo", "bar"), true
```

Tuples with 0 and 1 elements are a little trickier. An empty tuple can be created with a pair of empty parentheses. On the other hand, a one element tuple is created with a single item followed by a comma. 

```
emptyTuple = ()
oneElement = 1,
// or
oneElement = (1,)
```

**Comment by avivbeeri** [comment]
This could be easily emulated by wrapping a List inside a class and only providing a constructor and getter, although this method wouldn't allow for hashing into maps.

**Comment by MageJohn** [comment]
Wrapping a list in a class misses the point of tuples. It's not that being immutable is the goal, it's the sacrifice that makes the benefits possible.

**Comment by novemberisms** [comment]
What is an actual use case for tuples that you cannot do without them? Is this motivated by a real-world application you need? Or are you just proposing to add stuff for no reason? 

As a minimal scripting language, adding tuples seems like bloat. After all, most of the popular scripting languages see tuples as superfluous. Neither Lua nor Javascript have tuples because they are an unnecessary structure.

**Comment by MageJohn** [comment]
Fair enough. What I meant by that sentence was that tuples main advantage is being hashable, so you can use them as keys in maps; their immutability is necessary to make that possible. They have some less tangible benefits too: they imply that the data isn't meant to be changed, which can help understanding of code; secondly, they can be optimised better than lists, and therefore have speed advantages. 

My reason for wanting tuples comes from a small game I was writing in wren for the TIC-80 fantasy computer. It's a snake game, and I represented the direction the snake moves in with a list of `[delta x, delta y]`. I then want to rotate the sprite representing the head of the snake in the direction it's moving, and so I want to use the direction as a key in a map. I can't do this, so I resorted to a slightly hacky (and hard to read) conversion to a string to do the job. You can look at the code here: https://gist.github.com/MageJohn/d9fee1983f5810951472f21a3473fa41

Bear in mind I come from Python. Perhaps someone could point out a style that's more in line with wren.

**Comment by mhermier** [comment]
I transposed map code in pure wren (more than once). It is a costly, but as
long as you expose 'hash' getter it is not as bad as it looks, and allow
you to use any hashable objects.

**Comment by bjorn** [comment]
> Bear in mind I come from Python. Perhaps someone could point out a style that's more in line with wren.

What about, instead of using some abstract container, you would define an appropriate data type for what you need and make your code a bit more readable in the process? Isn't the following the immutable type you're looking for?

```dart
class Pos {
    construct new(x, y) {
        _x = x
        _y = y
    }

    x { _x }
    y { _y }
}
```

**Comment by MageJohn** [comment]
@bjorn Yeah, I can see that working. Can you then write a hash function?

**Comment by avivbeeri** [comment]
It depends on the values. If you are looking to hash pairs of numbers, I
highly recommend the szudzik function, for example.

**Comment by mhermier** [comment]
As mentioned earlier you can write the hash function/methods. And in your
case I think a simple or between the values can do the trick. But as
mentioned earlier and with a deeper explanation: because stock wren is not
reentrant you can't use native map.

**Comment by bjorn** [comment]
> Yeah, I can see that working. What would be needed for a hash function so it can be used in maps?

So, as @mhermier mentioned you currently can't customize the hash function used for objects, and when trying to use an object as a key in a map Wren even prints out "`Key must be a value type.`". So you'd need to keep converting to a value type, like you were already doing with your list solution:
```dart
class Pos {
    construct new(x, y) {
        _x = x
        _y = y
    }

    x { _x }
    y { _y }

    toString { "%(x),%(y)" }
}

var a = {}
var p = Pos.new(1, 2)

a[p.toString] = true
```

**Comment by MageJohn** [comment]
Thank you everyone. I'll see about implementing those suggestions.
