### ISSUE TITLE
Multi-line strings

### ISSUE THREAD

**Issue by IngwiePhoenix** [wren-lang/wren#632]
I haven't been able to find this yet, but does Wren support any kind of multi-line string? Be it a Here- or NowDoc syntax or something similiar?

Also, the "%(...)" part seems to not be in the docs - or, did I just overlook that? I found it while browsing the source.

**Comment by underscorediscovery** [comment]
The latter is called "string [interpolation](http://wren.io/values.html#interpolation)" and is documented. 

I haven't seen any docs on any multi-line syntax and had been curious recently, but if you just hit enter during a line it is valid (however it will include any whitespace). Only option I know of that I use is `+` on each line.

**Comment by mhermier** [comment]
Substring exist. Use subscript with a range.

**Comment by IngwiePhoenix** [comment]
Oh wow - I didn't know that! Thank you for that.

I also figured out how to iterate through each individual character as well, so I am almost set.

What I can not figure out yet is how to overwrite an entry within an iteration. Like if I had `for(line in source)`, where `source` is an array of strings, how can I replace the entry representing `line` within `source`? Alternatively, I could create a new list and append to it - but, how do I actually append? `.append` is not implemented, neither is `.push`. And `newlist[] = line` is a syntax error...

**Comment by IngwiePhoenix** [comment]
Nevermind the last post's last part... I should really read closer - my visual impairment shall not be an excuse ^^; It's `.add()` in here. And, I can not assign directly, except when I use the iteration protocol directly - which, really, doesn't seem all too fancy. So instead I will just create a new list. With that, I made a basic implementation for multi line strings:

```
var x = "
  | #include <foo>
  | int main() {}
"
var y = x.split("\n")
var z = []
for(line in y) {
  line = line.trim()
  if(line.count > 0) {
    line = line.replace("| ", "")
    z.add(line)
  }
}
z = z.join("\n")
System.print(z)
```

Couldn't find `continue` in the docs, but `break` instead... Well, this isn't too bad, but it would be nice having `continue`. I also tried `next`, but both resulted in an `undefined variable` error.

**Comment by underscorediscovery** [comment]
Here's one option (slightly more idiomatic):
```lua
var x = "
  | #include <foo>
  | int main() {}
"
var lines = x.split("\n")
lines = lines.map {|line| line.trim().replace("| ", "") }.toList
System.print(lines)
```

notes:
- [the sequence](http://wren.io/modules/core/sequence.html) class is superclass to many things, it's great
- sequences need `toList` to evaluate them eagerly, i.e convert the sequence into a list
