### ISSUE TITLE
Top-Level functions

### ISSUE THREAD

**Issue by IngwiePhoenix** [wren-lang/wren#633]
We can already do this:

```
var aFunc = Fn.new {
  // ...
}
aFunc.call()
```

But what if we just want to define a couple of top-level functions, without having to add `.call` each time, as you don't need that on methods anyway? I mean, I am surprised that `function` is not even a reserved word...

I would like to just define a few helper functions in a tiny script, and something like this would make things a little bit easier, if not at least more readable:
```
function aFunc() {
  // ...
}
aFunc()
```

**Comment by mhermier** [comment]
Because of the function getter syntax it is not possible to add the short
syntax to call functions. There is also a small issue with the naming you
can't use global variable name from within a class.

I have the patch ready on my fork to add function and a *lambda* (rev
slash) syntax. I need to seriously add tests to it, but basically it is
only ~10 lines changes each.

**Comment by bjorn** [comment]
> There is also a small issue with the naming you can't use global variable name from within a class.

Well, you can, but the variable name has to start with a capital.

**Comment by mhermier** [comment]
My bad I thought I wrote the capital letter rule.

**Comment by IngwiePhoenix** [comment]
> > There is also a small issue with the naming you can't use global variable name from within a class.
> 
> Well, you can, but the variable name has to start with a capital.

Can you elaborate this? Do you mean something like this?

```
var aVar = 0;
var BVar = 0;
class MyClass {
  static increment() {
    aVar++; // <- Fails because not having a capital letter?
    BVar++; // <- Would not fail, as "B" is capital?
  }
}
```

**Comment by IngwiePhoenix** [comment]
@mhermier Do you have made a PR of it yet? I'd love to see what you came up with. :)

**Comment by bjorn** [comment]
> Can you elaborate this? Do you mean something like this?

Yes, turned into valid Wren code:

```dart
var aVar = 0
var BVar = 0
class MyClass {
  static increment() {
    System.print(BVar) // <- Would not fail, as "B" is capital?
    System.print(aVar) // <- Fails because not having a capital letter?
  }
}
MyClass.increment()
```
Outputs:
```text
0
MyClass metaclass does not implement 'aVar'.
[main line 6] in increment()
[main line 10] in (script)

```

**Comment by mhermier** [comment]
No PR for now, I'm currently heavily plumbing my fork, and this is
currently upper on my stack. But this patch should semlessly apply to
upstream at the end.

**Comment by IngwiePhoenix** [comment]
@mhermier Cool! I am looking forward to this patch :)

@bjorn Thank you for explaining. I will make sure to keep this in mind when I construct POCs of classes/objects/modules... This would otherwise be quite confusing :)

**Comment by IngwiePhoenix** [comment]
I didn't want to pop a new issue ticket just for this but with the addition of attributes and other recent additions, I wanted to try my luck and ask again anyway:

Are we ever going to see toplevel functions in Wren? It's 2021, maybe things changed? :)
