### ISSUE TITLE
Variable may be used uninitialized

### ISSUE THREAD

**Issue by nbuwe** [wren-lang/wren#635]
Variable `entry` in `insertEntry` may be used uninitialized:

https://github.com/munificent/wren/blob/744147fd94febd7dae0c14f132f2dec363252a6f/src/vm/wren_value.c#L522-L531

https://github.com/munificent/wren/blob/744147fd94febd7dae0c14f132f2dec363252a6f/src/vm/wren_value.c#L455-L459

Neither `entry` is initialized, nor `findEntry` sets it to NULL if capacity is not ensured, so when this assert should be triggered the variable is not actually set.

**Comment by mhermier** [comment]
Trivial, initialize entry to NULL on line 522.

I think I have pull request for this somewhere, but can't find it. For some reasons, gcc only find it when not using WREN_NAN_TAGGING.
