### ISSUE TITLE
Binding Fn instance to a custom "this" or "environment"

### ISSUE THREAD

**Issue by IngwiePhoenix** [wren-lang/wren#638]
Hello.

I would like to know if it is possible to "bind" to an instance of `Fn`, allowing to either have a pre-defined `this` (as to execute a callback in the context of another instance) or a pre-defined variable, that holds this very instance - like `self`?

What I basically want to do:

```wren
class Something { /*...*/ }
var cb = Fn.new { /*...*/ }
var inst = Something()
x.bind(inst).call()
```

I tried looking into `wren_values` and `wren_core`, but could not find any hints - except for the maximum arguments passable to `.call` actually being limited to some amount.

Any idea?

Kind regards,
Ingwie.

**Comment by underscorediscovery** [comment]
The simplest method of doing this would just be an argument to the function, right?  i.e `fn.call(self, others)`. For me, not a fan of _magic_, like a _magic variable_ that exists alongside `this` that's hidden, i'd rather it be explicit in the callback args. So I personally wouldn't try for that approach.

If you wanted to try and hack on it locally, I'd probably go more along the lines of `fn.callWithThis(inst, args...)` or something along the lines. This would require special handling though so I'm not sure it would gain much except complexity. 

For more context, there are upvalues that a method can see. These are resolved by the compiler when emitting the bytecode, so any changes to what upvalues are accessible to a given method would be added/modified there. That's the only way I can think of off the top of my head that won't require changing the opcodes to include a bound call.

**Comment by IngwiePhoenix** [comment]
I see, well that's too bad :) Looks like going with the parameters would be the only option I really have. To explain, I was wanting this to be able to construct a build target (I am working on making a build tool based on Wren):

```wren
Native.binary("myBinary") {|t| // <- It would've been nice to use "this" instead.
  t.input = ["./src/main.c"]
  t.on("configure") {
    // ... snip ...
  }
}
```

Well, I guess it can't be helped :)

**Comment by IngwiePhoenix** [comment]
That is actually up to the user, they could use `t` or `target` :) I am trying to make this project unopiniated, easy and fluent - so that the user can decide what he does with it, and has enough leeway to make themselves a home with it. So if they prefer the shorter `t`, then they use that. If they are a more elaborate person, they may prefer `target` or even `thisTarget`... :) But thank you for your opinion there, this is much appreciated!
