### ISSUE TITLE
bind foreign methods is slow

### ISSUE THREAD

**Issue by liigo** [wren-lang/wren#648]
You must `strcmp` class names and method signatures every time when `WrenBindForeignMethodFn` is called (by the VM). The more foreign methods you have, the more you call `strcmp`.

```
// Returns a pointer to a foreign method on [className] in [module] with
// [signature].
typedef WrenForeignMethodFn (*WrenBindForeignMethodFn)(WrenVM* vm,
    const char* module, const char* className, bool isStatic,
const char* signature);
```

**Comment by mhermier** [comment]
Nothing prevent the user to use a better approach than to test symbols one
by one.
Other solutions have some disavantages compared to this lazy/at demand
approach.

**Comment by munificent** [comment]
Yes, binding is fairly slow, but the idea is that you don't bind methods in performance-critical code. Foreign methods are bound when the *class declaration itself* executes, not when *the method is called*. So, in this code:

```
class Foo { 
  foreign method(arg)
}

for (i in 1...1000) {
  var foo = Foo.new()
  foo.method()
}
```

The VM will only call your bind function once, at the point that the class is declared, not each time an instance is created or a method is called inside that loop.
