### ISSUE TITLE
Amalgamation not working

### ISSUE THREAD

**Issue by MarcoLizza** [wren-lang/wren#649]
I've been trying to integrate Wren by mean of the amalgamation file, and I've encountered two different issues.

The first being that the "optional" sources are tentatively merged in the amalgamated source but, due to the position in a sub-path, the build fails prematurely.

Even when moving the optional files from their folder to the main, the amalgamated result does not compile properly since the 'call()' function is defined twice with a different signature.

Should the optional files be moved elsewhere (or skipped during the amalgamation)?

**Comment by underscorediscovery** [comment]
Fixed by #541 and https://github.com/wren-lang/wren/commit/cdeb0db5c34691c1b715dd3e48e77596dd94fc58 !
