### ISSUE TITLE
Windows build not working

### ISSUE THREAD

**Issue by ZenToad** [wren-lang/wren#650]
Windows 10, Visual studio 2017
Initial project build would not work because I have the windows SDK 10 and not SDK 8.

I did the standard Project->Retarget Solution.

The Rebuild Project fails with the following output:

1>------ Rebuild All started: Project: wren, Configuration: Debug x64 ------
2>------ Rebuild All started: Project: wren_lib, Configuration: Debug x64 ------
2>wren_opt_meta.c
2>wren_opt_random.c
2>wren_compiler.c
2>c:\dev\wren\src\vm\wren_compiler.c(715): warning C4244: 'function': conversion from '__int64' to 'double', possible loss of data
2>wren_core.c
2>wren_debug.c
2>wren_primitive.c
2>wren_utils.c
2>wren_value.c
2>wren_vm.c
2>Generating Code...
2>wren_lib.vcxproj -> C:\dev\wren\util\vs2017\lib\..\..\..\lib\wren_static_d.lib
2>Done building project "wren_lib.vcxproj".
1>The system cannot find the file specified.
1>Cloning libuv...
1>Getting tags...
1>Checking out libuv v1.10.0...
1>Downloading gyp...
1>Deleting unneeded files...
1>Traceback (most recent call last):
1>  File "../../update_deps.py", line 73, in <module>
1>    main(sys.argv)
1>  File "../../update_deps.py", line 53, in main
1>    remove_dir("deps/libuv/build/gyp/infra")
1>  File "C:\Users\twright\dev\wren\util\util.py", line 46, in remove_dir
1>    ['cmd', '/c', 'rd', '/s', '/q', dir.replace('/', '\\')])
1>  File "C:\Users\[my_user_name]\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 341, in check_call
1>    raise CalledProcessError(retcode, cmd)
1>subprocess.CalledProcessError: Command '['cmd', '/c', 'rd', '/s', '/q', 'deps\\libuv\\build\\gyp\\infra']' returned non-zero exit status 2.
1>b'Warning: Visual Studio not found\r\n[\'-Dtarget_arch=x64\', \'-Duv_library=static_library\', \'.\\\\uv.gyp\', \'-I\', \'.\\\\common.gypi\', \'--depth=.\', \'-Dhost_arch=x64\']\r\nTraceback (most recent call last):\r\n  File "gyp_uv.py", line 94, in <module>\r\n    run_gyp(gyp_args)\r\n  File "gyp_uv.py", line 38, in run_gyp\r\n    rc = gyp.main(args)\r\n  File ".\\build\\gyp\\pylib\\gyp\\__init__.py", line 545, in main\r\n    return gyp_main(args)\r\n  File ".\\build\\gyp\\pylib\\gyp\\__init__.py", line 530, in gyp_main\r\n    generator.GenerateOutput(flat_list, targets, data, params)\r\n  File ".\\build\\gyp\\pylib\\gyp\\generator\\msvs.py", line 2029, in GenerateOutput\r\n    msvs_version)\r\n  File ".\\build\\gyp\\pylib\\gyp\\generator\\msvs.py", line 1853, in _CreateProjectObjects\r\n    guid = _GetGuidOfProject(proj_path, spec)\r\n  File ".\\build\\gyp\\pylib\\gyp\\generator\\msvs.py", line 912, in _GetGuidOfProject\r\n    guid = guid or MSVSNew.MakeGuid(proj_path)\r\n  File ".\\build\\gyp\\pylib\\gyp\\MSVSNew.py", line 60, in MakeGuid\r\n    d = _new_md5(str(seed) + str(name)).hexdigest().upper()\r\nTypeError: Unicode-objects must be encoded before hashing\r\nFailed to create vc project files.\r\n'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: The command "python ../../update_deps.py
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: python ../../build_libuv.py -64
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "wren.vcxproj" -- FAILED.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

**Comment by underscorediscovery** [comment]
Thanks for the report! We've been looking into it and have found a few small discrepancies in the python scripts with regards the CLI tool and libuv stuff. We're working on some solutions in the mean time.

**Comment by SuperWangKai** [comment]
@ZenToad Though the Windows build looks like always in broken state. Your issue seems directly related to enviroment path of Python 2 - https://github.com/wren-lang/wren/tree/master/util/vs2017

**Comment by ZenToad** [comment]
I will check it out.  Thanks.

**Comment by ZenToad** [comment]
Yes I don't have python 2.7.  Since it's end-of-life is in 10 months I'm not going to bother with it.
Thanks though.
