### ISSUE TITLE
Error message buffer too small

### ISSUE THREAD

**Issue by paxos1977** [wren-lang/wren#651]
> cc src/vm/wren_compiler.c          -O3 -std=c99 -fPIC
> src/vm/wren_compiler.c: In function ‘error’:
> src/vm/wren_compiler.c:402:36: error: ‘: ’ directive writing 2 bytes into a region of size between 1 and 159 [-Werror=format-overflow=]
>    int length = sprintf(message, "%s: ", label);
>                                     ^~
> src/vm/wren_compiler.c:402:16: note: ‘sprintf’ output between 3 and 161 bytes into a destination of size 159
>    int length = sprintf(message, "%s: ", label);
>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> 

It would appear the message buffer is two bytes too small as it doesn't account for the colon and the space in the `sprintf()` call.

**Comment by underscorediscovery** [comment]
Hi thanks for the effort! See #620 as there has been discussion around this particular bug in several threads :)

**Comment by paxos1977** [comment]
Oh sorry, I did a brief search through the issues and I missed that one.
