### ISSUE TITLE
Proposal: Wauxlib

### ISSUE THREAD

**Issue by walterschell** [wren-lang/wren#661]
I think it would be useful to include a Wauxlib (Wbatteries/Wextrastuff?) along side the core language that is separate from the core language but included by default similar to the optional modules but slightly greater scope. The individual components of the library should be severable via configuration.

In particular, this library should include a standard implementation of a binder and a loader. The structure outlined below doesn't strictly require, but would be greatly aided by changing the signature of the binding and load callbacks to include a `void *` for binder and loader specific context data.

The default loader would be based on the cli loader with the following addition: It would also look for shared objects named appropriately (wren-modmodulename.so/dll/dynlib). If found it would open the shared object and resolve `wren_mod_config` which would be a struct similar to 
```C
typedef struct
{
uint32_t wren_api_ver; //Or possibly the wren semantic version
WrenLoadModuleFn loadModuleFn;
void *loadModuleFnCtx;
WrenBindForeignMethodFn bindForeignMethodFn; 
WrenBindForeignClassFn bindForeignClassFn; 
void *bindForeignCtx
}
```
If the function pointers are NULL then the so is requesting the  default implementation.
For `loadModuleFn` this would mean casting `loadModuleFnCtx` as a `char *` and returning it. (The default load would keep track of which  file was dlopened for which module)

For the `bindForeign` methods that would mean casting the `bindForeignCtx` into an array of structures terminated by a sentinel the way the cli does and using the same binder that the cli does to process it.

The default binder would also have a function looking like
```C
void defaultBinderAddModule(void *binderCtx, //or as a struct BindCtx *, just depends where you want to cast
                                                char *moduleName,
                                                WrenLoadModuleFn moduleLoadModuleFn;
                                                void *moduleLoadModuleFnCtx;
                                                WrenBindForeignMethodFn moduleBindForeignMethodFn; 
                                                WrenBindForeignClassFn moduleBindForeignClassFn; 
                                                void *moduleBindForeignCtx);
```

with the same meaning for NULL function pointers. This would allow easier binding of foreign modules that are compiled into the application Wren is being embedded in.

**Comment by walterschell** [comment]
A little bit more concrete example of what is being proposed can be seen here https://github.com/walterschell/wren_playground. Let me know if anything there would be useful for the main project so I can start cleaning those features up, writing tests/docs and preparing a feature branch for them.

**Comment by underscorediscovery** [comment]
Thanks for the thoughts! Closing with the future tag for now.
