### ISSUE TITLE
[QUESTION] How to read value from list element

### ISSUE THREAD

**Issue by darmie** [wren-lang/wren#662]
```c
   wrenGetListElement(vm, slot, index, 0); // this returns a void
```

How do I read the value of the element from C?

**Comment by munificent** [comment]
We'll need a little more context here. What is "C"?

**Comment by munificent** [comment]
The site doesn't have full docs on the embedding API yet, but wren.h has some more detail:

```c
// Reads element [index] from the list in [listSlot] and stores it in
// [elementSlot].
void wrenGetListElement(WrenVM* vm, int listSlot, int index, int elementSlot);
```

This function pulls an element out of a list and stores it in another slot. Then, to read the element out of that slot, you can use the other `wrenGetSlot___()` functions.

**Comment by darmie** [comment]
Apologies for the naive questions:

How do I tell which slot to read from when i get the element?

**Comment by darmie** [comment]
This is what I am doing right now, but my programming environment isn't yet set up right to compile `C`, however I am reading the tests, and I want to know if my assumptions are correct:
```c
wrenGetListElement(vm, 1, index, 0);
const char* val = wrenGetSlotString(vm, 0); // I assume slot is '0', is this right?
```

**Comment by munificent** [comment]
> How do I tell which slot to read from when i get the element?

The fourth parameter to `wrenGetListElement()` is the destination slot where you want the element to be put, so that's the one you read from.

```c
wrenGetListElement(vm, 1, index, 0);
const char* val = wrenGetSlotString(vm, 0); // I assume slot is '0', is this right?
```

Right, because that's what you passed to `wrenGetListElement()`. :)

**Comment by darmie** [comment]
Thank you! You have been very helpful!
