### ISSUE TITLE
Won't build on Android in Termux

### ISSUE THREAD

**Issue by xordspar0** [wren-lang/wren#665]
I'm trying to build the interpreter on my Android phone in Termux, and I'm hitting an error. Maybe it's because my phone's not rooted, or maybe it's the limited Android C libraries.

```
make[1]: Entering directory '/data/data/com.termux/files/home/src/wren'
       run util/build_libuv.py
b'[\'-f\', \'make\', \'/data/data/com.termux/files/home/src/wren/deps/libuv/uv.gyp\', \'-I\', \'/data/data/com.termux/files/home/src/wren/deps/libuv/common.gypi\', \'--depth=.\', \'-Goutput_dir=/data/data/com.termux/files/home/src/wren/deps/libuv/out\', \'--generator-output\', \'/data/data/com.termux/files/home/src/wren/deps/libuv/out\', \'-Dhost_arch=aarch64\', \'-Dtarget_arch=aarch64\', \'-Duv_library=static_library\']\nTraceback (most recent call last):\n  File "gyp_uv.py", line 94, in <module>\n    run_gyp(gyp_args)\n  File "gyp_uv.py", line 38, in run_gyp\n    rc = gyp.main(args)\n  File "./build/gyp/pylib/gyp/__init__.py", line 538, in main\n    return gyp_main(args)\n  File "./build/gyp/pylib/gyp/__init__.py", line 514, in gyp_main\n    options.duplicate_basename_check)\n  File "./build/gyp/pylib/gyp/__init__.py", line 130, in Load\n    params[\'parallel\'], params[\'root_targets\'])\n  File "./build/gyp/pylib/gyp/input.py", line 2776, in Load\n    check, generator_input_info)\n  File "./build/gyp/pylib/gyp/input.py", line 602, in LoadTargetBuildFilesParallel\n    parallel_state.pool = multiprocessing.Pool(multiprocessing.cpu_count())\n  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool\n    return Pool(processes, initializer, initargs, maxtasksperchild)\n  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/pool.py", line 140, in __init__\n    self._setup_queues()\n  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/pool.py", line 236, in _setup_queues\n    self._inqueue = SimpleQueue()\n  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__\n    self._rlock = Lock()\n  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__\n    SemLock.__init__(self, SEMAPHORE, 1, 1)\n  File "/data/data/com.termux/files/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__\n    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)\nOSError: [Errno 38] Function not implemented\n'
make[1]: *** [util/wren.mk:242: build/libuv.a] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/src/wren'
make: *** [Makefile:16: release] Error 2
```

**Comment by underscorediscovery** [comment]
It seems to be an error in python accessing `_multiprocessing.SemLock`, a function for multithreading stuff. The error says `OSError: [Errno 38] Function not implemented`, meaning the version of python doesn't support threads. I would look into the args to disable threading on the python somehow?

**Comment by walterschell** [comment]
If you don't mind dealing with CMake, check out the cmake branch of https://github.com/walterschell/wren configure with -DLIBUV_TERMUX=ON

**Comment by xordspar0** [comment]
Looking at https://github.com/asciinema/asciinema/issues/271 and https://bugs.python.org/issue3770, it seems like `Multiprocessing` isn't and won't be supported on Android because it lacks necessary features. I haven't looked at the Python code, but maybe it could be changed to use threads instead of processes like what the asciinema folks did.

By the way, @walterschell, the CMake build works great. 👍

**Comment by xordspar0** [comment]
Oh, I see. The Python code that has a problem isn't part of our repo, it's the vendored gyp. So the problem is that gyp doesn't support building on Android. I'll file this issue with gyp instead, and maybe we can upgrade to a newer version if this fix it.

**Comment by xordspar0** [comment]
Actually, gyp already supports this. There's an option to disable multiprocessing: `--no-parallel`. Libuv already enables this option if it detects that multiprocessing is not supported, with a catch: the method of detection that they use only works in Python 3. Python 2 doesn't seem to report that it can't do multiprocessing.

According to my tests, you can build the libuv master branch by itself in Termux. This is because the default Python for `env python` is version 3 on Termux. In Wren, we explicitly use `python2`. This is good, because the Python code we have vendored actually requires Python 2.

However, Gyp and libuv have both updated there code to work unmodified in both Python 2 and 3. We can get Wren to build on Android if we do 2 things:

1. Update our dependencies. I can track down the relevant commits.
2. Update our build scripts to require Python 3 instead of Python 2.

**Comment by underscorediscovery** [comment]
I'm going to close this as I'm working on both 1. and 2. If this comes up again we'll open a new issue on the right repo. Thanks for the report.
