### ISSUE TITLE
Warnings when building VM using Visual Studio 2017

### ISSUE THREAD

**Issue by Heaven31415** [wren-lang/wren#667]
Hey. I tried to build a 13dfebe1a5d0fa57e424cedc34f141519fada686 VM using Visual Studio 2017 and I found some warnings which we should fix.

```
Warning C499 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead.
Warning C4996 'vsprintf': This function or variable may be unsafe. Consider using vsprintf_s instead.
```

Warnings are about `sprintf` and `vsprintf` functions which are considered unsafe by Microsoft compiler. They recommend to use `sprintf_s` and `vsprintf_s` instead. 

Their recommendation is a little bit problematic because those functions have different semantics and they are optional part of C11, so they aren't implemented everywhere.

I see two different ways to get rid of those warnings:

1. We can add `#pragma warning (disable: 4996)` at beginning of files which are using those functions, this way Microsoft compiler won't complain anymore.

2. We can use conditional compilation along with macros to switch between those two different functions versions depending on which OS we are currently using.

What are we going to do?

Here is a link to Microsoft document about differences between those two versions: [link](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/sprintf-s-sprintf-s-l-swprintf-s-swprintf-s-l?view=vs-2017).

**Comment by mattiasljungstrom** [comment]
You can also "solve" this by defining _CRT_SECURE_NO_WARNINGS for VS builds.

**Comment by underscorediscovery** [comment]
yea, for [0.3.0](http://wren.io/blog/0.2.0-and-beyond.html) I am busy redoing the project files and refactoring the repos, so most of this will be resolved soon.

**Comment by ruby0x1** [comment]
0.3.0 defaults to defining `_CRT_SECURE_NO_WARNINGS ` now.
