### ISSUE TITLE
Import seemingly not working amongst modules

### ISSUE THREAD

**Issue by Skyway666** [wren-lang/wren#670]
I think that the best way to put this is with an example:

I have some modules that I want to be able to import to my scripts. Those are of course not compiled through wrenInterpret(), but instead the strings with their code are retruned when required using loadModule().

I have a problem trying to export a specific module into another, I get that the class I try to import is Null, so if course trying to call static functions in a Null doesn't work.

It's pretty weird, because I can import modules to scripts and modules between modules, but for some reason this specific combination of modules doesn't work.

This is the "Physics" module
```
import "ObjectLinker" for Vec3, EngineComunicator
import "UI" for ButtonComunicator

...
class ComponentPhysics{
        ...
	getEuler(){
		ButtonComunicator.C_ButtonGetState(0,0)
		EngineComunicator.consoleOutput("hello")
		return Vec3.new(PhysicsComunicator.C_GetEulerX(gameObject, component), 
                PhysicsComunicator.C_GetEulerY(gameObject, component), 
                PhysicsComunicator.C_GetEulerZ(gameObject, component))
	}
        ...
}
```
This is the scripts that calls it
```
import "ObjectLinker" for ObjectLinker,
EngineComunicator,
InputComunicator,
ComponentType

class bug is ObjectLinker{

construct new(){}

 Start() {
	_rigid_body = getComponent(ComponentType.PHYSICS)
 }

 Update() {
	_rigid_body.getEuler()
 }

}
```
This is the function that belongs to ObjectLinker that returns the instance
```
getComponent(type){
	var component_uuid = ObjectComunicator.C_GetComponentUUID(gameObject, type)
...
	if(type == ComponentType.PHYSICS){
		return ComponentPhysics.new(gameObject, component_uuid)
	}
 ...
}
```
I know this code makes no sense without context, but the thing is that calling ButtonComunicator.C_ButtonGetState() works, while calling EngineComunicator.consoleOutput() tells me that EngineComunicator is Null

I know for sure that the ObjectComunicator module works, since I use it everywhere, so why can this happen?

I don't want to copy all the code that I use here, since it would be a really long issue, but if it is needed I can send a .zip with the files or something.

**Comment by underscorediscovery** [comment]
From a quick look, is the issue here maybe circular reference? If module A imports module B which imports module A again, one of these will be null because it was still busy importing the first one.

Typically you can resolve this by `import` later on, closer to the usage site.

**Comment by underscorediscovery** [comment]
Closing for now until hearing back.
