### ISSUE TITLE
Create instances of a class without explicitly stating class name

### ISSUE THREAD

**Issue by G0BL1N** [wren-lang/wren#671]
Does wren have reflection or reflection-like functionality at the moment?
For example, i can't imagine how i can build list of entity classes, and then create their instances using that list. I can imagine it possible through CAPI, but that's not ideal. I might have to do it though...
And that can be easily done in pure lua, and in JS as well. 
Is there anything like that in wren? [This](http://wren.io/classes.html#metaclasses-and-static-members) page references metaclasses, but i can't find any more info about it besides mentioning. Is it not documented yet or just not implemented? Could metaclasses help me at all, or it's something else?

**Comment by Heaven31415** [comment]
Hey, I can give you a hint about metaclasses, you can find some information about them [here](https://github.com/wren-lang/wren/blob/master/src/optional/wren_opt_meta.wren). Maybe this will help you.

**Comment by mhermier** [comment]
There was quite a number of discussion about that without work being
integrated. There are some limitations in the implementation that forbid
some part of what a mirror API should be to exist. And because of wren
nature, there is no strong need for a mirror API. There is a need for the
sake of completeness, and some corner usage, but because of wren dynamic
nature, delegation and implicit generics reduce the number of use cases.

**Comment by G0BL1N** [comment]
Oh, that's really handy, I didn't know that. That is indeed enough for now.
I'll close this issue, because I got my answer and there's not much discussion anyway. 
Thanks everyone.

**Comment by underscorediscovery** [comment]
I have something like this working in my code based on exposing 2 things to the scripts via `wren_core.c`, if you feel like hacking it in yourself while you wait for this kind of stuff in master, here's a way.

For my purposes initially I added these:
1. System.importModule 
2. System.getModuleVariable

The code for these comes straight from wren [before the new import compiler](https://github.com/wren-lang/wren/commit/8d37b207837036b5b82c50a30b5c9a3fcc8a31c8#diff-dcb6b0b39dab081abcb7497e66762a57L1084).

With these functions you can do what you're asking. Consider this function:

```js
run_module(module) {

  var result = null
  var load = Fiber.new {
    result = System.importModule(module)
  }

  load.try()

  if(!load.error) {
    return { "error":null, "result": result }
  }

  System.print("failed to load `%(module)`\n%(load.error)")

  return { "error": load.error, "result": null }

} //run_module
```

and this usage
```js
var generated = ...
var list = ["Something%(generated)"]
list.each {|item|
  var module = "%(item).wren"
  //import "module" ...
  var res = run_module(module)
  if(res["error"]) return
 //... for "item"
  var type = System.getModuleVariable(module, item)
  var inst = type.new()
}```

You can reintroduce those functions in `meta` or `System` and use them that way to get completely string based imports!

**Comment by underscorediscovery** [comment]
I should add that one of the first new things is the introspection APIs (I'm working toward those atm, been busy).

**Comment by G0BL1N** [comment]
Thanks, that might help! I'm totally in for hacking :)
Will do this if I feel like it.
For now I'm busy embedding wren in Kotlin/Native. It does work flawlessly, I just need to build solid architecture to continue.

**Comment by mhermier** [comment]
While Sven solution is correct and working, I found it under optimal. I
think modules should be first class and that their should be something like
'System.getModuleByName' or 'System.getModuleByURL'.
