### ISSUE TITLE
metaclass does not implement method

### ISSUE THREAD

**Issue by IllusiveS** [wren-lang/wren#681]
I am trying simple methods call from cpp as described in embedding documentation and im running into trouble of it not working
I have this wren script

```
class GameEngine {
    static Create(){
        System.print("Creating engine")
    }

    static Update(elapsedTime) {
        System.print("time elapsed")
    }
}

GameEngine.Create()
```

Steps im doing to achieve it are:
read it from file

```
void WrenWrapper::read_file(const char *filename) {
	std::ifstream t(filename);
	std::string str((std::istreambuf_iterator<char>(t)),
	                std::istreambuf_iterator<char>());
	WrenInterpretResult result = wrenInterpret(vm.get(), "main", str.c_str());
}
```

and later i try to call the thing

```
void WrenWrapper::call_function(const char *module, const char *class_name, const char *function) {
	auto create_function_handle = wrenMakeCallHandle(vm.get(), function);
	wrenEnsureSlots(vm.get(), 1);
	wrenGetVariable(vm.get(), module, class_name, 0);
	WrenHandle* gameEngineClass = wrenGetSlotHandle(vm.get(), 0);
	wrenSetSlotHandle(vm.get(), 0, gameEngineClass);

	auto call_result = wrenCall(vm.get(), create_function_handle);
}
```

result is 
Runtime script error (null):-1 message: GameEngine metaclass does not implement 'Update'.
Are metaclasses not working properly?

**Comment by mhermier** [comment]
Seems it is the wrong method signature, should be 'Update(_)'.

**Comment by munificent** [comment]
@mhermier is right. Wren allows overloading by number of parameters, so the "name" of a method must be a *signature* that includes that information. The way it does that is by having parentheses surrounding comma-separated underscores for each parameter.
