### ISSUE TITLE
Correctly set up https for wren.io

### ISSUE THREAD

**Issue by bjorn** [wren-lang/wren#683]
For https to work correctly on wren.io, the IP addresses of the A records need to be updated.

Current setup:
```
bjorn@thor:~$ dig +noall +answer wren.io
wren.io.		1277	IN	A	192.30.252.154
wren.io.		1277	IN	A	192.30.252.153
```
Required setup [is documented here](https://help.github.com/en/articles/setting-up-an-apex-domain#configuring-a-records-with-your-dns-provider).

The documentation states that after updating the IP addresses, we also need to [remove and then re-add the custom domain to the repository](https://help.github.com/en/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site#adding-or-removing-a-custom-domain), to trigger the process of enabling HTTPS.

I guess only @munificent can perform the DNS changes.

**Comment by munificent** [comment]
Yeah, this is on me. I'll try to take a peek at this when I get a chance.

**Comment by munificent** [comment]
OK, that was a long delay, but I finally got around to this. I set up A records for the four IP addresses listed [here](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain). I think that's all I need to do on the DNS host? Is there anything else?

**Comment by ruby0x1** [comment]
After waiting for the GitHub certificate to issue, https://wren.io is now valid, and I've enforced it as the only option 🎉 Thanks @munificent !

![image](https://user-images.githubusercontent.com/236374/84054125-c6304800-a967-11ea-9149-e77a3d99aea0.png)
