### ISSUE TITLE
wrenGetSlot* doesn't check type and (often) give garbage output on invalid type

### ISSUE THREAD

**Issue by TSnake41** [wren-lang/wren#694]
wrenGetSlot* functions doesn't check type and give invalid/garbage output if the type doesn't correspond to the slot type.
The expected behavior is a error that slot type isn't respected (something like "x type expected, got y").

Considering the following example : 
```wren
class foo {
  foreign static bar(value)
}

foo.bar(42) // This is not a string
```

With the following foreign method : 

```c
void foo_bar(WrenVM *vm)
{
  printf("%s", wrenGetSlotString(vm, 1));
}
```

printf receives a acceptable but invalid char pointer which most of times lead to undefined behavior (mostly crash).

Workarounds of this issue is either to do explicit type checking in foreign method (with wrenGetSlotType) or in wren code with a wrapper that checks the type before using the foreign method which is not optimal performance-wise and makes things complex where they shouldn't be.

**Comment by mhermier** [comment]
Unless you change error handling to setjmp/longjmp, or change the signature
of the methods, there is no other proper way to deal with it in C.

**Comment by minirop** [comment]
The check is only done in debug. 
https://github.com/wren-lang/wren/blob/52c16b4f80c914b571d605a793bf0090b06d678d/src/vm/wren_vm.c#L1630-L1636

I remember an issue where this was discussed and was said:
> use a wren method to call your foreign one wrapped with a "if (value is String)"

**Comment by munificent** [comment]
Yes, this is by design. See the "Performance and safety" section [here](http://wren.io/embedding/). If we put mandatory checking in here, that checking has a performance cost and users that don't need it have no way to opt out of that cost. So the embedding API does the fastest thing it possibly can and leaves it to you to ensure safety.

**Comment by TSnake41** [comment]
I will look around #591 which has features I need as I am pretty concerned about safety _but only in some cases_.
