### ISSUE TITLE
Is negative modulus intended?

### ISSUE THREAD

**Issue by nearlyNonexistent** [wren-lang/wren#695]
-8 % 3
= -2
Another language, such as Lua:
-8 % 3
= 2

Is this intended behavior? I don't see it documented anywhere.

**Comment by minirop** [comment]
under the hood, the function [fmod](https://en.cppreference.com/w/c/numeric/math/fmod) is used.
`The returned value has the same sign as x`

**Comment by bjorn** [comment]
> Another language, such as Lua:
> -8 % 3
> = 2

I guess you meant `-8 % 3 = 1`. Both are valid remainders, with the multiplier being `-3*3+1=-8` in Lua's case and `-2*3-2=-8` in fmod's case.
