### ISSUE TITLE
Calling wrenAbortFiber during foreign class allocation does not abort the fiber

### ISSUE THREAD

**Issue by matusnovak** [wren-lang/wren#697]
### Basic working example

I have a C++ class that I am using in Wren. This is the following code I am using to allocate it:

```cpp
void allocateFoo(WrenVM* vm) {
    auto* memory = wrenSetSlotNewForeign(vm, 0, 0, sizeof(Foo));
    new (memory) Foo();
}

...

WrenForeignClassMethods methods;
methods.allocator = allocateFoo;
```

Wren code:

```js
var foo = Foo.new()
```

### The problem

Nothing special so far, but what if **Foo throws an exception** from its **constructor**? I am trying to wrap it in a try/catch statement and then simply using `wrenAbortFiber` as so:

```cpp
void allocateFoo(WrenVM* vm) {
    auto* memory = wrenSetSlotNewForeign(vm, 0, 0, sizeof(Foo));
    try {
        new (memory) Foo();
    } catch (std::exception& e) {
        wrenEnsureSlots(vm, 1);
        wrenSetSlotString(vm, 0, e.what());
        wrenAbortFiber(vm, 0);
    }
}
```

The following try/catch with `wrenAbortFiber` **works when calling a foreign method** from Wren. I will get handled gracefully and I will get the exception message in the `WrenErrorFn` functiom. But it **does not work when allocating a foreign C++ class**.

Instead, I will get:

```
String does not implement 'init new()'
```

I assume Wren is trying to call `init new()` on the the string that should have been handled by wrenAbortFiber.

Am I doing it wrong?

### The bad workaround

As a workaround, when an exception is thrown when calling the C++ constructor, I am setting the slot to null as: `wrenSetSlotNull(vm, 0);`. Then, I am simply using a custom `WrenErrorFn` callback which has a "next error" string. So when an exception is caught, the message will get stored as the "next error" variable, and this will get picked up by the custom `WrenErrorFn` callback. A horrible workaround but it works for me.

**Comment by mhermier** [comment]
What is the Foo class in your wren code?

**Comment by matusnovak** [comment]
@mhermier That's just a random class. It does not have to be anything specific. The problem is with `wrenAbortFiber`.

**Comment by mhermier** [comment]
The problem report that the class don't have a new, so the problem is in
the class

**Comment by matusnovak** [comment]
@mhermier If my class is missing new, the `allocateFoo` (part of `WrenForeignClassMethods`) would not get executed at all. That's not the case. It's being called from here: https://github.com/wren-lang/wren/blob/master/src/vm/wren_vm.c#L630 (Stack trace: `wrenCall` -> `runInterpreter` -> `createForeign` -> `allocateFoo`)

If I add `wrenSetSlotNull(vm, 0);`, as shown below, before calling `wrenAbortFiber` I will get:

```
Null does not implement 'init new()'
```

The modified code:

```cpp
void allocateFoo(WrenVM* vm) {
    auto* memory = wrenSetSlotNewForeign(vm, 0, 0, sizeof(Foo));
    try {
        new (memory) Foo();
    } catch (std::exception& e) {
        wrenSetSlotNull(vm, 0); // <- this
        wrenEnsureSlots(vm, 1);
        wrenSetSlotString(vm, 0, e.what());
        wrenAbortFiber(vm, 0);
    }
}
```

Which means, the `wrenAbortFiber` has no effect, and Wren continues script execution as normal.

**Comment by mhermier** [comment]
Seems that we forgot to check for a errors after returning 
'createForeign' at 
https://github.com/wren-lang/wren/blob/master/src/vm/wren_vm.c#L1200

Please try to add 'if (wrenHasError(fiber)) RUNTIME_ERROR();' before 
dispatch.

**Comment by matusnovak** [comment]
@mhermier That does fix the problem, I have created a PR and added a test -> https://github.com/wren-lang/wren/pull/698

**Comment by minirop** [comment]
just for your info, placement new are declared noexcept so throwing an exception is undefined behaviour.

**Comment by mhermier** [comment]
Do you have some pointers to that? The only reference I found is that the
default allocator does no throw indeed since it has nothing to do, but it
doesn't state that constructor of class should not throw in this case. Even
the c++ guidelines says that the constructor should throws in case of error
since it is the only way of communication. Thought maybe there is a no
garantee of ressource deallocation that can trigger the undefined behavior,
but I'm not sure about that.

**Comment by minirop** [comment]
if you look the ISO draft section `[support.dynamic]`, not all operator new are noexcept, and here, I'm not sure which one will be used, but there is:
```
[[nodiscard]] void* operator new  (std::size_t size, void* ptr) noexcept;
```

**Comment by mhermier** [comment]
My understanding of, is that people mix the construction part and the
initialisation of it. [support.dynamic] explicit what are the memory
initialiser part of the constructor. And instead when you use a placement
new there is no memory allocation, so there is no sane way construction of
memory would/should throw since it was given by the user. My guess is that
it can be overloaded to memset the memory with some 0 or random pattern to
see if the memory was properly initialised. But that concerns only the
allocation part of creating an object. Then the 'new' call to tries to
initialised the object by calling the constructor method, and that part is
user defined and can throw.

**Comment by matusnovak** [comment]
Adding to the comments above: The allocation of the memory holder for the foreign class happens via [wrenSetSlotNewForeign](https://github.com/wren-lang/wren/blob/master/src/vm/wren_vm.c#L1668) -> [wrenNewForeign](https://github.com/wren-lang/wren/blob/master/src/vm/wren_value.c#L233) -> [ALLOCATE_FLEX](https://github.com/wren-lang/wren/blob/master/src/vm/wren_common.h#L122) -> [wrenReallocate](https://github.com/wren-lang/wren/blob/master/src/vm/wren_vm.c#L199) which is the heap memory Wren uses for dynamic allocations, so this memory gets freed once Wren frees. No memory leaks at all. [It is also being set to 0s](https://github.com/wren-lang/wren/blob/master/src/vm/wren_value.c#L239).

The constructor during an exception is handled by C++, I do not see a problem there as it is handled gracefully by C++ itself. 

When the exception gets caught and the error gets reported to Wren ([the pull requests ensures that wrenAbortFiber works correctly](https://github.com/wren-lang/wren/pull/698)) the Wren will also call the finalize class method automatically. So depending on the custom implementation inside of the allocate class method, you can easily check for any extra memory you might have had allocated.

In my own implementation, I use an extra class wrapper `ForeignObject<T>` and my allocation and finalize methods look like this:

```cpp
static void allocate(WrenVM* vm) {
    auto* memory = wrenSetSlotNewForeign(vm, 0, 0, sizeof(ForeignObject<T>));
    new (memory) ForeignObject<T>();
    auto* wrapper = reinterpret_cast<ForeignObject<T>*>(memory);
    try {
        wrapper->ptr.reset(new T(... get slots ...)); // std::shared_ptr<T>
    } catch (std::exception& e) {
        wrenEnsureSlots(vm, 1);
        wrenSetSlotString(vm, 0, e.what());
        wrenAbortFiber(vm, 0);
    }
}
static void finalize(void* memory) {
    auto* wrapper = reinterpret_cast<ForeignObject<T>*>(memory);
    wrapper->~ForeignObject<T>();
}
```

Also tested via Valgrind, no memory corruption.

The reason for this issue is because I am working on a C++17 binding library for Wren: https://github.com/matusnovak/wrenbind17

The fix has been resolved and merged -> https://github.com/wren-lang/wren/pull/698 so I will close this issue.

Thank you all.
