### ISSUE TITLE
Documentation typo on wren.io

### ISSUE THREAD

**Issue by gkjpettet** [wren-lang/wren#702]
Hi, I'm not sure where best to report this. There's a typo on the _Functions_ documentation page at [http://wren.io/functions.html](url). In the _Function Parameters_ section, it reads:

> Here we’re passing a function to `greet` that takes two parameters, `first` and `last`. They are passed to the function when it’s called:

I think it should be:

> Here we’re passing a function to **`callMe`** that takes two parameters, `first` and `last`. They are passed to the function when it’s called:

**Comment by mwilmsm** [comment]
https://github.com/wren-lang/wren/pull/703 Made a pull request for this.

**Comment by underscorediscovery** [comment]
Thanks for the report and the PR!
