### ISSUE TITLE
Building wren without building libuv

### ISSUE THREAD

**Issue by cinerea0** [wren-lang/wren#705]
Currently, it is impossible to build wren without also building a local copy of libuv unless `wren.mk` is altered substantially. This makes packaging wren for Linux distributions difficult because the build process relies on libuv's complicated build process. In the short term, I'm looking for some guidance as to what parts of `wren.mk` need to be changed/deleted so wren can be built against a system-wide installation of libuv. In the long term, I think it would be a good idea to modify the makefile so that options can be passed to it to determine whether wren should be built against a local or system-wide version of libuv.

**Comment by mhermier** [comment]
Better solution would be to wait for 0.3.0 and the cli split. In addition,
at long term it will be necessary to choose <insert your loved makefile
generator here> to support compilation on shorted platforms.

**Comment by underscorediscovery** [comment]
Yea the refactoring in [0.3.0](http://wren.io/blog/0.2.0-and-beyond.html) will make the process a lot simpler.

**Comment by cinerea0** [comment]
Wonderful! I read the blog post you linked, and I like every bit of news in there. One question: is there a timeline as to approximately when 0.3.0 will be released?

**Comment by underscorediscovery** [comment]
No timeline currently, but I don't expect it to take too long.
