### ISSUE TITLE
wrenEnsureSlots for more than slots than arguments in foreign allocate method causes errors

### ISSUE THREAD

**Issue by avivbeeri** [wren-lang/wren#707]
If you try to execute `wrenEnsureSlots` in the allocate C method of a foreign class, and try to ensure n+2 slots, where n is the number of arguments to the constructor method, Wren seems to lose track of what the original class object is, resulting in runtime errors.

Minimal example:
[test.txt](https://gist.github.com/avivbeeri/786405c5d4a1247b3af29797514b10b2)

**Comment by mhermier** [comment]
Known issue, using wrenEnsureSlots inside a foreign is broken in many ways.

**Comment by avivbeeri** [comment]
Do you know if it is it likely to be improved some time soon, and whether there's a workaround for the meantime?

**Comment by mhermier** [comment]
There is no ETA, for now I'm waiting for the 0.3.0 and it's cli/vm split
before considering submitting stuff again.

**Comment by avivbeeri** [comment]
So others know, if you call `wrenEnsureSlots` before the wrenCall function to allocate the maximum slots you'll need, it will keep the slots allocated when it calls back into C code. 

Just don't call `wrenEnsureSlots` in your foreign class allocator afterwards and you shouldn't have any problems.
