### ISSUE TITLE
Why can't Wren output a quote?

### ISSUE THREAD

**Issue by myu-sername** [wren-lang/wren#708]
It is very weird that Wren is incapable of outputting a double-quote. This is what I tried:
```
System.print("\"")
```
This outputs nothing. Same as this program:
```
System.print(String.fromCodePoint(34))
```
The above program works for any other value, e.g. the exclamation mark:
```
System.print(String.fromCodePoint(33))
```
So can anyone explain what is causing Wren to be incapable of outputting a double-quote? (Fixing this will potentially allow a quine program to be possible.)

**Comment by myu-sername** [comment]
Now it is working...

**Comment by mhermier** [comment]
For the reference, what was the issue? User bug?

**Comment by bjorn** [comment]
@mhermier The post was edited, but you can still access the original contents by clicking on the "edited" text and viewing the diff.

@myu-sername It's really better to just write another reply than editing your original message in such a case. Also, it's always nice to hear about what could have led to the problem or the confusion, even if there was nothing to fix in the end.

**Comment by mhermier** [comment]
My emails were not edited ;) so I was really asking for the origins of the
confusion, not about the original report.
