### ISSUE TITLE
Some methods of String don't work in the online interpreter

### ISSUE THREAD

**Issue by myu-sername** [wren-lang/wren#709]
When I tried the following program
```
System.write(String.fromByte(34))
```
in the [Wren online interpreter](http://ppvk.github.io/wren-nest/), it says the following:
```
String metaclass does not implement 'fromByte(_)'. | (null):-1
(script) | main:1
```
I am absolutely sure that this is in the [documentation](http://wren.io/modules/core/string.html#string.frombyte(byte)).

**Comment by myu-sername** [comment]
Also [```.replace()```](http://wren.io/modules/core/string.html#replace(old,-swap)) doesn't work too:
```
System.write("1212".replace("21","x"))
```

**Comment by minirop** [comment]
the Wren online interpreter hasn't been updated since november 2016, whilst `System.fromByte` has been added on Feb 27, 2019.

as for `String.replace`, I don't find any instance in the source code, but there are tests for it. :thinking:

**Comment by bjorn** [comment]
Issues for the online interpreter should be reported at https://github.com/ppvk/wren-nest.

**Comment by underscorediscovery** [comment]
And worth noting, [as discussed here](http://wren.io/blog/0.2.0-and-beyond.html) that we're working on a new automated web build that will give the site live examples and a more up to date interpreter.
