### ISSUE TITLE
Calling wrenEnsureSlots before wrenInterpret causes apiStack to become invalid

### ISSUE THREAD

**Issue by liquid600pgm** [wren-lang/wren#710]
## Description

```c
WrenConfiguration config;
wrenInitConfiguration(&config);
WrenVM *vm = wrenNewVM(&config);

/* let's allocate some slots for later use */
wrenEnsureSlots(vm, 32);

/* then, let's execute a Wren script */
wrenInterpret(vm, "main", myScript);

/* now, however, we face a problem: while the fiber's stack got updated,
   the API stack (aka slot array) didn't, so we're stuck with the old slots that
   got allocated during the first wrenEnsureSlots call */
```
Calling `wrenEnsureSlots` at this point will not yield any effect, because of how slots are ensured:

```c
void wrenEnsureSlots(WrenVM* vm, int numSlots)
{
  // If we don't have a fiber accessible, create one for the API to use.
  if (vm->apiStack == NULL) /* ← problematic line */
  {
    vm->fiber = wrenNewFiber(vm, NULL);
    vm->apiStack = vm->fiber->stack;
  }
  
  int currentSize = (int)(vm->fiber->stackTop - vm->apiStack);
  if (currentSize >= numSlots) return;
  
  // Grow the stack if needed.
  int needed = (int)(vm->apiStack - vm->fiber->stack) + numSlots;
  wrenEnsureStack(vm, vm->fiber, needed);
  
  vm->fiber->stackTop = vm->apiStack + numSlots;
}
```
In this case, `vm->apiStack` is not null, but `vm->fiber->stack` is also a completely different stack than `vm->apiStack`. Updating `vm->apiStack` through `wrenSetSlotT` calls will not have any effect, because internally, these functions update `vm->apiStack`, which now points to some unrelated stack.

That by itself wouldn't be a problem, unless we try and `wrenCall` a method:
```c
wrenEnsureSlots(vm, 1);
wrenGetVariable(vm, "main", "MyClass", 0);
/* ↑ will succeed and get us the correct variable */
WrenHandle *class_MyClass = wrenGetSlotHandle(vm, 0);
WrenHandle *method_doThings = wrenMakeCallHandle("doThings()");

wrenSetSlotHandle(vm, 0, class_MyClass);
/* ↑ will trigger a bug, because the old stack is used */
WrenInterpretResult result = wrenCall(vm, method_doThings); /* uh oh! */
/* the above call will fail, because we updated the old stack instead of the new one.
   the VM will try to read from the new stack, and the value read is `null`,
   which causes the call to fail unexpectedly. */
```

## Possible fix
I'm no expert at the internals of the VM, but I feel like a simple `vm->apiSlots` update at the end of `wrenInterpret` would do the job just fine. The overhead would be practically unnoticable, so it wouldn't matter much.

If it's not possible to update `vm->apiSlots` with a correct value, we can at least invalidate it by setting `vm->apiSlots = NULL;`, which would cause subsequent `wrenEnsureSlots` calls to allocate a new stack and use it in any VM invocations. But as I said, I am no expert, so I don't know if it would even work.

**Comment by kawa-yoiko** [comment]
A viable solution is to invalidate by setting both `vm->fiber` and `vm->apiStack` to NULL (fiber needs to be NULL as well, or subsequent calls may still fail). No worries about memory leaks — the finished fiber is garbage collected, as can be confirmed by logging inside `wrenFreeObj()`. I do not have Valgrind on macOS, but Apple's Leaks instrument reported no issue.

Other ways to update the stack cause problems under various scenarios including multiple `wrenInterpret()` calls, foreign calls from inside `wrenInterpret()` etc. and I didn't attempt in those ways. I have made a new PR #730 with a test, and it would be great if you can help verify it and possibly suggest more test cases. (Tests that live in `test/api` together form an executable, which can be built by `make api_test` and run by `build/debug/test/api_wrend test/api/<file>.wren`, or `make test` together with all other tests.)

Cheers

**Comment by liquid600pgm** [comment]
Thanks for looking into this. As far as I can tell, your PR covers all the cases I would expect. I already tried fixing the issue in #712, but since your PR is more robust and includes a test case, I'll close mine.

I'll think of more test cases later.

**Comment by underscorediscovery** [comment]
Thanks @kawa-yoiko and @liquid600pgm this is looking good. I've tagged the PR for 0.4.0, I'm close to wrapping up the 0.3.0 refactoring stuff and then we can merge these in.
