### ISSUE TITLE
High memory usage in binary_trees.wren

### ISSUE THREAD

**Issue by mingodad** [wren-lang/wren#721]
Hello !
After cloning and checking "binary_trees.wren" wren is faster than LUA but using 10 times more memory, is this expected ?
```
/usr/bin/time lua binary_trees.lua 
stretch tree of depth 13 check: -1
8192 trees of depth 4 check: -8192
2048 trees of depth 6 check: -2048
512 trees of depth 8 check: -512
128 trees of depth 10 check: -128
32 trees of depth 12 check: -32
long lived tree of depth 12 check: -1
elapsed: 0.36843600
0.36user 0.00system 0:00.37elapsed 100%CPU (0avgtext+0avgdata 8836maxresident)k
0inputs+0outputs (0major+1554minor)pagefaults 0swaps
```
```
/usr/bin/time ../../bin/wren binary_trees.wren 
stretch tree of depth 13 check: -1
8192 trees of depth 4 check: -8192
2048 trees of depth 6 check: -2048
512 trees of depth 8 check: -512
128 trees of depth 10 check: -128
32 trees of depth 12 check: -32
long lived tree of depth 12 check: -1
elapsed: 0.240065
0.24user 0.02system 0:00.26elapsed 99%CPU (0avgtext+0avgdata 85532maxresident)k
0inputs+0outputs (0major+20841minor)pagefaults 0swaps
```
Cheers !

**Comment by mhermier** [comment]
Yes that is to be expected as it higly depends on garbage collection 
strategies. If you run the gc version you'll see something like:

```

/usr/bin/time ./wren test/benchmark/binary_trees_gc.wren
stretch tree of depth 13 check: -1
8192 trees of depth 4 check: -8192
2048 trees of depth 6 check: -2048
512 trees of depth 8 check: -512
128 trees of depth 10 check: -128
32 trees of depth 12 check: -32
long lived tree of depth 12 check: -1
elapsed: 1.443956
1.44user 0.00system 0:01.44elapsed 99%CPU (0avgtext+0avgdata 
3892maxresident)k
0inputs+0outputs (0major+451minor)pagefaults 0swaps

```

where maxresident is using 2 times less memory than lua, so it highly 
depends on how the gc threshold is tuned.

**Comment by mingodad** [comment]
Hello Michel !
Somehow I didn't saw the gc version.
Testing it myself I noticed that there is several calls like this:
```
for (i in 1...1000) System.gc()
```
Replacing then by just:
```
System.gc()
```
Gives a lot better result in terms of time spent and with the same memory usage.
Why have that "for" loop ?
```
/usr/bin/time ../../bin/wren binary_trees_gc.wren 
stretch tree of depth 13 check: -1
8192 trees of depth 4 check: -8192
2048 trees of depth 6 check: -2048
512 trees of depth 8 check: -512
128 trees of depth 10 check: -128
32 trees of depth 12 check: -32
long lived tree of depth 12 check: -1
elapsed: 1.253068
1.25user 0.00system 0:01.25elapsed 99%CPU (0avgtext+0avgdata 3996maxresident)k
0inputs+0outputs (0major+445minor)pagefaults 0swaps
```
```
/usr/bin/time ../../bin/wren binary_trees_gc2.wren 
stretch tree of depth 13 check: -1
8192 trees of depth 4 check: -8192
2048 trees of depth 6 check: -2048
512 trees of depth 8 check: -512
128 trees of depth 10 check: -128
32 trees of depth 12 check: -32
long lived tree of depth 12 check: -1
elapsed: 0.239261
0.23user 0.00system 0:00.24elapsed 99%CPU (0avgtext+0avgdata 3948maxresident)k
0inputs+0outputs (0major+446minor)pagefaults 0swaps
```

Cheers !

**Comment by mhermier** [comment]
A quick git blame search seems to emphasis that this test is in fact 
testing the garbage collection costs and not about performance.

Since the binary tree test produce a huge set of data for *cheap* it is 
reasonable to use it to test the performance/cost of the garbage 
collection on it.

**Comment by mingodad** [comment]
Hello Michel !

If that's the case then probably state that in the comments inside the script could help future users to understand the intended "use case".

And after your explanations I'm in doubt about the effectiveness of wren garbage collection because on this example "binary_trees_gc.wren" compared with LUA where without any extra effort by the end user LUA manages to maintain a lower memory usage compared to wren.

Cheers !

**Comment by mhermier** [comment]
Well for every garbage collector you can't compare apple to apple. 2
language/vm/ implementation can use different strategies.

Wren gc performs well, in the sense that it doesn't crash, and produce
expected results. We can always discuss about the threshold function being
a little bit to much optimistic, but it is a choice that every gc
implementation has to deal with. And nothing prevent one to either tune the
threshold numbers or even change the behavior completely, and compact more
frequently.

**Comment by mingodad** [comment]
Hello Michel !

Thank you for you explanation !

LUA exposes to end users some way to adjust the garbage collection behavior, I looked at the wren documentation and didn't found anything other than "System.gc()".

There is any undocumented options in wren to tune the garbage collector ?

Cheers !

**Comment by mhermier** [comment]
For now, you need to look into the code. There are some magic
numbers/defines that should live in wren_values.c. Can't look at the code
currently to be more precise.

**Comment by mingodad** [comment]
Hello Michel !
I found this in wren_vm.c
```
void wrenInitConfiguration(WrenConfiguration* config)
{
  config->reallocateFn = defaultReallocate;
  config->resolveModuleFn = NULL;
  config->loadModuleFn = NULL;
  config->bindForeignMethodFn = NULL;
  config->bindForeignClassFn = NULL;
  config->writeFn = NULL;
  config->errorFn = NULL;
  config->initialHeapSize = 1024 * 1024 * 10;
  config->minHeapSize = 1024 * 1024;
  config->heapGrowthPercent = 50;
  config->userData = NULL;
}
```
And changing heapGrowthPercent to 15 or and initialHeapSize to 2MB does not trigger the garbage collector when running "binary_trees_gc.wren".
Cheers !

**Comment by mhermier** [comment]
src/cli/vm.c override the default configuration you tried to alter to
100Mo. Try to update values there instead. And as the comment say:
'''
Since we're running in a standalone process, be generous with memory.
'''
This might explain it all.

**Comment by mingodad** [comment]
Hello Michel !

Thank you again, that was it, I changed it to 4MB and the peak memory now is 7.8MB.

Cheers !
