### ISSUE TITLE
Unsupported platform:  FreeBSD

### ISSUE THREAD

**Issue by darkoverlordofdata** [wren-lang/wren#722]
Doen't make on bsd:

darko@NomadBSD:~/GitHub/wren] gmake
gmake[1]: Entering directory '/home/darko/GitHub/wren'
        cc src/optional/wren_opt_random.c  -O3 -std=c99 -fPIC
        cc src/optional/wren_opt_meta.c    -O3 -std=c99 -fPIC
        cc src/vm/wren_primitive.c         -O3 -std=c99 -fPIC
        cc src/vm/wren_vm.c                -O3 -std=c99 -fPIC
        cc src/vm/wren_debug.c             -O3 -std=c99 -fPIC
        cc src/vm/wren_value.c             -O3 -std=c99 -fPIC
        cc src/vm/wren_core.c              -O3 -std=c99 -fPIC
        cc src/vm/wren_compiler.c          -O3 -std=c99 -fPIC
        cc src/vm/wren_utils.c             -O3 -std=c99 -fPIC
        cc lib/libwren.so                  -O3 -std=c99 -fPIC -Wl,-soname,libwren.so
        ar lib/libwren.a                  rcu
       run util/build_libuv.py            
Unsupported platform: FreeBSD
gmake[1]: *** [util/wren.mk:242: build/libuv.a] Error 1
gmake[1]: Leaving directory '/home/darko/GitHub/wren'
gmake: *** [Makefile:16: release] Error 2

**Comment by darkoverlordofdata** [comment]
I was able to fix the build - see https://github.com/darkoverlordofdata/wren

Do you want a pull?

**Comment by maxdeviant** [comment]
@darkoverlordofdata I don't see a reason why a fix wouldn't be accepted. Never hurts to make a PR 😄

**Comment by darkoverlordofdata** [comment]
Ok, I sent it. Thanks!
