### ISSUE TITLE
No print output when following embedding example in documentation

### ISSUE THREAD

**Issue by benob** [wren-lang/wren#728]
The embedding example in the documentation suggests to run the code "System.print(\"I am running in a VM!\")" which does not print anything because the vm was not configured with a print function.

Suggesting the user to provide a print/error function would make things clearer.

**Comment by avivbeeri** [comment]
You make a very good point here, this could be clearer. There's a link in that section to the explanation of VM configuration, but it'd be nice if it worked first time.

The example should either:
1) Include a write/error function
2) Mention the caveat that the function is required, or 
3) Wren should include a default write/error handler which prints to the stdout.

**Comment by ruby0x1** [comment]
I’ve made the docs clearer about this, thanks!
