### ISSUE TITLE
Thread safety of a VM?

### ISSUE THREAD

**Issue by natinusala** [wren-lang/wren#732]
Is a Wren VM thread safe? Can I call multiple Wren methods from multiple C threads at the same time without synchronizing them, or should I put a lock on the whole VM each time I do something?

I would expect the answer to be no but it doesn't hurt to ask

**Comment by liquid600pgm** [comment]
The VM is not thread safe, you need to create a new instance for each thread.

**Comment by natinusala** [comment]
Okay thanks for the answer. Can't I just use a lock each time I want to access the VM? Or will it blow up if called from different threads even when synchronized?

**Comment by avivbeeri** [comment]
That may work. You would have to ensure that only one thread is handling the VM execution at any given time. Depending on what you are doing, you may want to consider different architectures to get to the same result

**Comment by underscorediscovery** [comment]
each VM is isolated and therefore thread safe from other VMs, but a VM on it's own is not thread safe. I'd consider also the re-entrancy concerns, as it sounds like it would quickly run into that when trying to use threads on the same VM.

**Comment by natinusala** [comment]
The use case is to add scripting support to RetroArch, a multi emulator frontend. The program has two threads, the main thread (main loop) and the video thread (OpenGL stuff). 

For modules to draw things onscreen they need to be called from both threads (main thread to update, video thread to draw). Calling video stuff from the main thread is not possible

**Comment by liquid600pgm** [comment]
You may want to use a channel to send commands from the main thread (where your Wren instance runs) to the video thread, but I'm not really sure if that's viable in your case. I'm just throwing ideas around.

**Comment by natinusala** [comment]
Yeah I'd better find another solution since synchronizing the whole VM will probably slow everything down dramatically.

Sending drawing commands from the main thread will need serializing and storing them in the C code... That's not so bad I suppose

However I fear like RetroArch has more stuff running in the video thread than drawing commands so it might not be enough... I'll check

**Comment by bjorn** [comment]
Since apparently RetroArch modules in general already have an update and a draw phase, as long as they are guaranteed to not happen at the same time (which I hope is the case, otherwise each module would have to cope with threading issues), you should already be on the safe side. But you need to make sure of course.

**Comment by natinusala** [comment]
Well the issue is that they are not synchronized... When writing the current menu widgets I had to manually synchronize every component

**Comment by bjorn** [comment]
Hmm, that's too bad. It may be worth considering whether this is something to fix on the RetroArch side, or whether there is really some advantage from calling the module update and draw functions concurrently.

**Comment by natinusala** [comment]
It's hardly possible, my only hope is to identify what runs on the video 
thread and manually synchronize them

**Comment by pyway** [comment]
make few changes to WrenVM struct, then create a new VM, and run wrenCall in threading function.
it looks good. (i have done).
