### ISSUE TITLE
Is it ok to hold on to a pointer returned by wrenGetSlotForeign?

### ISSUE THREAD

**Issue by mode777** [wren-lang/wren#734]
Hey everyone!

I'm new to Wren and so far it has been a blast to work with. 

However, I was wondering if it is ok to store a pointer to C data from obtained from Wren.

Consider this example. I previously stored a struct PGLGeometryBuffer in Wren C Data. I want to store a pointer to this struct for later use:
```c
PGLAttribute* attribute = calloc(1, sizeof(PGLAttribute));
attribute->buffer = (PGLGeometryBuffer*)wrenGetSlotForeign(vm, 1);
```
My question: Will this pointer stay valid until finalize is called or is it possible that the wren garbage collector will move my C Data around?

**Comment by mhermier** [comment]
Objects are never moved in current implementation, since it would require
updating all the objects. So pointers should always be valid till the
object is gc.

Thought I'm not sure it might not be wiser to let C manage the memory, and
make wren objects do the proxing to the data. But it depends what you are
doing.

**Comment by avivbeeri** [comment]
The memory for the foreign classes is entirely at the whim of the garbage collector, so if you absolutely have to hold onto it, either hold a reference to it in a cache or create a handle to free later.

**Comment by mode777** [comment]
Thanks a lot for the swift replies. I guess it is safer to assume that the data might be moved even if the current implementation doesn't. 
What I'm gonna do is storing a pointer to a pointer and do the actual struct allocation myself.
```c
attribute->buffer = *(PGLGeometryBuffer**)wrenGetSlotForeign(vm, 1);
```

**Comment by mhermier** [comment]
Do you control PGL* symbols? If so also do:
attribute->handle = wrenGetSlotHandle(vm, 1);
And release it at destruction of the attribute.

**Comment by underscorediscovery** [comment]
Just to add my thoughts I agree the safest is not to hold pointers to memory you don't own without a guarantee. In this case there is no guarantee :)

**Comment by avivbeeri** [comment]
So in the intended API, you are supposed to get a WrenHandle from the VM
for any objects you want to keep, but there isn't a good timing hook for
releasing that handle during class finalize, because you don't get full
access to the VM. Something to consider for future versions.

**Comment by mode777** [comment]
@mhermier And I could use that handle to get a pointer to the actual data right? Still this would leak Wren implementation details to my non-scripting aware classes. Additionally @avivbeeri's issue remains.

What while I'm doing this this: `attribute->buffer = *(PGLGeometryBuffer**)wrenGetSlotForeign(vm, 1);` 
PGLAttribute and PGLGeometryBuffer are both C Data representations of Wren foreign classes Attribute and GeometryBuffer accordingly.
So now PGLAttribute is referencing PGLGeometryBuffer. If I replicate this dependency on the Wren side, like this:
```
foreign class Attribute {
  construct new(geometryBuffer, attributeType, componentType, componentCount, offset, normalized){
    // keep reference for garbage collector
    _geometryBuffer = geometryBuffer
  }
}
``` 
Wren will reference count my PGLGeometryBuffer for me - No need to get a handle.

Does this sound like a sound strategy?

@underscorediscovery Jep, sounds like a good general rule to follow

@avivbeeri Yeah, it's strange that you don't get a pointer to WrenVM in the finalize hook. You can store a pointer in the actual C data but it feels wrong.

PS: I didn't expect to get so much response for a relatively small project like Wren. You guys are great!!

**Comment by avivbeeri** [comment]
You don't get VM access for a good reason: Finalize is called mid-garbage-collection, so the VM isn't in stable state. But the downside is that you can't do some memory/garbage collection related activities.

You could just keep a list of WrenHandles in your application and mark them for releasing, and periodically check? Depending on your application type.

**Comment by mode777** [comment]
@avivbeeri Thanks for pointing it out. I just learned the hard way that foreign classes can't have members. That combined with the inability to release handles during finalizing makes it really hard to build up graphs of foreign classes.
Well, it's back to the drawing board for me....

**Comment by mhermier** [comment]
I guess you have lifetime issue. Designing a binding API is not an easy
task, if you try to do it too much wise. Usually the more dumb it is, the
less problem it can trigger.

**Comment by mode777** [comment]
The more I learn the more I see this is true. I was always puzzled why OpenGL has such a verbose and contracted API. Now I can understand some of choices.

Well in my case I solved the dependencies between struct with manual reference counting implemented on the C side. 

```c
typedef struct {
  GLsizei stride;
  GLuint handle;
  int refCount;
} PGLGeometryBuffer;
```
Each time a Wren allocation references the buffer `refCount` is incremented.  In the finalize call the count is decreased - once it reaches 0 the (OpenGL) handle and struct memory is freed.

**Comment by mhermier** [comment]
In the case of opengl it is more an implementation language decision. If
you compare it to DirectX, it is also pretty dumb, but because of the
object oriented nature of the implementation each time you augment the
feature, you have to recompile the client. OpenGL uses the proven API ideas
from unix/POSIX which demonstrated how easy extensible it is contrary to
object orientation.

If you look at the development of c++ since c++11 it is more and more
apparent maintainers go back functionnal, because pure object has some
fundamental maintenance issues and hidden costs.
