### ISSUE TITLE
UTF-16 and emoji count support

### ISSUE THREAD

**Issue by clsource** [wren-lang/wren#735]
According to the docs every string is UTF-8 in *Wren*.
So currently we can do the following count operations using unicode strings.

```js
System.print("👨‍👩‍👧‍👦".count)  // Count Unicode Scalars. Return 7.
System.print("👨‍👩‍👧‍👦".bytes.count)  // Count UTF-8 code Units. Return 25.
```

But UTF-16 and Single Unit string count may be missing.
So this is a syntax proposal.

```js
System.print("👨‍👩‍👧‍👦".utf8.count) // Count UTF-8 Code Units. Return 25. The same as bytes (alias), just to be similar to utf16.
System.print("👨‍👩‍👧‍👦".utf16.count) // Count UTF-16 Code Units. Return 11.
System.print("👨‍👩‍👧‍👦".length) // Count as Single Character. Return 1.
```

An example of how `Swift` counts unicode strings.

https://www.objc.io/blog/2017/12/19/decomposing-emoji/

**Comment by clsource** [comment]
Closed as this maybe out of scope for the core language. Maybe an external string lib could handle those utf16 and length requirements?

**Comment by clsource** [comment]
Found some arguments from http://utf8everywhere.org/

The string length() operation must count user-perceived or coded characters. If not, it does not support Unicode properly.

Unicode support of libraries and programming languages is frequently judged by the value returned for the ‘length of the string’ operation. According to this evaluation of Unicode support, most popular languages, such as C#, Java, and even the ICU itself, would not support Unicode. For example, the length of the one character string ‘🐨’ will be often reported to be 2 where UTF-16 is used as for the internal string representation and 4 for the languages that internally use UTF-8. The source of the misconception is that the specification of these languages use the word ‘character’ to mean a code unit, while the programmer expects it to be something else.

That said, the code unit count returned by those APIs is of the highest practical importance. When writing a UTF-8 string to a file, it is the length in bytes which is important. Counting any other type of ‘characters’ is, on the other hand, not very helpful.

**Comment by bjorn** [comment]
Let's include a link to the relevant documentation:

http://wren.io/modules/core/string.html

And for [String.count](http://wren.io/modules/core/string.html#count):

> Returns the number of code points in the string. Since UTF-8 is a variable-length encoding, this requires iterating over the entire string, which is relatively slow.

I guess "Unicode code point" is a synonym of "Unicode scalars"?

Personally I think it would be interesting to add a `characters` iterator and `characterCount` getter, but I don't really see the point of dealing with UTF-16.

**Comment by mhermier** [comment]
While the ideas are interesting (and I would prefer to have these behavior)
original implementor designed the language to have strings to be more like
python strings. Meaning that strings are just a bunch of bytes, that are
tried to be decoded as utf8. It was done so it simplify
implementation/language, so there is no need to have an extra byte array
container.

**Comment by clsource** [comment]
@bjorn I believe that unicode scalars is referred to the number of chars that the emoji needs to be build (in the case of the family emoji is father + union char + mother + union char + childA + union char + childB = 7 chars). code point on the other hand refers to the bytes used in the encoding of the string (25 bytes for the family emoji).

@mhermier I agree. Wren is fine as is it now. Maybe a lib with ICU functions could be created as an optional extension :)

**Comment by bjorn** [comment]
> code point on the other hand refers to the bytes used in the encoding of the string (25 bytes for the family emoji).

Well, [code points](https://en.wikipedia.org/wiki/Code_point) are definitely not bytes. I've found [the answer on SO](https://stackoverflow.com/questions/48465265/what-is-the-difference-between-unicode-code-points-and-unicode-scalars):

> D76 **Unicode scalar value**: Any Unicode code point except high-surrogate and low-surrogate code points. 

And it adds that for UTF-8 there is no difference because surrogate pairs are only used by UTF-16

**Comment by clsource** [comment]
Thanks for your clarification 😄  I will post a link to the unicode dictionary too, for completeness https://www.unicode.org/glossary/#unicode_scalar_value 

So right now i'm not sure enough the main difference on why `count` and `bytes.count` return different values.

**Comment by liquid600pgm** [comment]
@clsource Normally, String operations operate on Unicode characters. `bytes` returns a Sequence that operates on individual bytes (C `char`s), so that Strings can be used to store binary data.

**Comment by mhermier** [comment]
There is at least one issue that should be dealt with thought, and possibly
a breaking one. There is an inconsistency with StringByteSequence::[index]
returning a number. I know why it was done that way, but it contradict what
string does and does not offer smart index behavior.

And because of String::[index] behavior it is not possible to properly
obtain a sub StringByteSequence (because multiple bytes might be skipped at
front of String). So maybe in addition to String::byteAt(index) it would be
better to add a String::byteSubscript(index).

It would break some code, but would solve some annoying issues in the REPL
if I remember well, that are hidden by inforcing ASCII 7 and preventing
usage of unicode chars even in string litterals.
