### ISSUE TITLE
Unable to build Wren with MinGW

### ISSUE THREAD

**Issue by vtereshkov** [wren-lang/wren#738]
When trying to compile Wren with MinGW on Windows, I get the error message:

`b'Warning: Visual Studio not found\r\nTraceback (most recent call last):\r\n  File "gyp_uv.py", line 21, in <module>\r\n    import gyp\r\n  File ".\\build\\gyp\\pylib\\gyp\\__init__.py", line 37\r\n    print\'%s:%s:%d:%s %s\' % (mode.upper(), os.path.basename(ctx[0]),\r\n^\r\nSyntaxError: invalid syntax\r\nFailed to create vc project files.\r\n'`

**Comment by sukhchainn** [comment]
Oh, damn!
I'm not sure if this is the case but it seems like wren will only compile in Visual Studio.
I don't know why devs did it, I mean GCC is the standard then, Why?

Well, you can easily port the code to GCC, it's very easy and I can give it a shot if you want.
I love this project, the way it is set up and it's directory structure, the naming convention, the delicacy of C language, all on point, but Visual Studio is something which takes away all the beauty.

**Comment by avivbeeri** [comment]
Which version of Wren are you working with? I compile Wren 0.2.0 using MinGW and MSYS2 without any problems at all.

**Comment by sukhchainn** [comment]
@avivbeeri you're right it does compile in MinGW. I just checked it and it works.
wren is the most beautiful language, now that it compiles in GCC.
