### ISSUE TITLE
Some more examples of Functions in Wren

### ISSUE THREAD

**Issue by BoQsc** [wren-lang/wren#741]
Can someone give me more working examples of functions in Wren apart from these: http://wren.io/functions.html

I was really hoping to just write something like
```
function helloWorld() {
       System.write("Hello World")
}
```

But it seems that wren-lang has something different in mind.

**Comment by underscorediscovery** [comment]
Hi, functions only exist in the context of a class (methods), or as a `Fn` object.
Functions don't have any decorations up front. It's just `helloWorld()`

```js
class Example {
  construct new() {} //constructor
  helloWorld() {
     System.print("Hello World")
  }
}

var hello = Example.new()
hello.helloWorld()
```

A `Fn` object is a function that you can store in a variable, and then use `.call()` on. 
```js
var hello = Fn.new {|name|
   System.print("hello %(name)!")
}
hello.call("user")
```

If a method takes a function as an argument, there is some shorthand syntax for `Fn` usage.

```js
class Example {
   static call_this(fn) { fn.call() }
   static call_with_arg(arg, fn) { fn.call(arg) }
}

Example.call_this {
  System.print("block function! becomes an `Fn` using short syntax")
}

Example.call_with_arg("arg goes here") {|arg_comes_in_here|
   System.print("block function with arg %(arg_comes_in_here)")
}
```
