### ISSUE TITLE
duplicate isLocalName definitions prevent wren from compiling in unity/jumbo builds

### ISSUE THREAD

**Issue by Stephenmccaul** [wren-lang/wren#744]
The function isLocalName is defined in wren_vm.c and wren_compiler.c. This causes a compiler error when trying to do a unity build (#including all .c files in another .c file to reduce compiler invocations and header parsings).

Suggestions: 
 - mark it inline and move it into a header (yea that is not strict C)
 - replace the function with a macro in a header
 - call the two definitions by two different names so they do not conflict
 - change to non-static linkage and find a single home for it (probably the best option)

not that it is too useful but i'm compiling on windows with VS 2019 on using wren change 1618.

**Comment by underscorediscovery** [comment]
This is a known issue and is resolved in the next release (0.3.0 branch). Thanks
