### ISSUE TITLE
Recursion bug

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#748]
I came across Wren a few weeks ago and thought it would be fun to write some examples for it on [Rosetta Code](http://rosettacode.org/wiki/Rosetta_Code) either from scratch or by translating code which I (or others) have written in various other languages.

Anyway, on the whole, things have been going well and have certainly convinced me that Wren is not just useful as an embedded language but is also a great language for writing standalone scripts. So I hope the CLI side of things will be expanded in the future.

A couple of things I particularly miss in the language itself are a ```continue``` statement and the ability to set a step for a ```Range``` object though one can, of course, work around their absence. 

However, I have come across a bug which manifests itself in several (though certainly not all) of those tasks which are best, or more easily, solved by using recursion. Rather than re-post the code here, perhaps I could link to the first two examples I found:

[Pythagorean triples](https://rosettacode.org/wiki/Pythagorean_triples#Wren) 

[Cantor set](https://rosettacode.org/wiki/Cantor_set#Wren)

In the first one, if you comment out the ```System.write("")``` in the ```newTri``` function, you'll find it produces completely wrong answers until getting a segmentation fault.

In the second one, if you comment out the ```System.write("")``` in the ```cantor``` function, you get the runtime error :
```
Null does not implement 'iterate(_)'.
[./cs line 11] in new(_) block argument
[./cs line 15] in new(_) block argument
[./cs line 15] in new(_) block argument
[./cs line 19] in (script)
```
Incidentally, I found out by accident that System.write("") seemed to fix it when I tried to debug the problem by printing out some variable values.

Here's a similar example I discovered yesterday when researching an alternative (ridiculously fast!) solution for the [Self-describing numbers](https://rosettacode.org/wiki/Self-describing_numbers#Wren) task (based on some Python code) but which I haven't posted yet to RC:

```javascript
// assumes the lists are of equal length
var listEquals = Fn.new { |l1, l2|
    for (i in 0...l1.count) if (l1[i] != l2[i]) return false
    return true
}

var impl // recursive so declare first
impl = Fn.new { |d, c, m|
    if (m < 0) return
    if (d.count > 0 && listEquals.call(d, c[0...d.count])) {
        if (d[0] < 10) {
            System.print(d.join())
        } else {
            System.print(([String.fromByte(d[0] + 87)] + d[1..-1]).join())
        }
    }
    if (d.count == c.count) return
    for (i in c[d.count]..m) {
        var dd = d + [i]
        if (i >= dd.count || c[i] != dd[i]) {
            System.write("") // fixes a VM recursion bug
            impl.call(dd, c[0...i] + [c[i]+1] + c[i+1..-1], m-i)
        }
    }
}

var self = Fn.new { |n| impl.call([], [0]*(n+1), n) }

var start = System.clock
self.call(20)
System.print("\nTook %(System.clock-start) secs")
```

Without the familiar fix, this produces the error:
```
Bool does not implement 'iterate(_)'.
[./self_desc3 line 18] in new(_) block argument
[./self_desc3 line 22] in new(_) block argument
[./self_desc3 line 27] in new(_) block argument
[./self_desc3 line 30] in (script)
```
Finally, here's a somewhat stranger one (an attempted Go translation) for the [De Bruijn sequences](https://rosettacode.or/wiki/De_Bruijn_sequences#Wren) task where I've inserted two ```System.write("")```s.

```javascript
var rzset = Fn.new { |m, n|
    var s = "%(n)"
    var c = s.count
    return (m > c) ? "0" * (m - c) + s : s
}

var digits = "0123456789"

var deBruijn = Fn.new { |k, n|
    var alphabet = digits[0...k]
    var a = List.filled(k * n, 0)
    var seq = []
    var db  // recursive closure
    db = Fn.new { |t, p|        
        if (t > n) {
            if (n%p == 0 && p >= 1) {
                for (q in a[1..p]) seq.add(q)
            }
        } else {
            a[t] = a[t-p]
            System.write("") // bug fix (essential)
            db.call(t+1, p)          
            var j = a[t-p]+1
            while (j < k) {
                a[t] = j & 0xff
                System.write("") // bug fix (inessential)
                db.call(t+1, t)
                j = j + 1
            } 
        }
    }  
    db.call(1, 1)
    var buf = []
    for (i in seq) buf.add(alphabet[i])
    var b = buf.join()
    return b + b[0...n-1] // as cyclic append first (n-1) digits
}

var allDigits = Fn.new { |s|
    for (b in s) {
        var c = b.bytes[0]
        if (c < 48 || c > 57) return false
    }
    return true
}

var validate = Fn.new { |db|
    var le = db.count
    var found = List.filled(10000, 0)
    var errs = []
    // Check all strings of 4 consecutive digits within 'db'
    // to see if all 10,000 combinations occur without duplication.
    var i = 0
    while (i < le - 3) {
        var s = db[i..i+3]
        if (allDigits.call(s)) {
            var n = Num.fromString(s)
            found[n]= found[n] + 1
        }
        i = i + 1
    }
    for (i in 0...10000) {
        if (found[i] == 0) {
            errs.add("    PIN number %(rzset.call(4, i)) missing")
        } else if (found[i] < 1) {
            errs.add("    PIN number %(rzset.call(4, i)) occurs %(found[i]) times")
        }
    }
    var lerr = errs.count
    if (lerr == 0) {
        System.print("  No errors found")
    } else {
        var pl = (lerr != 1) ? "s" : ""
        System.print("  %(lerr) error%(pl) found:")
        System.print(errs.join("\n"))
    }
}

var db = deBruijn.call(10, 4)
var le = db.count
System.print("The length of the de Bruijn sequence is %(le)")
System.print("\nThe first 130 digits of the de Bruijn sequence are:")
System.print(db[0...130])
System.print("\nThe last 130 digits of the de Bruijn sequence are:")
System.print(db[-130..-1])
System.print("\nValidating the de Bruijn sequence:")
validate.call(db)
 
System.print("\nValidating the reversed de Bruijn sequence:")
validate.call(db[-1..0])

db = db[0..4442] + "." + db[4444..-1]
System.print("\nValidating the overlaid de Bruijn sequence:")
validate.call(db)
```
If you comment out the second one, it works fine but, if you comment out the first one, you get the error:
```
Null does not implement '<(_)'.
[./deBruijn line 24] in new(_) block argument
[./deBruijn line 22] in new(_) block argument
[./deBruijn line 33] in new(_) block argument
[./deBruijn line 80] in (script)
```
I won't be posting this one to RC as I've found an alternative iterative solution which I prefer though I think it's still worth investigating.

Clearly, there is some memory corruption going on here. I'm not familiar with the inner workings of the VM but, if a Fiber's stack starts small and can be increased in size to accommodate further frames (as in the Go language) then I suspect it's at one of these transition points where the problem lies. I imagine the VM switches to a different fiber to execute something like System.write("") and by then the previous fiber has reset its stack.

**Comment by PureFox48** [comment]
Forgot to mention I'm using Ubuntu 18.04 (AMD64).

**Comment by mhermier** [comment]
Try to run under valgrind, there is a high chance that wellknown VM stack
corruption bug is in action.

**Comment by PureFox48** [comment]
Thanks for that suggestion. I hadn't realized before that valgrind worked with anything other than C/C++ programs but apparently it works with anything.

Anyway, as expected, when the Wren scripts are run with the ```System.Write("")``` fix inserted, there are no errors. Otherwise, there are errors which are all of this nature:
```
Invalid write of size 8
   at 0x128CC5: runInterpreter (in /home/purefox/wren/wren)
   by 0x10FB91: runFile (in /home/purefox/wren/wren)
   by 0x10DB54: main (in /home/purefox/wren/wren)
Address 0x5a4b7b8 is 72 bytes inside a block of size 96 free'd
   at 0x4C31D2F: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x121D47: prim_fn_call2 (in /home/purefox/wren/wren)
   by 0x128BDE: runInterpreter (in /home/purefox/wren/wren)
   by 0x10FB91: runFile (in /home/purefox/wren/wren)
   by 0x10DB54: main (in /home/purefox/wren/wren)
Block was alloc'd at
   at 0x4C2FA3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x4C31D84: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x124C1B: wrenNewFiber (in /home/purefox/wren/wren)
   by 0x1298C3: wrenInterpret (in /home/purefox/wren/wren)
   by 0x10FB91: runFile (in /home/purefox/wren/wren)
   by 0x10DB54: main (in /home/purefox/wren/wren)
```
Does this look like the stack corruption bug you were expecting?

**Comment by mhermier** [comment]
Yes it is exactly that. If I remember well you can increase
INITIAL_CALL_FRAMES to some power of 2 larger than default value 4 to see
if it does fix the problem.

The problem is not in the language, but in the VM this is why valgrind is
working to trace the error.

**Comment by PureFox48** [comment]
Yeah, I've found the ```#define``` for that in the VM source code.

Is there a way to configure it from the command line or will I have to rebuild the VM with a new higher value for INITIAL_CALL_FRAMES baked in?

If it's the latter, I'm inclining to leave it with the ```System.write("")``` fix in my RC submissions, which does no harm, rather than ask folks to rebuild their VM.

**Comment by mhermier** [comment]
For now, one has to rebuild the VM, but it should be fixed some day, since
it is a quite critical issue.

**Comment by PureFox48** [comment]
OK, fine. At least it's a known problem.

Thanks for your help. I'll close the issue now.
