### ISSUE TITLE
Grammar fixes: it's -> its

### ISSUE THREAD

**Issue by skybrian** [wren-lang/wren#752]
`it's` is used instead of `its` in the following places (at least):

http://wren.io/blog/2-0.3.0-released.html

> The CLI now has it’s own corner of the docs,

http://wren.io/cli/

> instead it is it’s own project as a standalone tool you can run. It exposes it’s own standard library and modules that may be of interest if looking for a general purpose single binary scriptable tool.
 
(Two places.) Also, there should be a new sentence starting at "Instead."

https://github.com/wren-lang/wren-cli/releases

> The CLI has been split to it's own repo 

http://wren.io/cli/modules/

> The Wren CLI executable extends the built in language modules with it’s own

**Comment by ruby0x1** [comment]
Thanks, I'm aware. I was hurrying to get the release done, docs will continue to improve in the coming days.

**Comment by bjorn** [comment]
Why not keep the issue open until it has been addressed?

**Comment by ruby0x1** [comment]
It has...?

**Comment by bjorn** [comment]
@skybrian, btw, such issues are a perfect opportunity to get involved. Just fork and fix, open a pull request. It saves time since it will generally take you less time than for you to describe the fixes that are needed and then for somebody else to go and search for them and apply the changes.

**Comment by bjorn** [comment]
@ruby0x1 Ah, maybe you addressed these... I checked by doing 'git grep` and it returned:
```
CHANGELOG.md:as well as [move the CLI to it's own repo](https://github.com/wren-lang/wren-cli/)!
```
Which was indeed not one of the cases mentioned above...
