### ISSUE TITLE
Inconsistent wrenInterpretResult calls

### ISSUE THREAD

**Issue by Ichards** [wren-lang/wren#767]
When trying to interpret a small wren file, I've tried using a simple file reading function. However, when I use the value from that function in wrenInterpretResult, it'll only OCCASIONALLY work. I've tried different file reading functions. Here's what I've used so far.
```

const char* fileReader(const char* p_fileName)
{
    ifstream in(p_fileName);
    string contents((istreambuf_iterator<char>(in)), 
    istreambuf_iterator<char>());
    return contents.c_str();
}



int main()
{
        
    WrenConfiguration config;
    wrenInitConfiguration(&config);
    config.writeFn = simpleWrite;
    config.errorFn = simpleError;


    WrenVM* vm = wrenNewVM(&config);


    WrenInterpretResult result = wrenInterpret(
    vm,
    "my_module",
    fileReader("example.wren"));
    //"System.print(\"hello World!\")\nSystem.print(\"goodbye, world\")");
    cout << result << endl;

    wrenFreeVM(vm);
    
}

```
example.wren
```
System.print("hello World!")
System.print("goodbye, world")
```
The result will either be:
```
hello World!
goodbye, world
```
or
```
Type: 0
Module: my_module
Line: 1
Message: Error: Invalid byte 0xb8.
Type: 0
Module: my_module
Line: 1
Message: Error at 'so': Expect end of file
```

**Comment by ruby0x1** [comment]
Make sure the string you pass to Wren is null terminated, otherwise it'll read past the end.

**Comment by Ichards** [comment]
I was under the impression std::string.c_str() returned a null terminated string. Regardless, ensuring it's null terminated doesn't seem to change anything, unfortunately.

**Comment by DethRaid** [comment]
```cpp

const char* fileReader(const char* p_fileName)
{
    ifstream in(p_fileName);
    string contents((istreambuf_iterator<char>(in)), 
    istreambuf_iterator<char>());
    return contents.c_str();
}
```

The `std::string` gets destroyed at the end of this function's scope - right before you return a pointer to the now-destroyed character array

Proposed solution: return a `std::string` directly

**Comment by Ichards** [comment]
My bad, it seems to work now. I do recall trying to return a string before, but I probably screwed something up then. It works fine now, thank you.
