### ISSUE TITLE
list.removeAt changes size of list after checking if capacity resize is necessary

### ISSUE THREAD

**Issue by mattiasljungstrom** [wren-lang/wren#769]
Noticed this when I was hacking around in my own fork of wren:

```
Value wrenListRemoveAt(WrenVM* vm, ObjList* list, uint32_t index)
{
  ...

  // If we have too much excess capacity, shrink it.
  if (list->elements.capacity / GROW_FACTOR >= list->elements.count)
  {
    list->elements.data = (Value*)wrenReallocate(vm, list->elements.data,
        sizeof(Value) * list->elements.capacity,
        sizeof(Value) * (list->elements.capacity / GROW_FACTOR));
    list->elements.capacity /= GROW_FACTOR;
  }

  if (IS_OBJ(removed)) wrenPopRoot(vm);

  list->elements.count--;
  return removed;
}

```

Should "list->elements.count--;" be moved up to before the capacity check, or am I missing some detail in the implementation that makes this order necessary?

**Comment by mhermier** [comment]
I suspect it has to do with something like allocation optimisation. If you
are on the border of a resize, and do a remove there is quite some chance
that you'll probably insert again pretty soon. There is also the 0 border
that would cause an unnecessary deallocation.
But maybe I'm just seeing thing and it was not as deeply thought.

**Comment by bjorn** [comment]
I think @mhermier is exactly right. Wren grows by factor of 2, and if it just grew and then you remove the last element (not uncommon in case of stack usage pattern, for example) then it would immediately shrink again and this is a slow operation that could start happening a lot.

https://github.com/wren-lang/wren/blob/e45a9d03820bfa5b0c6281a15cec0383994aafe1/src/vm/wren_utils.h#L47-L53

https://github.com/wren-lang/wren/blob/e45a9d03820bfa5b0c6281a15cec0383994aafe1/src/vm/wren_value.c#L334-L341

(`GROW_FACTOR` is 2)

I'm personally a bit surprised that it will start to reallocate on removal so soon already.

**Comment by mhermier** [comment]
I'm also surprised, I would expect it reallocate on previous factor. Like
if size is 32 it would not reallocate till size is 8 and reallocate to 16.
Or something like that...

**Comment by mattiasljungstrom** [comment]
Thanks, this makes a lot of sense. Will close this ticket.
