### ISSUE TITLE
Different behaviour of two semantically identical functions.

### ISSUE THREAD

**Issue by ashwanidausodia** [wren-lang/wren#770]
I was trying out some examples on https://wren.io/try/ and I came across a weird behaviour. I am not at all familiar with wren, I was just checking it out after seeing a Hacker News post. Below two functions look semantically identical to me and should give same output but they don't. But if I swap the last two print statements, I get the same output (`i.e 144`). I was just wondering if it is the expected behaviour or is it a bug.
```wren
var Fib1 = Fn.new {|n|
  if (n <= 2) {
    return 1
  } else {
    return Fib1.call(n-1) + Fib1.call(n-2)
  }
}

var Fib2 = Fn.new {|n|
  if (n <= 2) {
    return 1
  } else {
    var left = Fib2.call(n-1)
    var right = Fib2.call(n-2)
    return left + right
  }
}
System.print(Fib2.call(12))
System.print(Fib1.call(12))
```

**Comment by mhermier** [comment]
Using valgrind, I can relate this issue to the well-known stack 
corruption issue.

It seems the original issue is gone but I revived it in with a test 
case: https://github.com/wren-lang/wren/issues/761

I'll add your testcase to it ASAP.

**Comment by ruby0x1** [comment]
With #807 merged both functions return the same result. Let me know if you see otherwise.
