### ISSUE TITLE
[Question] Best practice for mass bindings?

### ISSUE THREAD

**Issue by dezifit** [wren-lang/wren#789]
I'm planning to use Wren as embedded script language in an editor.  The question is about best practice for binding a larger number (> 50) of edit functions sharing the same type signature (arguments and return type), which are already resolvable by name.

Having to provide the same function "stub" for each of them feels unfortunate, regardless if handwritten or generated. Much preferred would be a single trampoline function for all of them. Is it possible to access the name of the called foreign function in the C layer, or - even better - to identitfy and assign  addtional reference data to the inernal VM symbol table slot?

**Comment by mhermier** [comment]
If you are meaning, you want to introspect the current method in flight,
due to how the VM works, it is not possible. A foreign function/method is
not an accessible object, and even circumventing this issue, the foreign
function data doesn't embeded the signature.
So either generation or macros are the easy ways to solve your problem
AFAIK.

**Comment by Alloyed** [comment]
here's a tricky construction that might get you what you're after:
```cpp
WrenForeignMethodFn myBindForeignMethod(WrenVM* outerVm, const char* className, bool isStatic, const char* signature)
{
	return [=](WrenVM* vm) { /* your dynamic dispatch method, using className or signature */ };
}
```
basically creating a new closure for each method, which will have access to the initial input params. I've not actually tested this, so those strings may go out of scope but if that's the case then copying it to a local and then capturing that should work just as well

**Comment by dezifit** [comment]
Thanks for the suggestions, I'm limited to C, therefore C++ lambdas are no option. I decided to register the target editor functions in a mapping table and bind simple helpers to wren, which in turn invoke the call dispatcher with the associated mapping id:

```
static void fn00(WrenVM *vm) { callFn(vm,  0); }
static void fn01(WrenVM *vm) { callFn(vm,  1); }
 ::
```
