### ISSUE TITLE
Support import from variable

### ISSUE THREAD

**Issue by mathewmariani** [wren-lang/wren#790]
Currently loading a module, without binding any variables from it works as so:
```
import "some_imperative_code"`
```

However, I think it would be useful to import modules from a variable; given that the var is a string.
```
var sic = "some_imperative_code"
import sic
```

A nice simple use-case for this could look something similar to this:
```
for (m in ["a", "b", "c"]) {
  import m
}
```

It could also be useful for importing data that is stored in `.wren` files.

**Comment by mhermier** [comment]
This is a generalization of #776 that as some interest.

**Comment by CohenArthur** [comment]
This is definitely tied to [this](https://github.com/wren-lang/wren/pull/776)

There's been a big discussion there, and I'm sure it's going to make it into the language in some form

**Comment by mhermier** [comment]
The question of calling "toString" method on given variable/object can also have some interest on a object like a "Path" or "Module".

**Comment by mhermier** [comment]
Why did you close the issue ?
