### ISSUE TITLE
Something funny: we can have static operators

### ISSUE THREAD

**Issue by ChayimFriedman2** [wren-lang/wren#797]
The following code is valid in Wren:
```wren
class C {
  static - {
    return "`-%(this)`??"
  }
  static -(other) {
    return "Cool, `%(this) - %(other)`!"
  }
}
System.print(-C) // `-C`??
System.print(C - C) // Cool, `C - C`!
```

This doesn't seem like a **bug**, but it is funny 😄 

I think this should be stated in the docs, something like "classes are first-class objects in Wren".

**Comment by mhermier** [comment]
Probably a non intentional feature, because I don't remember it being
mentioned or tested. Maybe it would be nice to add unit test for this.

**Comment by ChayimFriedman2** [comment]
Closing as #798 was merged.
