### ISSUE TITLE
System.print causes different output

### ISSUE THREAD

**Issue by mathewmariani** [wren-lang/wren#801]
I came across this strange error were adding a `System.print` statement changes the expected output of a function.

```
class SudoList {
  construct new() {
    _a = [10, 7, 8, 9, 1, 5]
  }
  
  sort(fn) {
    quicksort_(0, _a.count - 1, fn)
    System.print(_a)
  }

  quicksort_(a, b, fn) {
    if (a < b) {
      var p = partition_(a, b, fn)
      quicksort_(a, p - 1, fn)
      quicksort_(p + 1, b, fn)
    }
  }

  partition_(a, b, fn) {
    var p = _a[b]
    var i = a - 1    
    for (j in a..(b-1)) {
      // commenting and uncommenting this line yields different results
      System.print("bug stopper") 
      if (fn.call(_a[j], p)) {
        i = i + 1
        var t = _a[i]
        _a[i] = _a[j]
        _a[j] = t
      }
    }
    var t = _a[i+1]
    _a[i+1] = _a[b]
    _a[b] = t
    return i+1
  }
}

var w = SudoList.new()
w.sort{|a, b| a < b }
```

I've run this code in both the VM and in the browser at [wren.io/try](https://wren.io/try/); additionally, the error is not present when running the script on [wren-nest](http://ppvk.github.io/wren-nest/).

When `System.print("bug stopper")` is uncommented the program runs as expected.
When commented out the program crashes giving a `Right operand must be a number.` error.

Complete error:
```
Right operand must be a number.
[compile line 41] in sort(_) block argument
[compile line 25] in partition_(_,_,_)
[compile line 14] in quicksort_(_,_,_)
[compile line 16] in quicksort_(_,_,_)
[compile line 8] in sort(_)
[compile line 41] in (script)
```

**Comment by mhermier** [comment]
If you are on Linux try to run wren inside valgrind. I suspect you are
hitting a variation of the well-known stack corruption.

**Comment by ruby0x1** [comment]
This should hopefully be fixed soon, just waiting on some feedback. Thanks for the report and examples!

**Comment by mathewmariani** [comment]
> If you are on Linux try to run wren inside valgrind. I suspect you are hitting a variation of the well-known stack corruption.

I'm running on macOS currently.

**Comment by ruby0x1** [comment]
Hi @mathewmariani, try with #807 merged, I tested your code and the results are consistent.
