### ISSUE TITLE
network support

### ISSUE THREAD

**Issue by nu8** [wren-lang/wren#805]
Does Wren have the ability to make network requests? For example, given a string URL, it would return a string or byte array of the response body.

**Comment by CrazyInfin8** [comment]
Wren itself is pretty bare as your supposed to embed it into a program and create its API.
so it doesn't really have any network tools by itself

**Comment by ruby0x1** [comment]
AS @CrazyInfin8 mentions, wren is a scripting language and is meant to be embedded. It won't be able to provide networking. 

If anything, the [Wren CLI](https://github.com/wren-lang/wren-cli) project could get some, but that's about it.
