### ISSUE TITLE
Proposal: Date module

### ISSUE THREAD

**Issue by clsource** [wren-lang/wren#812]
Hello I don´t know if this is available.
But maybe a `Date/Time` optional module would be useful.

Some resources:

- https://www.epochconverter.com/programming/c
- https://www.thinkage.ca/gcos/expl/c/lib/strfti.html
- https://curl.haxx.se/libcurl/c/curl_getdate.html
- https://github.com/curl/curl/blob/master/lib/parsedate.h

_Epoch to human_

```c
#include <stdio.h>
#include <time.h>

int main(void)
{
    time_t     now;
    struct tm  ts;
    char       buf[80];

    // Get current time
    time(&now);

    // Format time, "ddd yyyy-mm-dd hh:mm:ss zzz"
    ts = *localtime(&now);
    strftime(buf, sizeof(buf), "%a %Y-%m-%d %H:%M:%S %Z", &ts);
    printf("%s\n", buf);
    return 0;
}
``` 

_Custom Epoch_ to human
```c
#include <stdio.h>
#include <time.h>

int main(void)
{
    time_t rawtime = 1262304000;
    struct tm  ts;
    char       buf[80];

    // Format time, "ddd yyyy-mm-dd hh:mm:ss zzz"
    ts = *localtime(&rawtime);
    strftime(buf, sizeof(buf), "%a %Y-%m-%d %H:%M:%S %Z", &ts);
    printf("%s\n", buf);
    return 0;
}
```

Human to Epoch

```c
#include <stdio.h>
#include <time.h>

int main(void) {
    struct tm t;
    time_t t_of_day;

    t.tm_year = 2019-1900;  // Year - 1900
    t.tm_mon = 7;           // Month, where 0 = jan
    t.tm_mday = 8;          // Day of the month
    t.tm_hour = 16;
    t.tm_min = 11;
    t.tm_sec = 42;
    t.tm_isdst = -1;        // Is DST on? 1 = yes, 0 = no, -1 = unknown
    t_of_day = mktime(&t);

    printf("seconds since the Epoch: %ld\n", (long) t_of_day);
}
```

**Comment by mhermier** [comment]
AFAIK no such module is available. While I agree there might be some usage for it, it is a huge can of worm, if you consider portability, precision and implementation. So unless there is a huge urge for it, I would consider it a low priority thing, but patches for reviews are welcome.

**Comment by avivbeeri** [comment]
My suggestion for it would be to do something like a minimal version of Java's Instant class: 

https://docs.oracle.com/javase/tutorial/datetime/iso/instant.html

The result would be a thin interaction layer for an ISO8601 date time stamp, which can be easily serialised and deserialised to a string.

**Comment by clsource** [comment]
How about a simple

`System.time` that returns the value of https://en.cppreference.com/w/c/chrono/time

```c
(uint64_t)time(NULL);
```

**Comment by avivbeeri** [comment]
This assumes that every platform has a time-keeping feature, which isn't entirely the case.

**Comment by clsource** [comment]
So in conclusion. This feature is better to integrate with `wren_cli` at best (since the platforms are known).
Each system that embeds Wren should provide a time feature if needed 👍 

So i'm closing ths for now 👍  Thanks for your thoughts

**Comment by clsource** [comment]
> This assumes that every platform has a time-keeping feature, which isn't entirely the case.

But the core already is importing time.h

https://github.com/wren-lang/wren/blob/main/src/vm/wren_core.c#L6

Can this be used as well then?

**Comment by mhermier** [comment]
AFAIK core only use a single function of it to estimate the elapsed time.
Most cpu offer such feature, without a notion of date.
