### ISSUE TITLE
Bizarre array-of-fn execution results

### ISSUE THREAD

**Issue by KillaMaaki** [wren-lang/wren#813]
So I was doing some experimentation recently (actually, as strange as it might sound, I was experimenting with compiling C code into Wren haha) and ran into some frankly _bizarre_ results related to calling into arrays of functions.

Take the following code:

```
class Module {
	construct new() {
		_pc = 0
		_running = false
		_jmpTable = List.filled(2, null)
		_jmpTable[0] = Fn.new {
			System.print("enter 0")
			_pc = 1
			System.print("exit 0")
		}
		_jmpTable[1] = Fn.new {
			System.print("enter 1")
			_running = false
			System.print("exit 1")
		}
	}
	main() {
		return run(1)
	}
	run(entry_addr) {
		_pc = entry_addr
		_running = true
		while(_running) {
			_jmpTable[_pc].call()
			System.print("RUNNING: %(_running)")
		}
		return 0
	}
}

class Program {
	construct new() {
	}
	
	main() {
		var module = Module.new()
		module.main()
	}
}

var test = Program.new()
test.main()
```

This can be plugged directly into https://wren.io/try/ page
What *should* happen:
- I call Module.main
- Module.main calls run(1)
- run sets _pc to 1, _running to true, and then enters the while loop
- On the first iteration through it should call _jmpTable[1], which should print enter 1 followed by exit 1, then the while loop should print RUNNING: false (as the function at jmpTable[1] sets _running to false), and then the while loop should exit and the run function should return 0.

The output should therefore be:

```
enter 1
exit 1
RUNNING: false
```

This is not what happens. What I actually get is this:

```
enter 1
exit 1
enter 1
exit 1
RUNNING: false
```

Somehow it calls _jmpTable[1] *twice*, but never reaches the end of the while loop the first time. However, a few seemingly unrelated changes to the code appear to break this behavior:

Changing the run method to add an extra dummy function call fixes it:
```
run(entry_addr) {
  System.print("This fixes it") // in fact any function call at all inserted anywhere before the _jmpTable call in the while loop appears to fix it.
  _pc = entry_addr
  _running = true
  while(_running) {
    _jmpTable[_pc].call()
    System.print("RUNNING: %(_running)")
  }
  return 0
}
```

Calling it without the wrapper Program class fixes it:

```
// instead of:
// var test = Program.new()
// test.main()

var test = Module.new()
test.main()
```

Or even wrapping it in a dummy function call instead of calling directly from Program.main:

```
class Program {
	construct new() {
	}
	
	main() {
		run()
	}

	run() {
		// this fixes it too.
		var module = Module.new()
		module.main()
	}
}
```

So I guess the big question: what on earth is going on here? At first I thought I might have introduced some errors in the VM with some of my custom modifications, but it seems it's reproducible in the main branch as well.

**Comment by ruby0x1** [comment]
Can you try on the latest main branch? the try page hasn't been updated but there was a fix for a stack corruption issue causing all sorts of weirdness. https://github.com/wren-lang/wren/pull/807

**Comment by KillaMaaki** [comment]
aaaah, that actually might be it. It's been a little while since I made my local branch, so it would probably be missing a fix and I had assumed try was up to latest. Give me a little bit to merge in latest and try that. Might've been a false alarm, sorry!

**Comment by ruby0x1** [comment]
no worries, I'm hoping to update the try page real soon.

**Comment by KillaMaaki** [comment]
Yeah looks like a merge from latest took care of it! Sorry, I should've checked that first!
