### ISSUE TITLE
wchar_t* Support

### ISSUE THREAD

**Issue by MikeRKing** [wren-lang/wren#827]
At the moment Wren only supports UTF-8 when being embedded.  At any point are you going to be flexible and allow wchar_t* to allow for unicode rather than being stuck using const char*?

**Comment by avivbeeri** [comment]
I'm not sure that would be appropriate. The Unicode 4.0 standard (ISO 10646:2003) notes that:

> The width of wchar_t is compiler-specific and can be as small as 8 bits. Consequently, programs that need to be portable across any C or C++ compiler should not use wchar_t for storing Unicode text.

**Comment by ruby0x1** [comment]
https://utf8everywhere.org/
