### ISSUE TITLE
Inherit built-in `Num`

### ISSUE THREAD

**Issue by ChayimFriedman2** [wren-lang/wren#830]
In Wren, you cannot inherit from built-in classes:
```wren
class MyString is String {} // Class 'MyString' cannot inherit from built-in class 'String'.
```
...Except for the built-in `Num` class, which of course causes weird behavior:
```
class MyNum is Num { // Passes!
  construct new() {}
}

System.print(MyNum.new()) // nan
```
```
class MyNum is Num { // Passes!
  construct new(n) {
    _n = n
  }
  toString { "%(type)(%(_n))" }
}

System.print(MyNum.new(1)) // MyNum(1)
System.print(MyNum.new(1) + 8) // MyNum(1)
System.print(8 + MyNum.new(1)) // Right operand must be a number.
```

The guilt is here:

https://github.com/wren-lang/wren/blob/ad4e039187bda492709786762d4a36ec0b00d91c/src/vm/wren_vm.c#L505-L520

We don't check for `vm->numClass`!

And I wonder: is this deliberately for some reason (which will be good to document), or just a bug?

**Comment by mhermier** [comment]
I would say it is a bug at 100%. Please provide a patch.

**Comment by ChayimFriedman2** [comment]
It turns out that `Bool` and `Null` are also in the same bucket.
