### ISSUE TITLE
[Feature Request] Raw Strings

### ISSUE THREAD

**Issue by clsource** [wren-lang/wren#851]
I think that a simple raw string would be beneficial when using lots of texts with double-quotes and similar needs to escape characters.

I think using the backtick character (**`**) (similar to Javascript) could be an option to delimiter a raw string.

```js
var raw = `This is a "Raw" String`
var raw2 = `
This can be done too %(not_interpolated)
`
```

Thanks 👍

**Comment by ChayimFriedman2** [comment]
I prefer Rust syntax because using this syntax there's no way to encode a backtick in the string.

Rust syntax:
`r` then zero to infinite `#`s then the string then the same number of `#`s as in the start.
For example:
```rust
r"I am a raw string an I can include \"
r#"I am an another raw string and I can include even " (and of course \ too)"#
r#####"I am a third raw strings and I can include " then up to 4 #s - see: "#### "#####
```
Syntax:
```
RAW_STRING_LITERAL :
   r RAW_STRING_CONTENT

RAW_STRING_CONTENT :
      " <text> "
   | # RAW_STRING_CONTENT #
```
(From [The Rust Reference](https://doc.rust-lang.org/reference/tokens.html#raw-string-literals)).

**Comment by clsource** [comment]
You are right that a single backtick character would need to be escaped too.
But that kind of syntax is in my humble opinion, not much Wren like.

If something can be to pass variables that can be done with replace.

```js
r"My not interpolated "string" with {param}".toString.replace("{param}", 42)
```

**Comment by ChayimFriedman2** [comment]
> If something can be to pass variables that can be done with replace.

That's true but not relevant.

> r"My not interpolated "string" with {param}".toString.replace("{param}", 42)

Your string isn't valid because you have `"` inside.

**Comment by clsource** [comment]
how about using python's `"""` for delimiting a raw string?

**Comment by ChayimFriedman2** [comment]
Then you cannot encode `"""`. Yes, this is rarer, but still.

**Comment by clsource** [comment]
Ok, how about using the current string method. But just adding a new escape character `%r()`. Then the interpolation logic would detect that and convert the contents to codepoints until the end of the parenthesis, later will interpolate the string and finally convert `%r()` back from codepoints to a string.

```js
var raw = "
%r("This is a raw string")
"
```

**Comment by ChayimFriedman2** [comment]
First, that can collide with format specifiers that we may have in the future.

Second, it does not solve the problem of escaping the end marker.

Third, I find it strange and unnatural.

**Comment by clsource** [comment]
Maybe it can't be helped but for raw strings, a new keyword must be provided. Unless there is some syntax sugar that could be added to convert to raw codepoints before interpolation. I don't know xd.

Here is a discussion of raw strings in _Swift_. https://github.com/apple/swift-evolution/blob/master/proposals/0200-raw-string-escaping.md

**Comment by ChayimFriedman2** [comment]
I'm not arguing that raw strings are not useful, I'm just saying that _about the proposed syntax_.

C# raw strings are pretty good. I love C#, but in this case, I think that Rust and C++ approaches are better. Remember that raw strings are often (although not always) used in the context of long strings, and in those places, even double quotes instead of one can confuse and break the read continuity. For example, how is reading this:
```c#
@"
<!DOCTYPE html>
<html lang=""en"">
  <head>
    <title>My Title</title>
  <head>
  <h1 style=""font-family: Arial;"">Header</h1>
  <script src=""script.js""></script>
</html>
"
```
Versus reading this:
```rust
r#"
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>My Title</title>
  <head>
  <h1 style="font-family: Arial;">Header</h1>
  <script src="script.js"></script>
</html>
"#
```
When I read the first example my eyes jump here and there because of the extra quotes. The second example is clear and easy to read. I also had in some project a list of strings that were aligned, and the quotes broke the alignment and make everything ugly.

**Comment by mhermier** [comment]
A simple solution would be to extend regular string to allow newlines to be
included. It has the benefit to allow raw like string at the cost of
requiring to escape the escape char.

Be careful that raw lines also open the line termination character, that is
OS dependent.

Considering last point and that it is an option that one hardly use, all in
all I don't find it really worth it to add.

**Comment by clsource** [comment]
Nevertheless, I find at least it should be addressed the escape double-quotes use case. It's a common character, especially in JSON and HTML documents. The "fat quotes" (_"""_) can be provided to automatically:

- 1: Enable using double quotes without escaping
- 2: Remove incidental white-space

```js
var json = """
{
 "my": "json"
}
"""
```

**Comment by PureFox48** [comment]
I'd like to see raw strings added to Wren too. 

Personally, I dislike the way C++ and Rust do it. Although they can cope with just about anything it's just too complicated for my taste.

The Go language uses back-ticks to delineate raw strings but a lot of people aren't happy that you can't then include back-ticks themselves in the raw string.

The best solution in my view is to use triple quotes. A number of languages have adopted this as a reasonable solution. You can't then include triple quotes in the raw string but how often does that come up? - not very often I suspect.

**Comment by ChayimFriedman2** [comment]
> A simple solution would be to extend regular string to allow newlines to be included. It has the benefit to allow raw like string at the cost of requiring to escape the escape char.

What wasn't clear when I said:

> Also I think it is important to say here that _Wren supports multiline string literals_ (for some reason it's not stated in the docs).

> You can't then include triple quotes in the raw string but how often does that come up? - not very often I suspect.

When you include a code in the language that includes raw string. That happened to me.

**Comment by benpop** [comment]
Single quotes aren't currently used by Wren, couldn't we use a single-quoted string as a raw string?

**Comment by PureFox48** [comment]
If we did, then we wouldn't be able to include single-quotes in the raw string and they're commoner in my experience than back-ticks and certainly much more common than triple double-quotes.

**Comment by clsource** [comment]
Other languages like Elixir uses the concept of sigils `~s()`and  `~S()`

https://elixir-lang.org/getting-started/sigils.html#strings

```elixir
~s(String with escape codes \x26 #{"inter" <> "polation"})
"String with escape codes & interpolation"

~S(String without escape codes \x26 without #{interpolation})
"String without escape codes \\x26 without \#{interpolation}"
```

**Comment by clsource** [comment]
I think this has been solved by @ruby0x1 https://github.com/wren-lang/wren/commit/8304fd5ecc8b367f5ece477fd0808f1f0c33f7e8 👍 💯 

I'm super happy about it. Thanks Ruby!

**Comment by ruby0x1** [comment]
I forgot to comment here but I was working on it and it was ready.
Here's the documentation: https://wren.io/values.html#raw-strings

**Comment by PureFox48** [comment]
What a pleasant surprise :)

I've been thinking about this for some time and was convinced that triple double-quotes were the best solution for a simple language such as Wren. The ignoring of white-space when the triple quotes are on their own line is also a nice touch.

If your raw string does happen to include code in Wren itself or in a language which also uses triple quotes for raw strings, then this will normally be easy to deal with by temporarily replacing the triple double-quotes with single quotes, viz:

```
"""
A markdown string with embedded wren code example.

    class Example {
      construct code() {
        var s = '''I'm an embedded raw string!'''
      }
    }
""".replace("'''", "\"\"\"")
```

**Comment by mhermier** [comment]
With this feature in place maybe it is a good time to revisit unit testing?

**Comment by ruby0x1** [comment]
@PureFox48 yea, replace works and you can also do combining

```js
"""
some long parts""" 
+ "\"\"\"" +
"""
the rest
"""
