### ISSUE TITLE
Creating a foreign object in a foreign object call?

### ISSUE THREAD

**Issue by mattiasljungstrom** [wren-lang/wren#867]
Is it possible to create and return a foreign object (in C) in a foreign call? The documentation for wrenSetSlotNewForeign() seems to imply that it's possible but it's a bit unclear to me.

**Comment by mhermier** [comment]
It returns a pointer to allocated memory. You can do what ever you want
with it. It is user memory.

**Comment by mattiasljungstrom** [comment]
Right, but how do I create a new Wren object in C? What I would like to do is to call a method from Wren into C that returns a new foreign object. Is this possible?

**Comment by mhermier** [comment]
It's should be a foreign contruct I guess?

**Comment by mattiasljungstrom** [comment]
Ok, so only way to create objects are from a contructor call? It's not possible to create Wren object in C from other calls? I'm specifically thinking of when you're calling a different class.

**Comment by mhermier** [comment]
If you want to create regular objects, it is a no, except for basic types
provided by the API. Else you can create foreign class instance.

**Comment by mode777** [comment]
@mattiasljungstrom You can create foreign objects in C if you can get hold of the class object

Wren
```
foreign class A {
}

class B {
  foreign static createForeignObj(class)
}

var inst = B.createForeignObj(A)
```

C
```c
static void createForeignObj(WrenVM* vm){
  // Your class object is in slot 1
  wrenSetSlotNewForeign(vm, 0 /*=return value*/, 1 /*class slot*/, sizeof(A));
}
```

You can also obtain a handle to your class object and store it on c side for later use, then set it with `wrenSetSlotHandle(vm, slot, myHandle)`.

**Comment by mattiasljungstrom** [comment]
Thanks @mode777 , this was what I was looking for!

**Comment by mhermier** [comment]
Can you elaborate what wsthe source of confusion, so that the doc could be
iproved?

**Comment by mattiasljungstrom** [comment]
@mhermier : I guess it wasn't clear how to get the class object in C, and if this operation would be at all valid in C without calling from the constructor. 

It would also be interesting to know the reasoning behind not allowing creating regular Wren objects in C. Is it a performance thing, or just to reduce VM complexity?

**Comment by mhermier** [comment]
For now it is a mainly a technical issue. Allowing to create any objects
from C means making reentrancy which is not supported (yet, and it is long
debate about introduce it).

Strictly speaking, you can call the constructor on a class, within the
limitations of `wrenCall`, but you can't store/use the returned instance,
with current API.

**Comment by mattiasljungstrom** [comment]
I see, thanks for the clarification!
