### ISSUE TITLE
[Feature Request] Hexadecimal number literals

### ISSUE THREAD

**Issue by debevv** [wren-lang/wren#875]
Hi, would it be possible to introduce parsing of haxadecimal numbers literals?
Like, if a number is prefixed by `0x` the parser will consider it as expressed in hexadecimal form.
It think it would be a useful but non-invasive feature.

If it's ok for you I would personally implement it. Can you point me where I should start?

**Comment by ChayimFriedman2** [comment]
It is already implemented 😄

**Comment by debevv** [comment]
Oh, I didn't notice that. If that's so, https://wren.io/values.html should be updated

**Comment by ChayimFriedman2** [comment]
You're welcome to send a PR. That page lives under https://github.com/wren-lang/wren/blob/main/doc/site/values.markdown.

**Comment by joshgoebel** [comment]
This can be closed?
