### ISSUE TITLE
Undocumented features of the List class.

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#878]
I noticed today an unexpected but welcome feature of the List class's ```+```operator which I thought was worth drawing attention to.

Although the documentation states that you can only add another List in fact you can add any other Sequence or type which satisfies the iterator protocol. For example, the following works fine:

```javascript
var lst = [1, 2, 3] + "45" + (6..7)
System.print(lst) // [1, 2, 3, 4, 5, 6, 7]
```

Two other things about the List class which aren't documented at all but are obvious when one examines the source code:

1. You can create a new List using the multiply operator: 

```javascript
var lst2 = [1] * 5
System.print(lst2) // [1, 1, 1, 1, 1]
```
This is just equivalent to ```List.filled(5, 1)``` but is useful all the same.

2. There is an ```addAll(other)``` method where again ```other``` does not have to be another List but can be any Sequence:

```javascript
var lst3 = [1, 2, 3]
lst3.addAll("4567")
System.print(lst3) // [1, 2, 3, 4, 5, 6, 7]
```
Surprising what you find when you dig around a little :)

**Comment by ChayimFriedman2** [comment]
About the first, I already opened #872.

About the others:

About #1, you're probably right.
About #2, I afraid that it isn't documented because it isn't public. I'll ask @ruby0x1, though.

**Comment by PureFox48** [comment]
Sorry, I'd missed that you'd already opened #872.

Regarding #2, I'd be surprised if ```addAll``` was intended to be private as it's not followed by an underscore as they normally are.

**Comment by ChayimFriedman2** [comment]
> Sorry, I'd missed that you'd already opened #872.

This happens to us all 😃.

> Regarding #2, I'd be surprised if `addAll` was intended to be private as it's not followed by an underscore as they normally are.

I would be too, but I'm still not sure. So I referred the question to @ruby0x1.
