### ISSUE TITLE
Undocumented features of the Num class.

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#879]
There appear to be three undocumented methods in the Num class, namely ```truncate```, ```fraction``` and ```toString```.

**truncate** 

Rounds the number to the nearest integer towards zero.

It is therefore equivalent to ```floor``` if the number is non-negative or ```ceil``` if it is negative.

```javascript
System.print(1.5.truncate)        (1)
System.print((-3.2).truncate)    (-3)
```
This is a useful method and I wrote my own before I realized it already existed in the standard library.

**fraction**

The fractional part of a number i.e. the part after any decimal point.

The returned value has the same sign as ```this```.

```javascript
System.print(1.5.fraction)       (0.5)
System.print((-3.2).fraction     (-0.2)
```
Again worth knowing about so you don't have to write your own.

**toString**
The string representation of the number, over-riding ```toString``` inherited from the ```Object``` class.

Although you might guess that this last one exists, it's probably worth mentioning in the docs. Before I realized it worked I always used ```"%(num)"``` which is less easy to read.

**Comment by ruby0x1** [comment]
Some of these are new in 0.4.0 and the docs haven't been updated just yet, but will be for the next release.

**Comment by ChayimFriedman2** [comment]
`toString` exists for all builtin types. Actually, `"%(obj)"` desugars to `"" + obj.toString + ""`.

**Comment by PureFox48** [comment]
> toString exists for all builtin types.

True and, indeed, for all types that are not built-in as everything ultimately inherits from ```Object```.

However, there are a few built-ins which don't override the ```Object``` implementation. For example:
```javascript
var f = Fiber.new { }
System.print(f) // instance of Fiber
```
Still on the ```Num``` class, I've noticed that some of the bitwise operators aren't documented either namely: ```^```, ```<<``` and ```>>```.
