### ISSUE TITLE
System.writeAll

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#881]
A minor omission but the ```System.writeAll``` method is currently undocumented. As you'd expect it does the same as ```System.printAll``` except that it doesn't print a newline at the end.

**Comment by ChayimFriedman2** [comment]
It would be nice if you were sending PRs for missing documentation instead of raising an issue. Writing a documentation for a method takes less time that opening an issue. Do you know how to send PR for the docs? I use GitHub editing feature for that, not even messing with git, vscode or whatever.

**Comment by PureFox48** [comment]
I wanted to make sure that I was right about these apparent omissions before submitting PRs.

As you said yourself in one of the other issues, these methods may be private or might even be removed before 0.4.0 (though I hope they aren't as they're all useful).

Anyway,  if there are no objections, I will submit PRs for all of them tomorrow.

**Comment by ChayimFriedman2** [comment]
First, please submit separate PRs. I think @ruby0x1 will agree with that.

Second, GitHub and a cool (maybe unknown? 😛) feature that let you close PRs without merging them. When the change is such tiny, it's easier to send a PR then discuss about it, or close it, than to open an issue before.

Third, and somewhat off-topic, I'm not aware of any methods removed in Wren ever. Especially in 0.4.0. Remember that removing a public method is a breaking change.

**Comment by PureFox48** [comment]
OK, I've submitted separate PRs for each of the 'undocumented' issues I've raised (4 in total).

> Third, and somewhat off-topic, I'm not aware of any methods removed in Wren ever.

Good as I dislike breaking changes unless they're absolutely necessary.
