### ISSUE TITLE
[RFC] Add integer division operator

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#907]
I have a lot of stuff where I need integer division and currently have to write stuff like this:

```javascript
var rem = a % b
var div = (a/b).floor
```
The second line is relatively tedious and, looking back through old issues to see whether this had been proposed before, I see that @munificent admitted as much in #127.

So, would it be worthwhile to have an _integer_ division operator as well as an _ordinary_ division operator?

If we did, then there would be a number of questions to answer:

1. What symbol should be used for the operator?
2. How exactly should it work?
3. What should its precedence be?
4. Should it be overloadable?

Taking each of these in turn:

1. The only integer division operators I can recall seeing in other languages are `\` in BASIC
and `//` in Python. I have no particular preference between them though I suspect the former would be easier to parse so I'll use that in the remainder of this post.

2. Given that Wren doesn't have integers as such, I think we'd want the operator to apply to any two Nums whether they're integers of not. There's then the question of negative numbers. Which of the following would be best:

```javascript
var a = -4.6
var b = 2
var c = a \ b  // -2 i.e. (a/b).truncate
var d = a \ b  // -3 i.e. (a/b).floor
```
I think I'm right in saying that BASIC typically uses truncated and Python floored division.

3. I can't see any argument for it being other than the same as `/` i.e. precedence level 3 with (obviously) left associativity.

4. Sure, why not.

A slightly awkward point is that the `%` operator returns a result which has the same sign as the numerator. So, here we have:

```javascript
var a = -4.6
var b = -2
var c = a % b  
System.print(c) // -0.6, not +0.6, because a is negative
```
Although it would be nice for the integer division and modulo operators to be consistent with each other, I think it would seem anti-intuitive to most people if `a \ b` were `-2` in this example.

As a further alternative would it be best to just add an integer division method to the Num class (perhaps `a.div(b)` or `a.idiv(b)`) rather than an operator which would be easier to implement?

As always, comments would be appreciated.

**Comment by ChayimFriedman2** [comment]
It is not harder to parse `//` than `\`, but we can't use it since Wren uses `//` for line comments (Python uses `#` for that so it could).

**Comment by PureFox48** [comment]
Good point, I'd forgotten about that.

**Comment by mhermier** [comment]
I would not use \ for various reasons, main one being that it is usually
used to break a line in script languages, and we will need that to expand
the repl at some point.

A stupid idea why not add a parameter to truncate and floor?

**Comment by PureFox48** [comment]
> A stupid idea why not add a parameter to truncate and floor?

Do you mean  `a.floor(b)`  would be equivalent to `(a/b).floor` ?

If so, I'm not too keen on it as I think it would be potentially confusing.

I'd prefer `a.div(b)` or we could even have `a div b` as there's a precedent for using a word as an operator (namely `is`). However, as `div` would need to be a reserved word, the latter would not be backwards compatible so I think we can rule it out immediately.

**Comment by PureFox48** [comment]
Comments so far on this issue have been very useful and I've come to the conclusion that an integer division operator is not going to be practicable because there simply isn't a symbol available which is suggestive of division.

To my mind that just leaves us with adding an `a.div(b)` or `a.idiv(b)` method to the Num class. Personally, I prefer the former as simple sugar for `(a/b).truncate` i.e. always round towards zero.

So I'll leave the issue open for any further thoughts on the matter.

**Comment by mhermier** [comment]
If you go that route than `.quo` should be a synonym of `.truncate` if I'm
not mistaken. This is why I proposed the version of `.truncate(_)` an
`.floor(_)` to not add extra names in the first place.

**Comment by PureFox48** [comment]
Yes, `a.quo(b)` would be synonymous with `(a/b).truncate`.

However, the reason I was suggesting this in the first place was so that it would be shorter and, hopefully, clearer to write. 

I don't think it's clear what  `a.truncate(b)` would mean as there's no implication of division and it isn't short either.  Personally, I'd prefer to just live with what we have rather than to introduce that.

**Comment by PureFox48** [comment]
OK, I think I'm going to close this issue as a new operator clearly isn't viable and a new method (or overloading an existing one) doesn't seem worth the effort. At least what we already have, even if verbose, is clear and you can round it how you like.

It's something that's been bugging me for a while so I feel better for having discussed it. Hopefully,  commenters will agree that it was at least worth giving it an airing :)
