### ISSUE TITLE
Examples - Functions

### ISSUE THREAD

**Issue by yuppox** [wren-lang/wren#909]
I don't understand the examples in the Functions documentation. It says that "free-floating functions" are possible but I don't see an example. I wanted to try creating a class with a function (a method) but many of the example don't seem to work.

This:
```
class Blondie {
  callMe(fn) {
    // Call it...
  }
}

var blondie = Blondie.new()
```

gives me the error: `Blondie metaclass does not implement 'new()'.`

**Comment by ruby0x1** [comment]
See here for a breakdown. I intend to clarify the docs a bit soon.
https://github.com/wren-lang/wren/issues/741#issuecomment-607373566

**Comment by yuppox** [comment]
Thanks! That helps - especially explaining the constructor:

```
construct new() {} //constructor
```

**Comment by ruby0x1** [comment]
Yea, those are documented in the Classes page which is after heh :) https://wren.io/classes.html#constructors
