### ISSUE TITLE
[RFC] Add method chaining operator.

### ISSUE THREAD

**Issue by mhermier** [wren-lang/wren#914]
Hi,

It poped quite some times in the issues, that method chaining is a thing that maybe need to be addressed.
So I gave it a try, and it was quite trivial to add support for it in the language. I need still to add some documentation before publishing something for more battle testing. I made some tests, but I guess there might should not be enough.

So far, I used ';' as an operator, I don't really like that choice because of 'C' syntax predominance but that was an easy character to test implementation.

I chose `PREC_CALL` precedence, but I wonder if that it should have lower/higher priority, battle testing will tell.

So far the syntax looks like:
```
var my_list = Foo.new();call(42);foo = 42;foo
```
Where my list returns is the new created list. You can notice that getter/setter are handled (supporting getters can have sense if they have side effects).

The extra thing to debate is does supporting binary operators and subscript (setter) operators is a thing. Because it would also means we need to add support for allowing 'foo.&&(bar)' to make things coherent.

One thing that might be needed to be considered in a latter phase is combining calls like:
```
var my_list = Foo.new();(call(42);operate_on_returns_of_call())
```
Thought it can be trivial too add, I have concerns about readability.

**Comment by PureFox48** [comment]
Correct me if I'm wrong but it seems that what you're proposing here is not really method chaining, where a series of methods are applied to the return value of the previous method in the chain.

It's more like what is called a ```with``` statement in some other languages where a succession of properties/methods is applied to a single object with any intermediate return values being ignored. So the following statement:

```javascript
var my_list = Foo.new(); call(42); foo = 42; foo
```

is equivalent in current Wren syntax to this:

```javascript
var f = Foo.new()
f.call(42)
f.foo = 42
var my_list = f.foo
```

or, in ```with```statement form to this:
```javascript
var f = Foo.new()
with (f) {
    call(42)
    foo = 42
}
var my_list = f.foo
```

I don't understand where the list is coming from here as ```foo``` appears to be a scalar property but, as it's just an abstract example, no matter.

Applying the same analysis to the more concrete example you gave in #913 produces this:
```javascript
// in your proposed syntax
var r = 10..a; step = 2; ascending = false

// in current Wren syntax
var r = 10..a
r.step = 2
r.ascending = false

// in with statement form
var r = 10..a
with (r) {
    step = 2
    ascending = false
}
```

Personally, I quite like your proposal for property setters (which don't normally return a value) but I think it's potentially confusing for anything else.

If confined to property setters, then it would enable us to set a number of properties on a given object in a concise way i.e. without repeating the object reference and possibly on one line.

However, I think the ```;``` operator (or whatever is used) would need to be able to break lines otherwise there would be readability issues where a large number of properties were being set. 

In cases where properties are dependent on each other, then clearly the user would need to set them in the correct order just as they do now.

**Comment by ChayimFriedman2** [comment]
First, people used to `;` as line breaker.

Second, I fail to see the need. If you design an interface that should be chained (fluent), return `this` from each method. Otherwise, the longer code is more obvious.

**Comment by mhermier** [comment]
Well the idea does not come from thin air, I borrowed it from Smalltalk chaining operator which is probably a better name/description. Incidentally, Smalltalk also used ';' and I used the same operator by accident (I remember that it existed in the syntax not in the details). But that is a place holder till a final decision is made.

The need is that you can make everything fluent without requiring to tune your API to be fluent. fluent API is a hack/workaround the lack of expressiveness in the language.

**Comment by mhermier** [comment]
One interesting side effect of that feature is that it does allow to describe trees, eg:
```
var tree = Tree.new();
    (addChild;name="root";
      (addChild; name = "First Leaf"; value = 42);
      (addChild; name = "Second Leaf"; value = 54)
    )
```

**Comment by ChayimFriedman2** [comment]
> fluent API is a hack/workaround the lack of expressiveness in the language.

Exactly the opposite. This operator is a hack for the lack of expressiveness in your API.

Not all APIs need to be fluent. This is a special style of API that is used to build an object, an alternative construct to constructors (no pun intended). Methods, on the other hand, should perform operations. The new range API (if accepted) should be fluent, I agree, but for this goal to be achieved we need to change the API (the original proposed API is fine), not the language.

**Comment by ChayimFriedman2** [comment]
> One interesting side effect of that feature is that it does allow to describe trees, eg:
> 
> ```
> var tree = Tree.new();
>     (addChild;name="root";
>       (addChild; name = "First Leaf"; value = 42);
>       (addChild; name = "Second Leaf"; value = 54)
>     )
> ```

What's bad with:
```wren
var tree = Tree.new([
  Node.new("root", [
    Node.new("First Leaf"),
    Node.new("Second Leaf"),
  ]),
])
```

**Comment by PureFox48** [comment]
It's worth noting that, even if you do return ```this```, you can only chain property setters in a fluent way by declaring them as normal methods:

```javascript
class C {
    construct new(a) {
        _a = a
    }
    a { _a }
    a(b) { // normal method not property setter
        _a = b
        return this
    }

    toString { _a.toString }
}

var c = C.new(1).a(2).a(3)
System.print(c) // 3
c.a = 4 // C does not implement 'a=(_)'.
```

I don't think that ```;``` is necessarily a bad choice of operator since some languages which don't require statements to end with a semi-colon (for example Go) still use it to separate statements on the same line.

**Comment by mhermier** [comment]
Nothing, but there are 3 major issue to be aware, because subclass nodes are exposed:
- a fluent API can solve that to a certain degree
- if you need to forbid sub-classing, then you have to make a class validation.
- if you need to make internal state management (like resource loading or what ever), all the nodes needs to be connected to the root before any validation can happens.

With this syntax, you don't need to expose external classes, the user can only use the method provided by the returned objects, and internal state can be validated earlier.

**Comment by mhermier** [comment]
One interesting side effect of enabling this, is: since fluent is available in the language, there is no need to write fluent interfaces in addition to *regular* API. It makes less code to write and more generic code more, and it also helps the implementation in the long run, by reducing the number of unique methods signatures.

**Comment by ChayimFriedman2** [comment]
> It's worth noting that, even if you do return `this`, you can only chain property setters in a fluent way by declaring them as normal methods:
> 
> ```js
> class C {
>     construct new(a) {
>         _a = a
>     }
>     a { _a }
>     a(b) { // normal method not property setter
>         _a = b
>         return this
>     }
> 
>     toString { _a.toString }
> }
> 
> var c = C.new(1).a(2).a(3)
> System.print(c) // 3
> c.a = 4 // C does not implement 'a=(_)'.
> ```

First, you _can_ return `this` from a setter, although I wouldn't recommend it of course (and I think you'll need parentheses because of precedencies).

But I do not see it as a bad thing. Take constructors as an example: they don't have setter signature either, yet they set properties, usually even with the same name as their parameters. This is idiomatic because they don't _change_ properties, but _initialize_ them. Fluent interfaces are just another kind of constructors; languages like Python, that have named arguments (`**kwargs`), can avoid them and use named arguments in the constructor instead.

> I don't think that `;` is necessarily a bad choice of operator since some languages which don't require statements to end with a semi-colon (for example Go) still use it to separate statements on the same line.

This is why I thought that using `;` is bad, however I didn't realize that this proposal is indeed some form of statement chaining in the same line.

> Nothing, but there are 2 major issue to be aware, because subclass nodes are exposed:
> 
> * if you need to forbid sub-classing, then you have to make a class validation. (a fluent API can solve that to a certain degree)
> * if you need to make internal state management (like resource loading or what ever), all the nodes needs to be connected to the root before any validation can happens.
> 
> With this syntax, you don't need to expose external classes, the user can only use the method provided by the returned objects, and internal state can be validated earlier.

I don't understand your points.

**Comment by PureFox48** [comment]
> First, you can return this from a setter,

Yes, I realized that a setter could return ```this``` but I couldn't then figure a way to use it fluently - not without heavy use of parentheses anyway which is hardly fluent and ends up looking more like Lisp than Wren when you're chaining multiple properties.

The one aspect of this proposal that I do like (and TBH the only one) is that you would be able to chain property setters in a fluent way. However, as to whether it would be worth doing on that basis - probably not - and I don't think @mhermier would be satisfied with such a limitation in any case.

**Comment by mhermier** [comment]
First argument, if I take your example, and augment with node subclass, for
each subclass I have to make an import, the parent object may or may not
have type checking to see if the leafs have a valid type and the root is
created last.
With fluent operator, the root node is created first, and provide the
objects without need to import or type check.

Second argument, since root is created first, it can check that child node
are created correctly. Eg, let's pretend nodes have name, and it is
forbidden to duplicate names. With your approach, you create all the node
and die at insertion. With that approach, code dies when trying to create
the child node.

**Comment by mhermier** [comment]
I would not really care at doing it on a basis. The only problem I would
have is that it would add more on the hidden implementation cost, that the
feature requires. In practice it should not add much, because I don't think
fluent call happens that often. But it should be considered.

**Comment by mhermier** [comment]
The main question would be on what basis you would like to discriminate?
Based on signature? At compile time? At runtime?

**Comment by PureFox48** [comment]
It would be on the basis of signature (i.e. any property setter) and at compile time.

So an expression of the form:
```javascript
objectRef; propSetter1 = value1; propSetter2 = value2; ....
```
could be translated by the compiler to:
```javascript
objectRef.propSetter1 = value1
objectRef.propSetter2 = value2
....
objectRef // value of the expression
```

**Comment by mhermier** [comment]
This solution could be cheap, but forbid the creation of trees.

**Comment by PureFox48** [comment]
True, but for me the selling point of this limited proposal is that you'd be able to do something fluently (namely set properties) that you can't do at present and would be generally useful. Moreover,  it should be easy for folks to understand and probably implement.

On the other hand, whilst one can argue about the technicalities, fluent method chaining is possible at present given a suitably designed API and I think that's good enough for most people.

**Comment by mhermier** [comment]
I have not tested it yet, but if I really want to implement your feature,
first I have to change the `canBeSetter` flag to an enum, so I can pass a
`mustBeNameSetter` flag or alike. Should be done at some point I think, but
I am not sure it is worth enough to justify, to put a only used once
arbitrary limitation.

**Comment by PureFox48** [comment]
Well, it's not really an arbitrary limitation - it's just limiting the proposal to something that cannot be done fluently at present.

As to whether it's worth doing in either this limited form or the wider basis you originally envisaged, we'll have to leave that to @Ruby0x1 to decide. He'll have plenty on his plate after the spate of recent proposals :)

**Comment by avivbeeri** [comment]
> _She'll_ have plenty on _her_ plate
FTFY

**Comment by ruby0x1** [comment]
This is not something I would pursue any time soon. It adds new (likely confusing) syntax, magic/implicit mechanics, and does not look elegant at all. It doesn't feel like Wren, Wren continues to want to be a simple language and this doesn't fit to me. 

We can also already do method chaining plenty fine with the tools we have. 
As with anything, the trade off for what you get isn't high enough to introduce this, especially not for the % of use case.

Thanks for the thoughts!
(Feel free to continue discussing).
