### ISSUE TITLE
Running OS processes question

### ISSUE THREAD

**Issue by achikin** [wren-lang/wren#917]
Hi, I'm looking for a kind of bash script replacement for my small scripting needs (which sometimes are not so small), so I want something like wren: single-file distribution, simple, elegant. 

The only question I have - can wren execute external OS processes and capture the output?

**Comment by ruby0x1** [comment]
Hi @achikin . The [Wren CLI project](https://github.com/wren-lang/wren-cli) is the _type_ of thing where processes would be implemented, but at the moment has no implementation for it. The CLI is based on [libuv](http://docs.libuv.org/en/v1.x/guide/processes.html), which has support for that, so adding it would be quite feasible, if that interests you.

**Comment by achikin** [comment]
Yes, sorry, I didn't realize that CLI resides in a separate project. Thank you for your clarification.

**Comment by ruby0x1** [comment]
Not a problem at all!
