### ISSUE TITLE
Top level functions?

### ISSUE THREAD

**Issue by IngwiePhoenix** [wren-lang/wren#922]
Hello!

From the last time I toyed around with Wren, I remember that the only way to make top-level functions is to do something like this:

```wren
var toplevel = Fn.new {
  System.print("ok")
}
```

Is this still the only way, with the calling to be written as `toplevel.call()`? Or has `toplevel()` been implement over the time?

Thanks and kind regards,
Ingwie!

**Comment by mhermier** [comment]
Nothing changed. Thought there is one trick that you might not be aware to simulate overloading doing something like:
```
class toplevel {
  static call() { call("ok") }
  static call(obj) {
    System.print(obj)
  }
}
```

**Comment by mhermier** [comment]
I don't remember if this was evoked before, but there might be a possibility to by-pass the grammar ambiguity by distinguishing getter syntax by enforcing extra parenthesis.
```
foo.bar() // would always call "Foo::bar()"
(foo.bar)() // would call "Bar::()" operator
```

**Comment by ChayimFriedman2** [comment]
This is what Rust does, and I find it visually bad.

**Comment by mhermier** [comment]
Unfortunately there is no other solution. Either we allow getter/setter
syntax or have the usual function syntax. Mixing them is doable but runtime
expensive.

**Comment by ChayimFriedman2** [comment]
> Unfortunately there is no other solution

...except remaining with the `.call()` syntax 😃

**Comment by mhermier** [comment]
It is a non solution, by enforcing a convention.

**Comment by IngwiePhoenix** [comment]
> ```
> class toplevel {
>   static call() { call("ok") }
>   static call(obj) {
>     System.print(obj)
>   }
> }
> ```

Implementing that from a C API will be hard... That, and I smell a good bit of overhead. xD

Oh well, guess I'll have to deal with it then. Thank you for your reply :)
