### ISSUE TITLE
False positive syntax error

### ISSUE THREAD

**Issue by ThakeeNathees** [wren-lang/wren#924]
Hello!!

I've been reading wren source for a couple of days. It seems like new lines are part of the language grammar and ignored some places fairly. In the below code new line in the parameter list is being parsed without any errors. However, removing the parameter cause syntax errors. Not sure if that intended or a false positive error. (P.S. similar syntax is valid in ruby)

```swift
class Wren {
  flyTo(
        city) {
    System.print("Flying")
  }
}
```

```swift
class Wren {
  flyTo(
        ) {
    System.print("Flying")
  }
}
```

```
[./main line 4] Error at ')': Expect variable name.
[./main line 4] Error at '{': Expect ')' after parameters.
[./main line 4] Error at newline: Expect '{' to begin method body.
[./main line 5] Error at newline: Expect '}' at end of block.
```

```swift
// And also this one.
var x = (
           1 + 2
        )
System.print(x)
```

**Comment by mhermier** [comment]
It is probably an error that can be relaxed. While it makes ugly code,
there is no particular ambiguity that could result of allowing multiline
between parenthesis.
