### ISSUE TITLE
Can relative module resolution be implementd with wren?

### ISSUE THREAD

**Issue by mode777** [wren-lang/wren#927]
I wonder if NodeJS like module resolution could be implemented in wren. NodeJS will load modules relative to the location of the module they where required from. See here: https://nodejs.org/api/modules.html#modules_file_modules

I think this is pretty handy especially for libraries, as they don't have to care about the project structure.

However I don't think this is currently possible with wren. There is now a callback for onComplete that could help with paths, but as I understand Wren basically needs each module to have a unique string as identifier and only tries to resolves modules it hasn't seen yet.

Am I missing somethig here or is this correct? Maybe it would be nice to have some kind of hook to normalize module names before letting Wren decide if it wants to load the module.

**Comment by avivbeeri** [comment]
It wasn't originally possible, but there are features in the current version of the VM for this:

https://github.com/wren-lang/wren/blob/208bbc02a5287d4a14a00897da0959f5845465f6/src/include/wren.h#L61

You know the context of the importing module, which means you can do path normalisation and resolution of relative paths before the `loadModule` callback is called.

**Comment by ChayimFriedman2** [comment]
I think the CLI does that, not sure though.

**Comment by mode777** [comment]
> It wasn't originally possible, but there are features in the current version of the VM for this:
> 
> https://github.com/wren-lang/wren/blob/208bbc02a5287d4a14a00897da0959f5845465f6/src/include/wren.h#L61
> 
> You know the context of the importing module, which means you can do path normalisation and resolution of relative paths before the `loadModule` callback is called.

I'didn't know about that. Thanks alot!
