### ISSUE TITLE
[RFC] Introduce a Long type for 64-bit signed integers.

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#929]
One thing I miss when programming in Wren is not being able to perform (full) 64 bit integer arithmetic, as we are effectively limited to no more than 53 bits because of the way that ```Nums``` are represented.

I've been wondering whether there might be a way to achieve this without impacting on the simplicity of dealing with smaller integers and numbers generally that the ```Num``` class gives us and have come up with an idea.

This is a fairly rough sketch so please bear with me.

The basic idea is to introduce a ```Long``` class into the core library. A ```Long``` object would be 8 bytes long and would be represented internally by a C99 ```signed long long```. It would be immutable as numbers are now.

Consequently, a ```Long``` would be a value type as a variable of that type would hold its value directly.

The ```Long``` class would not have constructors but instead a ```Long``` object could be created in one of three ways:

1. From a literal - an integer with an 'L' suffix. Lower case 'l' would not be allowed as it's too easily confused with the digit '1'.

2. From a string by giving the ```String``` class a ```toLong``` method which could optionally specify a base from 2 to 36.

3. From a number by giving the ```Num``` class a ```toLong``` method.

The ```Long``` class itself would support all the usual integer operators:

\+  \-  *  /  %  &  |  ^  ~  <<  >>  <  <=   ==  !=  >= and >.

However, the operands would always need to be ```Long``` objects - mixed operations with ```Nums``` would not be allowed.

We'd also need a few methods such as: ```largest```, ```smallest```, ```min```, ```max```, ``pow`` and ```sign```  as well as ```toNum``` and ```toString```.

Here's a few simple examples to show how some of this would look:

```javascript
var r = 123456789L                  // Long created from a literal
var s = "123456789123456789".toLong // Long created from a String
var t = 12345678912345.toLong       // Long created from a Num
var u = "abcdef".toLong(16)         // Long created from a base 16 string
var v = s + t * u                   // arithmetic operations on Longs
var w = (s > t) && (t > u)          // relational operations on Long
var x = s + 6                       // not allowed, can't add Num to a Long
var y = s + 6L                      // fine
var z = r.toNum                     // Long converted to Num 
```
Internally all operations would be performed from the C side using ```long long``` arithmetic and conversion functions such as ```strtoll```.

There would clearly be a lot of work needed to implement this and so the question is would it be worth it?

On the plus side:

1. We'd get full 64-bit integer representation and arithmetic including bit-wise operations though the latter might necessitate an internal conversion to ```unsigned long long```. It would probably be best for overflows to wrap rather than producing an error.

2. As we'd just be dealing with integers, base conversions would be straightforward to implement.

3. Integer division would be just that (i.e. any remainder would be discarded) which is something I was banging on about in #907.

4. There would be no impact whatsoever on ```Num``` arithmetic. 

5. It would be backwards compatible. 

On the minus side:

1. There would be a certain amount of inconvenience in not permitting mixed arithmetic with ```Nums```.

2. There would inevitably be an impact on the size of the core library though I don't really see how it could done as an optional module as you'd need support for ```Long``` literals in the language itself. 

3. Using a numeric suffix for literals is arguably a bit ugly but I can't think of a sensible alternative and, of course, C has used suffixes from day one.

4. A ```Long``` would have a lower range than an _unsigned_ 64 bit integer but I feel that the convenience of having signed integers outweighs this.

5. There would  be more for newcomers to the language to learn.

Finally, I'd add that you could do a lot of this with a custom type which is represented internally by a ```List``` of two ```Nums```. However, the trouble with this is that it's relatively slow and, as it's a reference type, it will be subject to garbage collection and can't be used directly as a ```Map``` key.

I look forward to hearing what you all think.

**Comment by ChayimFriedman2** [comment]
This is not hard to implement. However:

Using `int64_t` is better that `long long` as minimum size is guaranteed.

Consider renaming this to `Int64` or similar, possibly with `UInt64`.

Do we really need that? If performance are your concern, this won't help you. These integers will have to be boxed, which will slow them _much_.

If performance are not your benefit, you can implement this in Wren, or even in the host. The core should be really minimal.

If you still think this is a useful addition, please share us why.

**Comment by ChayimFriedman2** [comment]
One thing _I_ think this can be useful for is bit twiddling. Not common, but useful when needed. It is however better suited for `uint64_t`.

**Comment by mhermier** [comment]
Implementation wise, it is only can only be cheaply done without double Nan
tagging. With it we can't avoid an allocation.

And if we go that route, I think it is preferable to directly have
BigInteger of any size and restrict/optimise for 64 bit.

**Comment by PureFox48** [comment]
Thanks for those  comments.

> Using int64_t is better that long long as minimum size is guaranteed.

I thought that C99 did guarantee a minimum size for the ```long long``` type,  namely  8 bytes?

> Consider renaming this to Int64 or similar, possibly with UInt64.

```Int64``` would be a reasonable alternative to ```Long``` though an 'I' suffix for literals is not so good as it looks like the digit '1'. 

I'd prefer it to be a signed type as they're more versatile and dealing with unsigned types can be problematic when they get close to zero.

> These integers will have to be boxed, which will slow them much.

As they'll be exactly 8 bytes long I don't see why they will need to be boxed as they'll fit into the same slot as a 64 bit float. It would just be a question of how those bytes were interpreted.

This is why I was thinking that ```Long``` objects could be value types, would therefore be suitable as ```Map``` keys and (as non-reference types) would not have GC concerns.

Performance is a concern to me but not the only one. 

I have in fact created for my own use a BigInt type for arbitrary precision integers which is represented internally by a list of Nums and which I currently use for 64 bit arithmetic. This works well enough but is not very quick and, of course, there's no way I can create literals.

You're right, of course, that if  a Long type were created from Wren itself, then it would be more efficient to use two ```Num``` fields rather than a list of two ```Nums```.

**Comment by ChayimFriedman2** [comment]
The idea of `BigInteger` is good.

Regarding disabling NaN tagging, this is not right - we need a way to save pointer data which is also 64 bit (or 2, that doesn't matter).

The only way is to pass a union which will _greatly_ make things worse. I even think (only a guess, but a educated one) that this will be even worse than boxing everything.

**Comment by ChayimFriedman2** [comment]
> As they'll be exactly 8 bytes long I don't see why they will need to be boxed as they'll fit into the same slot as a 64 bit float. It would just be a question of how those bytes were interpreted.

And when will you store the bit of info to tell which type is this?

**Comment by ChayimFriedman2** [comment]
> I thought that C99 did guarantee a minimum size for the `long long` type, namely 8 bytes?

Well, not exactly: it specifies that it must be greater than or equal to `long`, and it's minimum min/max values, but not its size. OTOH, `int64_t` is required to be 64 bits length or not exist, which is good for bit twiddling.

**Comment by mhermier** [comment]
Another solution is to have something like Int64List, and allow math on
them, not really practical, but could be reused.

**Comment by ChayimFriedman2** [comment]
> Another solution is to have something like Int64List, and allow math on them, not really practical, but could be reused.

Defined in Wren or C?

**Comment by mhermier** [comment]
About storing a pointer in a double, it is a lot of trickery relying on the
fact that no hardware vendor is expected to allow more than 58 bits(or
alike) of address space, so a pointer can be encoded in the Nan bits. And
since there is no type inference at compile time, we must put the int64_t
boxed in a regular object.

**Comment by ChayimFriedman2** [comment]
> About storing a pointer in a double, it is a lot of trickery relying on the fact that no hardware vendor is expected to allow more than 58 bits(or alike) of address space, so a pointer can be encoded in the Nan bits. And since there is no type inference at compile time, we must put the int64_t boxed in a regular object.

Yeah I know, but how is that important here?

**Comment by mhermier** [comment]
Both, the Int64List has the disadvantage that it is hard to feed it other
than bytes else you would have a potential precision loss. But it introduce
vector computation...

**Comment by mhermier** [comment]
The point is that boxing is expensive, and doing it only for 64bits fixed
is not really worth it.

**Comment by PureFox48** [comment]
Well, if a ```Long``` object (or whatever we're going to call it) will need to be boxed then this proposal loses a lot of its attractions for me.

For my own use, I might think about building it in Wren using two ```Nums``` as fields to get better performance than ```BigInt```. One  advantage of doing this  is that I'd get a  larger range than for Int64.

Leaving the issue open for now as it's generating some interesting discussion.

**Comment by mhermier** [comment]
If you store your 2 Nums in an object you are boxing your values. The
problem stay the same has I said...

**Comment by ChayimFriedman2** [comment]
Don't get us wrong: even boxed integers will provide better performance than Wren implementation. Their performance is likely to be worse than `Num`, but it is still better if you need their special capabilities - full 64 bits integer, for example. They'll also can be hashable.

**Comment by ChayimFriedman2** [comment]
I think that we should ask a simple question:

**Have you ever need a full 64 bit space (not just in Wren)?**

If you have a concrete, non-rare use case, this proposal is worth discussing. If not - we're spending our time.

**Comment by ruby0x1** [comment]
any kind of 64 bit hash will return incorrect results without full bits

**Comment by ChayimFriedman2** [comment]
> any kind of 64 bit hash will return incorrect results without full bits

What do you mean? Why not hashing the full bits?

**Comment by ruby0x1** [comment]
`foreign static hash64(bytes)` - will return incorrect results (because of the lack of 64 bits, of course).

**Comment by ChayimFriedman2** [comment]
Ah, I understand. But you still can use `Num` with just 32 bit hash, or a four-bytes `String`. You don't need the _numeric_ value.

**Comment by mhermier** [comment]
@.ruby statement is wrong, it depends on the hash, but it is true that more
bits make room too allow better hashing functions.

**Comment by ruby0x1** [comment]
I have experienced this first hand using 64 bit hashing functions. It cannot store the full 64 bits = you will get invalid results. It _might_ fit in sometimes and appear to work but as soon as the bits in the upper range are used you get incorrect results.

**Comment by mhermier** [comment]
Rule number 1: know your platform. Doing 64bit hash when only being able to
have 54bit precision is stupid...

**Comment by ruby0x1** [comment]
They asked for a use case. Please respect others and do not speak this way in this community.

**Comment by mhermier** [comment]
It is not targeted to you. Yes the use case is valid arithmetically
speaking, but trying to fit values that can't be stored reliably, shows a
lack of the knowledge of the platform.

**Comment by mhermier** [comment]
And I never said that the point was not legitimate or not interesting. Else
I would have said nothing. The point is about discussing pro/cons of
implementing 64bit precision, or do something more extensive/reusable,
since the implementation is quite costly.

**Comment by PureFox48** [comment]
Well, perhaps I'd better close this issue now before we all fall out.

Yes, I realize that a 'home-made' ```Long``` class would still need to be boxed and wouldn't be as quick as ```Num```. But it should be quicker than ```BigInt``` and  would be relatively lightweight. So it might be a worthwhile exercise for me.

Admittedly my own interests (which include number theory) are rather specialized  and so being able to deal with large numbers is probably more important to me than it is to the majority of Wren users.

Far from being a waste of time, the discussion here has given me some valuable insights so thanks everyone for that.

**Comment by mhermier** [comment]
Personnal curiosity, if you are doing number theory, and reach wren
precision limit, you are probably dealing with numbers big enough that I
doubt that even 64bits will be enough, and you maybe have bigger problems
in the long run. But that's just my vision of the issue.

**Comment by PureFox48** [comment]
64 bit precision is often enough for the sort of problems I've been working but it's sometimes difficult to know in advance whether you're going to exceed the 53 bit limit which may invalidate your results completely.

One area which we can probably all agree is a serious limitation is the 32 bit limit for bit-wise operations but, given the way ```Nums``` are currently represented, we're probably stuck with that as far as the core library is concerned.

**Comment by mhermier** [comment]
This restriction can be greatly improved, by searching the MAX before int
starts to produce broken bits, and be more near of the 53 bits limitation.
Probably something like (1<<54)-1 or alike.

**Comment by PureFox48** [comment]
I've been assuming the maximum safe integer is  2^53 - 1 (= 9007199254740991), the same as it is in JavaScript.

I'm sure I've had results that were one out when going only a little past that limit but, thanks, I'll have a closer look at it.

**Comment by mhermier** [comment]
Change set is almost ready. Have some trouble defining MIN/MAX...

**Comment by mhermier** [comment]
Please give a try to https://github.com/mhermier/wren/tree/augment_bitwise_precision I don't plan to push it, because there are potentially controverted changes in it, and it needs more testing

**Comment by ChayimFriedman2** [comment]
If you need it for a specific use case, you can create them in your host (unless you don't control it).

This will be almost as fast as if implemented in the core. With a small disadvantage that they won't be hashable.

If that does not satisfy your requirements, you can fork them VM and implement this in the core.

Like I said, this should be fairly easy. If you need guidance, I'll happily help you.

**Comment by mhermier** [comment]
With full control, you can make them hashable, increase hash bit
precision...
Feasibility rarely the problem in propositions, and you can get help also
from me if you believe it is your way to go. The real problem is about if
the proposed solution is wise enough for insertion in core.

**Comment by eamartin** [comment]
I'm not a Wren user. I first heard of Wren today and my initial thought was "this sounds awesome". I was disappointed to learn there's no integer type.

From higher up in the thread:
> Have you ever needed the full 64 bit space (not just in Wren)?
> If you have a concrete, non-rare use case, this proposal is worth discussing. If not - we're just wasting our time.

I've frequently used 64 bit integers to represent timestamps in nanoseconds since the epoch. This is commonly done in my industry (finance, typically using C++ and scientific Python). I suspect nanosecond timestamps are also used in scientific applications. A double precision floating point only has resolution of 256 nanoseconds at today's distance from epoch.

Realistically, this isn't a must-have feature for me in a language but it is a nice-to-have. Chiming in only because someone asked if there are applications for full 64 bits. Wren looks great for embedding, I hope I find a chance to try it sometime soon.

**Comment by ChayimFriedman2** [comment]
Timestamps can be represented as a) seconds, with fractions (or hours, or days, or years). b) more than one number.

And of course, you can always provide a foreign integer type in your host. And if you really need for some reason, you can always fork Wren. The question is if that use case is broad enough.
