### ISSUE TITLE
[Meta] Have you ever considered creating a Wren Gitter page?

### ISSUE THREAD

**Issue by WilliamBehrens** [wren-lang/wren#934]
Most other languages have one and it makes it really easy to quickly interact with other Wren devs, there might be a forum for Wren already but if there is I haven't come across it.

**Comment by ruby0x1** [comment]
There's a discord community which is linked on the bottom of this page. https://wren.io/getting-started.html 

Having community in many places is not ideal so one chat platform is plenty.
