### ISSUE TITLE
[RFC] Map.fromList method

### ISSUE THREAD

**Issue by clsource** [wren-lang/wren#940]
I think that a helper method in maps can be added.
This would ease creating a map from lists 👍 

something like:

```js
var map = Map.new().keys(["key1", "key2"]).values(["value1", "value2"])
```

maybe a constructor?
```js
Map.fromList(keys, values)
```

**Comment by mhermier** [comment]
I would go for the constructor `fromLists` and use a singular if we ever add something like:
```
Map.fromList(MapEntrySequence.fromLists(keys, values))
```
or
```
Map.fromList(Sequence.zip(keys, values))
```

**Comment by ChayimFriedman2** [comment]
I think we can also add `fromEntries` constructor which takes an iterable that produces iterables of two entries, and make `MapEntry` iterable that produces its key then value. This can be useful to implement map clone, too:
```wren
var map = { ... }
var clone = Map.fromEntries(map)
```
These can be implemented like:
```wren
class Map {
  static fromEntries(entries) {
    var result = {}
    for (var entry of entries) {
      var iter = entry.iterate(null)
      var key = entry.iteratorValue(iter)
      iter = entry.iterate(iter)
      var value = entry.iteratorValue(iter)
      result[key] = value
    }
    return result
  }
}
class MapEntry {
  iterate(iter) {
    if (iter == null) {
      return 0
    } else if (iter == 0) {
      return 1
    } else {
      return false
    }
  }
  iteratorValue(iter) { iter == 0 ? key : value }
}
```

**Comment by mhermier** [comment]
I this this could be reduced to something like:

```javascript
class Map {
  construct fromEntries(entries) {
    for (key in entries) this[key] = entries[key]
  }
}
```

**Comment by clsource** [comment]
I think this would be best to be in its own class that uses maps.
A value object or proxy. To not pollute the core :).

Thanks for your thoughts 👍
