### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by clsource** [wren-lang/wren#961]
I found the tests in Wren works well. But some tests are more difficult to accomplish or write due to the // expect: comments.

I made this small test framework in Wren https://github.com/NinjasCL/domepunk/wiki/test.unit.wren

And could adapt it to work with Wren only and change the license to MIT if required.

**Comment by ruby0x1** [comment]
Part of the value in what makes the wren tests so nice is they have almost zero friction. 

This isn't a property I want to change any time soon, and don't feel a need to change the way the tests are handled currently, as I haven't run into many issues while testing.

I've used [wren-test](https://github.com/gsmaverick/wren-test) before and am very familiar with ones from js that are similar, so I'm quite well versed in how it feels to use. I prefer the way wren does it at the moment.

Thanks for the suggestion, but we'll keep the tests how they are for now!

One other note, I really enjoyed writing tests in [rust](https://doc.rust-lang.org/reference/attributes/testing.html) too. This would be more the direction I take, see also https://github.com/wren-lang/wren/pull/962
