### ISSUE TITLE
[doc] Add "Examples" section to wren.io?

### ISSUE THREAD

**Issue by cxw42** [wren-lang/wren#967]
I just tripped over #358, which has a nice (if slightly outdated) worked example of how to embed Wren into a C++ game loop.  Would it be worth adding an "Examples" (or "Cookbook") section to wren.io with things like that?  I think longer examples would be useful to people trying to understand the language.  However, longer examples don't seem to me to fit the existing sections ("guides", "API docs", "reference").  What say you?  Thanks for considering this thought!

**Comment by PureFox48** [comment]
I think it would be a good idea to have a `Wren Cookbook` with longer examples and a suitable place to link to it might be from [this page](https://wren.io/contributing.html) on the main site, perhaps under the _Growing the ecosystem_ heading.

People who have expertise in particular areas could then write articles (perhaps as Github gists) showing how to do something in that area.

**Comment by clsource** [comment]
I think this need can be solved by using the Wiki

https://github.com/wren-lang/wren/wiki

where any user can create a snippets page 👍

**Comment by clsource** [comment]
Added the wiki page https://github.com/wren-lang/wren/wiki/Cookbook

**Comment by Orcolom** [comment]
I missed this issue when I decided to do https://github.com/wren-lang/wren/pull/979 but I was looking into adding the wiki in some spaces to the website. but don't like my wording

**Comment by clsource** [comment]
@cxw42 is this ok? 👍

**Comment by cxw42** [comment]
@clsource works for me - thanks!
