### ISSUE TITLE
[RFC] Use `in` keyword as a binary operator.

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#968]
At present, the `in` keyword isn't an operator as such but a particle whose only use is within a `for` statement:
```javascript
for (e in seq) // blah
```
Despite this, I keep finding myself wanting to type stuff like this:
```javascript
if (e in list)   // list
if (i in 0..5)   // range
if ("e" in str)  // string
```
Now all of these scenarios can be dealt with by using the `Sequence.contains` method or an override thereof for a particular class:
```javascript
if (list.contains(e))   // list
if ((0..5).contains(i)) // range
if (str.contains(e))    // string
```
but I think most folks would agree that it's not as nice.

So do you think it would be worthwhile re-classifying `in` as an overloadable binary operator (perhaps with the same precedence as `is`) which would enable us to use it as syntax sugar for the `contains` method?

For example:
```javascript
class String {
   // ...
   in(str) { (str is String) && str.contains(this) }
}
```

**Comment by PureFox48** [comment]
BTW, if anyone's wondering how `in` could be implemented for every type, given that any kind of object can be included in a Sequence, what I had in mind was to provide a default implementation in the Object class itself which each type would inherit:

```javascript
class Object {
   // ...
   in (seq) { (seq is Sequence) && seq.contains(this) }
```

It would only be necessary to override this method if the type in question (such as String) had its own override of the `contains` method.

I'm assuming there is no technical problem with Object referring back to its sub-class, Sequence, but if there is no doubt someone will tell me.

**Comment by mhermier** [comment]
Mixed feelings, while I agree it would be a nice sugar syntax, it seems to be too much specific.

Thought I think default implementation should be:
```javascript
class Object {
  in (seq) { seq.contains(this) }
}
```
Some containers might not be able to inherit from `Sequence`, while still implement `iterate(_)` and `iteratorValue(_)`.

**Comment by PureFox48** [comment]
As you may have gathered, one reason why I've suggested this now is because it may help with pattern matching a list of values for Option 1 (and possibly Option 3) of  the `switch` statement proposal in #956. It doesn't really help with Option 2 as we can just list the values after the `case` keyword.

However, I also think it stands on its own as a nice feature for Wren to have.

**Comment by mhermier** [comment]
Sure the case is legitimate.

Thought, I think it is more important to have a method/operator that does more generic thing. Something like (there may be a more appropriate name):
```javascript
class Object {
  transform (transformFn) { transformFn.call(this) }
}
```

**Comment by PureFox48** [comment]
Well perhaps something like that would be good to have as well but, unless I'm missing something, it wouldn't make current usage of the `contains` method any nicer.

**Comment by mhermier** [comment]
That's not the point, I'm raising. If `in` become a thing, its generic counterpart should/must also be there.

**Comment by PureFox48** [comment]
OK, fair enough.

**Comment by mhermier** [comment]
Does this looks odd ?
```javascript
42 in Fn.new {|value| value.isInteger }
```

**Comment by PureFox48** [comment]
It does look odd to me because, if you try to analyze it using the normal rules of Wren, `Fn.new {|value| value.isInteger }` returns an instance of Fn, not a container, and so there's no way that can contain 42.

I imagine you're using the function to generate a lazy list of integers of which 42 is one but unless you know that convention is being used it makes no sense.

**Comment by mhermier** [comment]
Ok, I have my answer, it doesn't provides the intent I hopped. Also, for some extra other reasons, the generic version should have its own name.

**Comment by ChayimFriedman2** [comment]
I think we should reverse the operator: `x in y` should translate to `y.in(x)`, so confusion doesn't land.

Alternatively, make the `in` operator use another method, like `contains()`.

And about `in Fn`, you can always create a `Predicate` type:
```wren
class Predicate {
  construct new(predicate) { _predicate = predicate }
  call(value) { _predicate.call(value) }
  in(value) { _predicate.call(value) }
}
```

**Comment by PureFox48** [comment]
Funnily enough, I started off with it the other way around but then realized that there were no other operators in Wren where the argument preceded the receiver (`element in this`) so I changed it back to the conventional order.

If you think it would be viable to reverse the operator, then we could put the default `in` implementation in the Sequence rather than the Object class which might be better.

**Comment by ChayimFriedman2** [comment]
That's why I want to reverse it.

**Comment by PureFox48** [comment]
Fine, thanks :)

**Comment by cxw42** [comment]
I support `x in y` === `y.in(x)` or `y.contains(x)`.  That is the model of Raku smartmatch :) , discussed at https://github.com/wren-lang/wren/issues/956#issuecomment-817233866 .  And, more to the point, membership is something associated with the container `y`, not the contained element `x`.  Checking for membership should therefore be done by the container for the sake of cohesion.

**Comment by mhermier** [comment]
I think that inversion is problematic for comprehension. Commutativity is not a thing, as it would be resolved at runtime, which is still a no-no for obvious performance reasons.
I think it is better to stick to the simplest definition `in` is the inverted version of `.contains(_)`, and nothing more.

**Comment by PureFox48** [comment]
So can we all (@mhermier?) agree that, if `in` were reclassified as a binary operator, the following would be the default implementation for sequences such as List and Range:

```javascript
class Sequence {
    // ...
    in(element) { this.contains(element) }
}
```
The String class has its own `contains` method, implemented in C, so we'd need to implement `in` separately there so we pull in its own `contains` version.

However, the next question (for the compiler experts) is how do we change `in` so that it becomes an overloadable binary operator?

Looking at `wren_compiler.c` I can see two obvious changes would be needed:

In the GrammarRule array, `TOKEN_IN` would need to be changed from `UNUSED` to `INFIX_OPERATOR(PREC_IN, "in")`.

`PREC_IN` would need to be added to the Precedence enum.

However, I'm lost after that. In particular:

1. Would reclassifying `in` as an operator have any impact on its current use as a particle in the `for` statement?

2. Would `in` require special handling given that the operands would be the other way around compared to the other binary operators?

**Comment by PureFox48** [comment]
Incidentally, regarding precedence level, I thought initially that we could give it the same level (11) as the `is` operator but, given the operand reversal,  I'm thinking now that it might be better to give `in` its own precedence level (inserted say at 12) and add a note about that in the docs.

**Comment by mhermier** [comment]
@PureFox48
No I don't agree, this is a non sense, the in operator does not make any sense as a commutative operator.
The way you try to add it to the grammar is using the default infix path in the compiler, and it will need to be commuted. You are trying to force the way for a commutative operator, and this will makes precedence. So it is a big NO as this.

1. Technically no problem with `for` as it expect specific tokens and it does not involve expression parsing till the `Sequence` argument.
2. Yes and this is the most annoying part because `in` is meant to be an inverted operand. To make things simple, it should be implemented as a builtin operator that call `.contains(_)`. To do that a SWAP opcode to swap the top 2 elements on the stack is required.
3. Error is the only logical behavior, if the rigth hand does not has `.contains(_)` it has no meaning to call `in`.

**Comment by PureFox48** [comment]
Well, this is why I edited the original proposal to avoid reversing the operands.

So it brings us back to either providing a default implementation for `in` within the Object class or (much better) implementing it as a built-in operator which calls `.contains(_)` as you've just suggested.

Thanks for confirming that there should be no impact on the `for` statement implementation.

I agree that the only sensible behavior for classes which don't have a `contains` method is to error out.

So, @ChayimFriedman2  and @cxw42,  despite what you said earlier would you be happy to proceed on this basis?

If so, we can ask @ruby0x1 to review the proposal with a view to possible adoption.

**Comment by mhermier** [comment]
I don't know what she'll say but considering benefits, costs (even in the seamlessly implementation form), and the more importantly the current time, I would say it is too early and possible future adoption would only depends on the `switch` form.

**Comment by PureFox48** [comment]
Well, now that v0.4.0 has landed, she'll be looking for stuff to add to v0.5.0.

This has good support and is not particularly complicated.

So I'm hopeful but we'll see :)

**Comment by PureFox48** [comment]
Incidentally, this proposal isn't really anything to do with `switch`. I think it's worth doing purely on its own merits. 

I just decided to raise it now as I thought it might be useful to express complex conditionals if `switch` is adopted.

**Comment by mhermier** [comment]
Well as this, this proposal is pure syntax sugar, so it is absolutely not vital. Depending on the `switch` form, because there is no possibility to inverts the test arguments, the importance will mechanically raise.

**Comment by ChayimFriedman2** [comment]
Implementing it on `Object` is fine, but I still think it's prefered to not, because:

 1. If you implement it in `Object` you can overload it, which can lead to unexpected things.
 2. This will have to be implemented in Wren, giving a performance loss.

Instead, I think we should give it a special treatment in the compiler (not the runtime!) and translating `x in y` to:
```
<calculate x>
<calculate y>
CODE_SWAP (new opcode)
CODE_CALL_1 <in(_)>
```
Or, alternatively:
```
<calculate x>
<calculate y>
CODE_CALL_IN (new opcode)
```
Though I think the former will be easier to implement, even if slightly less performant.

**Comment by cxw42** [comment]
- I think @mhermier's https://github.com/wren-lang/wren/issues/968#issuecomment-819464623 is reasonable.  
- `x in y` => `y.contains(x)`
- Runtime error if `y` does not implement `contains(_)`.  
- I heard in a comment on another issue that opcodes are not a scarce resource, so a new opcode for CALL_IN or a generic CALL_SWAPPED seems good to me.

@PureFox48 please let me know if there is anything from your https://github.com/wren-lang/wren/issues/968#issuecomment-819477834 that I missed!

**Comment by ChayimFriedman2** [comment]
> I heard in a comment on another issue that opcodes are not a scarce resource

We have 179 free (77 used). So, definitely not scarce.

**Comment by mhermier** [comment]
The problem is not really about being scarce, but more about a complex interactions between re-usability and the impacts of adding opcodes. Adding an opcode is not as cheap as it sounds, it can impact speed in some pretty unexpected manners. I'm not sure about the reasons thought. I don't know, if it is caused by the compiler making worse job at optimizing the code, cache misses due to an increase code memory size of the busy loop, or another matter I didn't understand.
Considering more operators might need the inversion in the future, and the low appearance of `IN` compared to other it is a no no for me.
`CALL_SWAPPED` could mean something, thought it has too be well tested... to see the impact of adding dispatch (or maybe abusing `CALL` again).

**Comment by jube** [comment]
Making `in` an operator is very confusing. Especially if `x in y` means `y.contains(x)` for two reasons:

- `in` in `for (x in y)` does not mean `for (y.contains(x))` so `in` would have two meanings in different situations. That defeats the purpose of simplicity of Wren.
- The gain of writing `x in y` is very low (not really a common situation) compared to the amount of changes required and the potential confusions. Why does this function `contains` would need a special operator? And what would be the other purpose of overloading a binary `in` operator?

IMO, this is a bad idea in the first place.

**Comment by mhermier** [comment]
As I stated earlier, the only real gain happens where there is an
impossibility to reverse operands position. For now, it can happen in other
forms with certain forms of `switch` statements that are still debated.

**Comment by PureFox48** [comment]
An `in` keyword is a very natural way to express containment and is used, for example,  in Python in exactly the way I'm proposing for Wren - see [here](https://www.w3schools.com/python/ref_keyword_in.asp).

It may be that if we could implement this in the way @mhermier proposed, that it needn't be overloadable at all. Apart from being a nice way to express containment, I can't think of any other use for it.

**Comment by mhermier** [comment]
Regardless of the utility debate, making it a built-in, allow to postpone
the debate of making it a real operator. If it were to be implemented as
this, we can later switch to a more regular operator if another use case
emerge (though I doubt it because of the very narrow meaning of `in`).

**Comment by avivbeeri** [comment]
I like this from an expressibility point of view, but I don't find a burning need for it myself. Are there any situations where it might cause confusion or unexpected behaviour?

As an aside:

> An `in` keyword is a very natural way to express containment and is used, for example, in Python in exactly the way I'm proposing for Wren - see [here](https://www.w3schools.com/python/ref_keyword_in.asp).

I don't think "Other languages do it like this so it is okay for Wren to do it" is a strong enough argument to justify any particular syntax or language feature. Wren isn't python, and so we shouldn't be trying to enable the same idioms. That could lead to a very slippery slope.

**Comment by PureFox48** [comment]
Although I'd generally agree with what you said in your last paragraph, I thought it was worth pointing out that this idea hasn't come out of of thin air but is used by what is one of the most popular languages in use today.

It may be because of this that I find myself wanting to write it that way.

**Comment by mhermier** [comment]
Sorry about the rant that will follow, but maybe it can make some sense to
some...

This subject is complex and took me a long time to understand, and was
quite pretty well documented in on of "Brian Williams" (if I remember it's
name correctly) youtube video: "OOP is embarrassing". The OOP mindset
impose a phrase like way to write expression. And this is exactly what the
`in` operator is, a way to express as you speak.

Good or bad, the OOP mindset impose you some mental constructions to
express yourself that looks natural to you, but that are not natural in the
computation world.

This keyword is one of the example of the results that naturally happens
when you follow that mindset.

**Comment by PureFox48** [comment]
Well, unless I'm very much mistaken Wren **is** an object-oriented language. It is described on the home page of this repository as: "a small, fast, **class-based** concurrent scripting language".

So I make no apologies for having an OOP mind-set.

However, ISTM that an `in` keyword has nothing to do with OOP anyway. I don't think anyone would regard Python as a beacon of OOP,  yet it has this keyword.

**Comment by mhermier** [comment]
The rant is more about, this is not because the language is OOP that it has
to be the answer to all problems.
The moves in the C++ standard, to use more functions and have less methods
unless necessary is a direct result of that réalisation.

**Comment by mhermier** [comment]
All operator in existence correspond to a method call, and those that seems
that don't are just converting arguments so it fits to a method call. Even
the ones that look like functions, are just an artefact of writing. So it
is definitely OOP.

**Comment by PureFox48** [comment]
Wren allows you to program in a procedural or even functional style and I frequently do for short scripts. However, it doesn't change the fact that it's fundamentally an OO language since even functions and fibers are objects.

In any OO language, operators are just fancy methods - that's just the nature of the beast. But, when I say that `in` has nothing to do with OOP, it's because it can just as easily be built into a purely procedural language.

There has been a lot of criticism of the OO paradigm in recent years, particularly in the area of inheritance where it is felt that containment is often a better strategy.  I think this is a fair point but it doesn't mean that you shouldn't use inheritance at all.

Also many traditional OO languages - C++, C#, Java etc - have such Byzantine object models that it puts people off from using them. The relative simplicity of Wren's object model is one of the things which attracted me to the language in the first place.

**Comment by mhermier** [comment]
No, you can't write it as a single universal function. At some point to
type inference as to happen, because argument of such function has to
accept any type on parameters.

The point is that because of cognitive bias we tends to use what we were
successful with. What I think is more sane is to use OOP where it is
necessary, and where it is good at: providing an abstraction and protect
internals. The biggest problem is where to draw the line, and because if
the bias we tend to over abstract.

To come back to the original topic, unless there is an urge, where we have
a situation where inverting arguments would make the situation really
unpleasant/performing bad because it requires more inefficient expression
to achieve the same result, and considering how almost trivial it is too
implement as a built-in, I would let it at the user discretion to implement
it for himself and not add it to the main language for now (since it would
also needs more validation work).

**Comment by PureFox48** [comment]
> I would let it at the user discretion to implement
it for himself and not add it to the main language for now (since it would
also needs more validation work).

OK, well I'll wait and see whether the supporters of the proposal agree with that. If they do, then I'll withdraw the proposal and close the issue so @ruby0x1 doesn't have to waste her time reviewing it.

**Comment by mhermier** [comment]
There is an alternative possibility, make it leave in a feature branch. I'm
considering more and more to do it for some of the patches I have.

**Comment by PureFox48** [comment]
I think I'm right in saying that only 'members' can add labels such as `Future` to issues. I can't see any obvious way for me to do it myself anyway.

**Comment by mhermier** [comment]
If I understand correctly what you are talking about, I think effectively
that some privilege are required to manage issue labelling. That said the
interface is not really clear, to who owns some privileges...

**Comment by PureFox48** [comment]
I thought that labeling the issue is what you meant in https://github.com/wren-lang/wren/issues/968#issuecomment-820367949 but perhaps you meant something else?

**Comment by mhermier** [comment]
All the time I mention label at the origin was a reference to #964, until last message where you talked about `Future` which refer to the github label system.

**Comment by cxw42** [comment]
@PureFox48 I just opened #989 for smartmatch --- I support binary `in` but would suggest we roll that function into the more general smartmatch.  I would add `CALL_SWAPPED` per https://github.com/wren-lang/wren/issues/968#issuecomment-820196805 .

**Comment by PureFox48** [comment]
Yes, I think you're right that a new smart-match operator would give us the benefits of this proposal and much more besides.

As reservations have been expressed about reusing `in` for this purpose anyway, I'm going to close this proposal now in favor of #989.
