### ISSUE TITLE
[RFC] Allow an empty for statement to be used as an infinite loop.

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#973]
Most C-family languages don't have a dedicated infinite loop. Instead they use constructions such as `for(;;)`, `while(1)`, `while(true)` or `do..while(true)` of which perhaps the first one is the most common.

An exception to this is `Go` which uses `for` as a dedicated infinite loop.

Currently, in Wren most folks seem to use `while (true)` for this purpose though the more cryptic `while (1)` or even `while (0)` - as any number is truthy - are also options.

What I'd like to propose is that we also allow an empty `for` statement, `for ()` to represent an infinite loop. This is shorter and looks more like a dedicated loop than `while (true)` and would bring us more in line with what other languages do. If we had it, I personally would use it all the time for this purpose.

There will be those who will say that we shouldn't be influenced by what other languages do. However, the truth is that Wren isn't developed in a vacuum and there's a reason why most of our keywords are the same as in other C-family languages, namely familiarity.

I look forward to hearing your views on this.

**Comment by mhermier** [comment]
Considering low usage of it, and the lalel'ing effort that is going on, it is an ultra low priority for now to determine the correct syntax for this. It is a nice optimization to have a forever loop, but I would like to see numbers before accepting such change.

**Comment by PureFox48** [comment]
Well,  as we don't have `do..while(cond)`, I tend to use infinite loops more in Wren than when programming say in C:
```javascript
while (true) {
    // blah
    if (cond) break
}
```
Although I'd consider Rust to be a C-family language, like Go, it has some unusual syntax so I agree that it's not a good language to compare Wren with.

**Comment by ChayimFriedman2** [comment]
If we want a new construct for infinite loop (although I don't think this is needed), then I think `for ()` has no advantage over `while (true)`. I would use `loop` instead, since they both stands for an infinite loop ("forever" or "while true"), but the intention is to break - so `loop` is a better name.

**Comment by ChayimFriedman2** [comment]
I agree, and that's why I think we shouldn't do it.

**Comment by avivbeeri** [comment]
I don't think `for ()` is a good idea for the language, as it isn't self-explanatory. It could just as easily mean "skip this", "perform this action once" or "loop forever"

`while(true)` is a lot clearer in its behaviour as an infinite loop.

**Comment by PureFox48** [comment]
OK, I think it's already clear that the use of `for()` as an infinite loop is going to lack the necessary support so I'll close this now as I don't want to clutter up the issues list.

Thanks everyone for your comments.

**Comment by clsource** [comment]
My preference would be a simple while block 

```js
while {
  my_infinite_instructions.call()
}
```

**Comment by ChayimFriedman2** [comment]
I find it less readable than `while (true)`.

**Comment by PureFox48** [comment]
Also you'd always need to use a block. In the example you give, you couldn't really put the single line of code on the same line as `while` because, without the following parentheses, it might just be a syntax error.
