### ISSUE TITLE
Undocumented behavior of the return keyword.

### ISSUE THREAD

**Issue by PureFox48** [wren-lang/wren#974]
One thing I've noticed recently is that, if you're in the middle of module-level code (i.e. code which is neither inside a function or a method), then the `return` keyword will jump to the end of that module. For example:

```javascript
/* mod_ret1.wren */

for (i in 1..2) {
    if (i == 2) return
    System.print(i) // prints 1 but not 2
}

System.print(3) // doesn't print

/* output:
1
*/
```
However, it only jumps to the end of the module it's in, not the end of the script:
```javascript
/* mod_ret2.wren */

import "./mod_ret1"
System.print(4) // prints 4

/* output:
1
4
*/
```
So it seems to work as if the module-level code is wrapped inside a function and then that function is automatically invoked.

Does anybody know whether this behavior is intended because, if it is, I couldn't find it documented anywhere.

If it is intended then:

1.  It could be useful for exiting a module and possibly the entire script prematurely without the need for ```Fiber.abort```.

2.  I could try and do a PR to document it somewhere.

**Comment by mhermier** [comment]
I have no memory it was or not intended. Since it seems there is no test
for it, I would guess that not really. It is an interesting behavior,
though AFAIK it does not really make sense a value since it cannot be
accessed unless I' missing something... If you document it also add a test,
at minimum.

**Comment by PureFox48** [comment]
Although the code still works if you return a value, the value can't be accessed and is therefore just discarded, as you surmised.

**Comment by mhermier** [comment]
Check wren-cli, maybe retiring from main module would change exit code, and
would be a proof it was intended.

**Comment by ChayimFriedman2** [comment]
I'm aware of this, and I remember there was a discussion about that. I'll update here once I've found it.

**Comment by ruby0x1** [comment]
The discussion mainly covers that it is valid as top level Wren code is normal imperative code. Return stops executing the module code (which implementation detail wise, is running as a function). While documenting the behaviour is a reasonable goal there the behaviour itself is fine.

The default path drops the return value because `import` keyword has no way to capture it, but in context of an explicit `var value = System.import(module)` method it is possible to capture and use the return value. Currently that doesn't exist in Wren main branch but I have used it locally in mine before.

**Comment by PureFox48** [comment]
I ran this code using wren-cli:
```javascript
import "./mod_ret1"
System.print(4) // prints 4
return 5
```
but it didn't appear to affect the exit code.

`echo $?` just returned 0.

**Comment by PureFox48** [comment]
@ruby0x1 
If you're thinking of adding `System.import(module)` to the main branch, then I could refrain from trying to document this for the time being.

Otherwise I was thinking of adding something like this at the end of the `Modularity` section in the docs:

### Exiting a module prematurely

Although the `return` statement is normally used to exit from a method or a function, it can also be used from a module's top-level code to exit the module. For example, if the script consists of a single module, this code would exit the module (and therefore the script) prematurely:

```javascript
for (i in 1..2) {
  if (i == 2) return
  System.print(i)  //>  prints 1 but not 2
}
System.print(3)    //>  not reached
```
Although it is not invalid to return a value, there is no way to access that value and it is therefore simply discarded.

**Comment by ruby0x1** [comment]
@PureFox48 I edited it for simplicity, a PR for that would be welcome still regardless of the future.

**Comment by PureFox48** [comment]
Great, thanks :)

I've done the PR now.

**Comment by clsource** [comment]
> Although it is not invalid to return a value, there is no way to access that value and it is therefore simply discarded.

This is not 100% true. Although the return value is discarted using the`import` keyword, you can still access the value if you use it with compile :) 

Example:

```js

import "meta" for Meta

var sum = Meta.compile("""
  class MySum {
    static sum {2 + 2}
  }
  
  return MySum
""").call()

System.print(sum.sum)
```

**Comment by PureFox48** [comment]
Good point, I hadn't thought of that!

Although the original PR has been merged, I've done another one to correct the final paragraph.

**Comment by ChayimFriedman2** [comment]
@clsource unfortunately you're wrong, `Meta.compile()` just wraps the code in a function, but the module is the same. You can see it yourself:
```wren
import "meta" for Meta
var X = 5
Meta.compile("X = 6").call()
System.print(X) // 6
```
Or by looking into the source (https://github.com/wren-lang/wren/blob/eca90e29e9665cce715db20a95763a3eb750e8f2/src/optional/wren_opt_meta.c#L10-L38)

So you're returning from a function, not module.

**Comment by mhermier** [comment]
In technical details, modules are evaluated the same way. What the example
annoys me is that it does not have anything to do with modules... Behind
the scene it is the same, but the interface is completely different.

**Comment by clsource** [comment]
I use this technique in chercán

```js
var page = Meta.compile(File.read(filename)).call()
```

So I read the file in a string and then pass it to compile.
It works :)

**Comment by mhermier** [comment]
Well this is not exactly equivalent to module loading because of the scope
of variables evasion.

**Comment by ChayimFriedman2** [comment]
> In technical details, modules are evaluated the same way. What the example annoys me is that it does not have anything to do with modules... Behind the scene it is the same, but the interface is completely different.

Not exactly... It has differences because it is evaluated in the same module (and because of variables evasion, like you said).

> I use this technique in chercán
> 
> ```js
> var page = Meta.compile(File.read(filename)).call()
> ```
> 
> So I read the file in a string and then pass it to compile.
> It works :)

...unless you define something with a name that already exists in the caller:
```wren
import "meta" for Meta

class DynamicImport {
  static do(contents) { Meta.compile(contents).call() }
}

System.print(DynamicImport.do("""
return "I am a module"
""")) // I am a module
System.print(DynamicImport.do("""
class Cool {}
return Cool
""")) // Cool
System.print(DynamicImport.do("""
class DynamicImport {}
return DynamicImport
""")) // Oops, crashing
```

This is why when meta-programming I always separate the class (say, `Enum`), to a different module, and give it a name that should not clash (will you name your enum `Enum`? Well, maybe we need `EnumGenerator`). Still, if someone really wants, they can crash it.

**Comment by clsource** [comment]
My point was using the return value.
Clearly using `import` keyword is different from `Module.compile`. 
If you really need the _return value_ you could use the `Module.compile` way. But you should keep in mind the nuances you already said. Its not module loading per se, but its a way of using the return value 👍

**Comment by ChayimFriedman2** [comment]
The return value of _what_? It's just a function! If you have a peace of code that you know _ahead of time_, then _do not_ use `Meta.compile()` for it, even if it needs to return a value, just wrap it into a function!
```wren
// a.wren
var ReturnsAValue = Fn.new {
  return 5
}

// b.wren
import "./a" for ReturnsAValue
System.print(ReturnsAValue.call())
```

**Comment by clsource** [comment]
That only works if you know before hand the filename.
Since imports are not dynamic I have to improvise using `Meta.compile` 
for loading different files with I didn´t have the filename before hand

**Comment by ChayimFriedman2** [comment]
I completely agree (though, for the reasons I stated above, `Meta.compile()` is not a replacement for dynamic imports, say `System.import()`). But this is something to be said above `Meta.compile()`, not about the `return` keywords.
