### ISSUE TITLE
[RFC] Protocols or Traits

### ISSUE THREAD

**Issue by clsource** [wren-lang/wren#993]
This is not a request for adding a `protocol` or `interface` keyword. Mostly is just a way of extending the functionality of `String`, `Num`, et al.

By having a protocol one can create a `String` like class that inherits String methods. And because this class is not a normal string then it can be extended.

```js
class StringProtocol is String {
   construct new (string) {_string = string}
}
```

Then one can implement such extensions to string

```js
class EString is StringProtocol {
   toUpper { // upper case _string }
}

if (EString.new("my string").toUpper == "MY STRING") {
  // is uppercase
}

```

I don't know if this is possible but is just an idea.

**Comment by mhermier** [comment]
You can always create a proxy class, and you can even make it almost a
perfect proxy by overloading `is`. The only thing you can't fake is the
`type` interrogation.

**Comment by ChayimFriedman2** [comment]
> The only thing you can't fake is the `type` interrogation.

Why not?
```wren
class StringWrapper {
  construct new(s) { _s = s }
  type { String }
}
```

**Comment by mhermier** [comment]
AFAIK the compiler populate it so you should not be able to overload it...

**Comment by ChayimFriedman2** [comment]
It does work (BTW, we should add persistent links to the playground).

It's just a normal method on `Object`, but you can override it.

**Comment by mhermier** [comment]
Well, I would say it is an error to allow it. While it has no consequence in the VM, the real way to pretend to be some other class should only be overloading the `is` operator, that was designed for that purpose.
When entering a foreign function, you have to distinguish between the real thing and a proxy. Allowing to override `type` does not offer wren code to protect itself from entering foreign functions with bad values.

**Comment by clsource** [comment]
Ok here are some ideas

- http://scg.unibe.ch/archive/papers/Ress11a-Talents.pdf
- http://scg.unibe.ch/archive/papers/Scha03aTraits.pdf

Solving extending built in classes without subclassing can be achieved by using Traits and Talents.
This would need:

- 1) A mechanism to add functions or properties to a class in runtime
- 2) A modified algorithm for scope resolution that considers runtime added properties or functions

## Adding traits

First we need to add a container to the class. This is an example with String. can be added to the _Object_ class.

```js
class String is Sequence {

 // traits are extensions at the class level
  static traits { 
     if (!__traits) { 
        __traits = {}
     }
    return __traits
  }
 
 // talents are similar to traits, but at instance level
 static talents {
   if (!__talents) {
      __talents = {}
   }
   return __talents
 }

}
```

- A trait can be a raw value or a function. If is a function it would receive the class as the first param, other params as an array for the second params.
- A talent can be a raw value or a function. If is a function it would receive the instance as the first param, other params as an array for the second param.

## Example

Lets add a `reverse` talent to a String.

```js
// Add a reverse method to the talents
String.talents["reverse"] = Fn.new {|instance| instance[-1..0]}

// Lets use it
var myString = "1234".reverse() // expect: 4321

// Lets add a trait that just returns abc
String.traits["abc"] = "abc"

System.print(String.abc) // expect: abc
```

## Scope Resolution

For this to work it would need a new search inside talents or traits before not found error.

### Trait is a function

- 1. Search for the expected scope resolution
- 2. If not found and is using a class method. Then look inside the `traits` map for a key with the same name.
- 3. If the value inside the key is a function then call it passing the class as the first param and the other params
- 4. Return the value from the function

### Trait is a value

- 1. Search for the expected scope resolution
- 2. If not found and is using a class property. Then look inside the `traits` map for a key with the same name.
- 3. If the value inside the key is a value. Then just return it.


### Talent is a function

- 1. Search for the expected scope resolution
- 2. If not found and is using an instance method. Then look inside the `talents` map for a key with the same name.
- 3. If the value inside the key is a function then call it passing the class as the first param and the other params
- 4. Return the value from the function

### Trait is a value

- 1. Search for the expected scope resolution
- 2. If not found and is using a class property. Then look inside the `traits` map for a key with the same name.
- 3. If the value inside the key is a value. Then just return it.

**Comment by mhermier** [comment]
This strangely looks like an ECS on steroid, and scope resolution seems over complicated. In particular I don't know how it can solve forward declared traits scope lockups, since scoping seems implies the knowledge of the layout of the trait (unless I'm misunderstanding things).

**Comment by clsource** [comment]
Maybe I overcomplicated things because I am still groking the scope resolution algorithm.
But the basic idea is just that if a not found error is triggered (with the current rules). Then look for the `traits` and `talents` properties, if something is found there and return the value. If the key is not found then trigger a not found error.

Since they are static methods they would be only available to the class which you are applyng them.
Instance properties can be added too for passing down the traits and talents to children.


Maybe we can separate to these concepts:

```js
class String is Sequence {

    // traits are extensions at the class level. Cannot be inherited to children.
    static traits__ { 
        if (!__traits) { 
            __traits = {}
        }
        return __traits
    }
    
    // talents are similar to traits, but at instance level. Can be inherited to children.
    talents__ {
        if (!_talents) {
            _talents = {}
        }
        return _talents
    }

    static trait__ (scope, name, value) {
        // check for name to be a valid identifier
        if (!isValidIdentifier(name)) {
            return Fiber.abort("%(name) is not a valid identifier")
        }

        traits__[name] = {
            "scope" : scope,
            "value" : value,
            "isFn"  : (value is Fn)
        }
    }

    talent__ (scope, name, value) {
        // check for name to be a valid identifier
        if (!isValidIdentifier(name)) {
            return Fiber.abort("%(name) is not a valid identifier")
        }

        talents__[name] = {
            "scope" : scope,
            "value" : value,
            "isMethod"  : (value is Fn) // Would determine if this would be a property or a method
        }
        
    }

    // Public api
    static useClassTrait (name, value) {
        trait__("class", name, value)
    }

    static useInstanceTrait (name, value) {
        trait__("instance", name, value)
    }

    useClassTalent (name, value) {
        talent("class", name, value)
    }

    useInstanceTalent (name, value) {
        talent("instance", name, value)
    }

}
```

```js


String.useClassTrait("1234", 1234) = 1234 
// Error. keys must be valid identifiers.

String.useInstanceTrait("hello", "Wren") 
// This would be available to all instances of String. Example: "hola".hello() // expect: Wren

MyParent.useClassTalent("abc", "abc")
 // MyParent.abc and MyChildren.abc would be available since is inherited
```

**Comment by mhermier** [comment]
Unless I'm mistaken, I don't think you need to differentiate `trait` and `talent`, one is a `trait` of the class the other is the `trait` of the meta class.

As this, it looks a little too rough/new, to have a clear idea of what it is doing, and the implication it has. One concern I have is that it seems that registration of traits/talents is voluntary, and does not guarantee an API of a sub-classed instance.

**Comment by mhermier** [comment]
As this, it looks a lot like a mirror API with write access and It make me fell nervous/not at ease.

**Comment by joshgoebel** [comment]
In reading some of this I feel I almost see a hidden argument for something like `method_missing` / dynamic dispatch from Ruby. http://rubylearning.com/satishtalim/ruby_method_missing.html

If (big if) dynamic dispatch is truly desirable then why not go all the way and (as a last resort) just let classes decide how they respond to ANY method dispatch at run-time?  If this one thing was added then any number of competing trait/talent systems could easily be built on top of that singular foundation.  

Although having to pass in `instance` to every trait function is annoying in that I presume it implies there would be no way to work with fields that exist on the classes, which seems a very natural thing one might want to do inside a trait. It seems traits should exist inside the scope of an instance, not outside it.

**Comment by mhermier** [comment]
@joshgoebel while this would be a possibility for implementation details, could you elaborate on how you see the thing? Because, to me, it does not seems really trivial to hook execution to traits methods in a generalized way.

**Comment by Orcolom** [comment]
> Although having to pass in instance to every trait function is annoying in that I presume it implies there would be no way to work with fields that exist on the classes, which seems a very natural thing one might want to do inside a trait. It seems traits should exist inside the scope of an instance, not outside it.
I disagree, don't want people to mess with internals they shouldn't touch

**Comment by mhermier** [comment]
It is complicated, while it should be able to access its owns, it should be able to access the methods of `this` to retrieve data from them. So it could be simplified to a bunch of unbound methods with a storage size. And things get messy when defining how to initialize and destroy them.

**Comment by clsource** [comment]
The dynamic dispatch on ruby reminds me of PHP magic methods

- __call
- __callStatic
- __set
- __get

https://www.php.net/manual/en/language.oop5.overloading.php#object.call

Which are called by the interpreter when a method or property is not found. If they are found in the instance then would be called as the last look up before triggering a not found. 

If a similar mechanism is implemented for wren then some things can be achieved.

I would call these: "Wren hooks" special methods that begins with three underscores ___method. Which are called on the lifecycle of a class and objects if found.

**Comment by joshgoebel** [comment]
> Which are called by the interpreter when a method or property is not found. If they are found in the instance then would be called as the last look up before triggering a not found.

@clsource Exactly, you got the idea. :-)  Of course in Ruby everything is an object, so we don't need static vs non-static... since the class itself is just an object that can have it's own `method_missing`... I don't think we need to copy the PHP naming with a bunch of underscores... I wouldn't mind a single well named method you could provide that had special meaning...

BUT with Wren even this is a bit more complex since the signature includes number of arguments... so

```js
method_missing(name, arg)
// would be entirely different from
method_missing(name, arg1, arg2, arg)
```

Perhaps that's not a bit deal though and you'd just write out however many signatures you needed?

**Comment by mhermier** [comment]
The re-entrancy red flag is tickling me... And having arguments as normal arguments, meaning that the 16 arguments version cannot be called, but it is a minor annoyance. And the naming is annoying.

The idea is interesting thought, I only have high doubts on the form and feasibility...

**Comment by clsource** [comment]
I will create a new PR to address hooks. I think Traits should wait until the scope resolution is achieved first 👍

**Comment by clsource** [comment]
I will close this since it may need futher development.

I think a good solution for this is the proxy class https://github.com/wren-lang/wren/issues/993#issuecomment-827377311

Or value objects https://en.wikipedia.org/wiki/Value_object

**Comment by clsource** [comment]
Just a couple of final though. And I don´t know if this is feasible.
Just having an static dictionary for traits. No fancy checks or boilerplate.

```js
class TraitTest {
  static trait(key) {
    return TraitTest.traits[key]
  }
  
  static trait(key, value) {
      TraitTest.traits[key] = value
  }
  
  static traits {
    if (!__traits) {
      __traits = {}
    }
    return __traits
  }
}


TraitTest.trait("hello", Fn.new{System.print("World")})
TraitTest.trait("hello").call()
```

With this you can extend the core classes withouth inheritance.

```js
class String {
  static trait(key) {
    return String.traits[key]
  }
  
  static trait(key, value) {
      String.traits[key] = value
  }
  
  static traits {
    if (!__traits) {
      __traits = {}
    }
    return __traits
  }
}

class StringTraits {
  static init() {
    String.trait("hello", Fn.new{System.print("World")})
  }
  
  static hello() {
    return String.trait("hello").call()
  }
}

StringTraits.init()
StringTraits.hello()

```
