### ISSUE TITLE
What's the purpose of wren_test.make in projects/make?

### ISSUE THREAD

**Issue by sukhchainn** [wren-lang/wren#995]
I compiled make project with MinGW32 GCC on windows. It compiled all the object files and .d files which were needed for wren. But it did the same for wren_test.make too. I was expecting that it would generate executables, is it the expected behavior or a bug?

**Comment by ruby0x1** [comment]
If you ran them from the project folder ([details here](https://wren.io/getting-started.html#building-wren)) you'll get a `wren_test` inside `bin/` which runs the test suite. If you're looking for an interpreter or repl to run scripts instead, the [Wren CLI link here](https://wren.io/getting-started.html#trying-out-the-language) is what you're after.

**Comment by sukhchainn** [comment]
thanks!
